// Extended seed data for pipeline, leads, marketplace, and screen replay

export const pipelineDeals = [
  {
    id: "deal-001",
    name: "Redwood Construction - Enterprise Upgrade",
    company: "Redwood Construction Co.",
    value: 15000,
    probability: 60,
    stage: "New",
    contact: "John Martinez",
    email: "john@redwoodconstruction.com",
    lastActivity: "2 hours ago",
    assignedTo: "Alex",
  },
  {
    id: "deal-002",
    name: "Pacific Coast - Additional License",
    company: "Pacific Coast Realty Group",
    value: 5000,
    probability: 80,
    stage: "Qualified",
    contact: "Sarah Chen",
    email: "sarah@pacificcoast.com",
    lastActivity: "1 day ago",
    assignedTo: "Riley",
  },
  {
    id: "deal-003",
    name: "Summit Healthcare - Full Suite",
    company: "Summit Healthcare Partners",
    value: 45000,
    probability: 40,
    stage: "Proposal",
    contact: "Dr. Michael Torres",
    email: "mtorres@summithealth.com",
    lastActivity: "3 days ago",
    assignedTo: "Jordan",
  },
  {
    id: "deal-004",
    name: "Ironbridge Mechanical - Renewal",
    company: "Ironbridge Mechanical LLC",
    value: 3600,
    probability: 90,
    stage: "Closed",
    contact: "Robert Kim",
    email: "robert@ironbridgemech.com",
    lastActivity: "5 hours ago",
    assignedTo: "Morgan",
  },
  {
    id: "deal-005",
    name: "Clearview Dental - Recovery",
    company: "Clearview Dental Group",
    value: 12000,
    probability: 30,
    stage: "New",
    contact: "Dr. Lisa Wang",
    email: "lisa@clearviewdental.com",
    lastActivity: "1 week ago",
    assignedTo: "Casey",
  },
  {
    id: "deal-006",
    name: "Highpoint Retail - Expansion",
    company: "Highpoint Retail Corp",
    value: 25000,
    probability: 70,
    stage: "Qualified",
    contact: "James Anderson",
    email: "james@highpoint.com",
    lastActivity: "12 hours ago",
    assignedTo: "Alex",
  },
  {
    id: "deal-007",
    name: "NorthStar Logistics - Pilot",
    company: "NorthStar Logistics",
    value: 8000,
    probability: 50,
    stage: "Proposal",
    contact: "Emily Rodriguez",
    email: "emily@northstarlog.com",
    lastActivity: "2 days ago",
    assignedTo: "Riley",
  },
];

export const pipelineStages = [
  { id: "New", name: "New", color: "bg-blue-500" },
  { id: "Qualified", name: "Qualified", color: "bg-yellow-500" },
  { id: "Proposal", name: "Proposal", color: "bg-orange-500" },
  { id: "Closed", name: "Closed", color: "bg-green-500" },
];

export const leads = [
  {
    id: "lead-001",
    name: "MetroTech Solutions",
    industry: "Technology",
    location: "San Francisco, CA",
    rating: 4.8,
    reviews: 127,
    phone: "(415) 555-0123",
    website: "metrotech.com",
    score: 95,
    employees: "50-200",
    revenue: "$10M-$50M",
    saved: false,
  },
  {
    id: "lead-002",
    name: "Golden State Manufacturing",
    industry: "Manufacturing",
    location: "Oakland, CA",
    rating: 4.5,
    reviews: 89,
    phone: "(510) 555-0456",
    website: "gsmanufacturing.com",
    score: 87,
    employees: "200-500",
    revenue: "$50M-$100M",
    saved: true,
  },
  {
    id: "lead-003",
    name: "Bay Area Financial Group",
    industry: "Finance",
    location: "San Jose, CA",
    rating: 4.9,
    reviews: 234,
    phone: "(408) 555-0789",
    website: "bayareafin.com",
    score: 92,
    employees: "100-500",
    revenue: "$25M-$100M",
    saved: false,
  },
  {
    id: "lead-004",
    name: "Silicon Valley Medical",
    industry: "Healthcare",
    location: "Palo Alto, CA",
    rating: 4.7,
    reviews: 156,
    phone: "(650) 555-0321",
    website: "svmedical.com",
    score: 89,
    employees: "500-1000",
    revenue: "$100M+",
    saved: false,
  },
  {
    id: "lead-005",
    name: "NorCal Construction Partners",
    industry: "Construction",
    location: "Sacramento, CA",
    rating: 4.3,
    reviews: 67,
    phone: "(916) 555-0654",
    website: "norcalconstruction.com",
    score: 78,
    employees: "50-200",
    revenue: "$10M-$50M",
    saved: false,
  },
  {
    id: "lead-006",
    name: "EcoEnergy Solutions",
    industry: "Energy",
    location: "Berkeley, CA",
    rating: 4.6,
    reviews: 112,
    phone: "(510) 555-0987",
    website: "ecoenergy.com",
    score: 85,
    employees: "20-100",
    revenue: "$5M-$25M",
    saved: true,
  },
];

export const industries = [
  "All Industries",
  "Technology",
  "Manufacturing",
  "Finance",
  "Healthcare",
  "Construction",
  "Energy",
  "Retail",
  "Education",
  "Real Estate",
];

export const aiEmployees = [
  {
    id: "ai-001",
    name: "SalesMate",
    role: "Sales Specialist",
    category: "Sales",
    description: "Expert in lead qualification, follow-ups, and pipeline management",
    skills: ["CRM Management", "Email Automation", "Call Scheduling", "Lead Scoring"],
    pricePerMonth: 997,
    rating: 4.9,
    tasksCompleted: 15420,
    avatar: "S",
    color: "bg-blue-500",
    available: true,
  },
  {
    id: "ai-002",
    name: "SupportPro",
    role: "Customer Support",
    category: "Support",
    description: "24/7 customer support with instant responses and ticket resolution",
    skills: ["Ticket Management", "Live Chat", "Knowledge Base", "Escalation"],
    pricePerMonth: 997,
    rating: 4.8,
    tasksCompleted: 28340,
    avatar: "C",
    color: "bg-green-500",
    available: true,
  },
  {
    id: "ai-003",
    name: "CodeAssist",
    role: "Development Helper",
    category: "Development",
    description: "Code review, bug fixes, documentation, and technical support",
    skills: ["Code Review", "Bug Triage", "Documentation", "API Testing"],
    pricePerMonth: 1497,
    rating: 4.7,
    tasksCompleted: 8930,
    avatar: "D",
    color: "bg-purple-500",
    available: true,
  },
  {
    id: "ai-004",
    name: "DataFlow",
    role: "Data Entry Specialist",
    category: "Operations",
    description: "Automated data entry, validation, and database management",
    skills: ["Data Entry", "Validation", "Reporting", "Database Sync"],
    pricePerMonth: 997,
    rating: 4.9,
    tasksCompleted: 45600,
    avatar: "O",
    color: "bg-orange-500",
    available: true,
  },
  {
    id: "ai-005",
    name: "BookKeeper",
    role: "Accounting Assistant",
    category: "Finance",
    description: "Invoice processing, expense tracking, and financial reporting",
    skills: ["Invoicing", "Expense Tracking", "Reconciliation", "Reports"],
    pricePerMonth: 997,
    rating: 4.6,
    tasksCompleted: 12350,
    avatar: "F",
    color: "bg-teal-500",
    available: true,
  },
  {
    id: "ai-006",
    name: "HRPartner",
    role: "HR Coordinator",
    category: "Human Resources",
    description: "Onboarding, scheduling interviews, and employee record management",
    skills: ["Onboarding", "Interview Scheduling", "Records", "Compliance"],
    pricePerMonth: 997,
    rating: 4.8,
    tasksCompleted: 9870,
    avatar: "H",
    color: "bg-pink-500",
    available: true,
  },
  {
    id: "ai-007",
    name: "MarketGuru",
    role: "Marketing Assistant",
    category: "Marketing",
    description: "Social media management, content scheduling, and campaign tracking",
    skills: ["Social Media", "Content Calendar", "Analytics", "Email Campaigns"],
    pricePerMonth: 997,
    rating: 4.7,
    tasksCompleted: 15670,
    avatar: "M",
    color: "bg-red-500",
    available: true,
  },
  {
    id: "ai-008",
    name: "ExecAdmin",
    role: "Executive Assistant",
    category: "Administration",
    description: "Calendar management, meeting notes, and travel coordination",
    skills: ["Calendar", "Meeting Notes", "Travel", "Correspondence"],
    pricePerMonth: 997,
    rating: 4.9,
    tasksCompleted: 21340,
    avatar: "E",
    color: "bg-indigo-500",
    available: true,
  },
];

export const screenReplays = [
  {
    id: "replay-001",
    name: "Sales Follow-Up Session",
    employeeId: "emp-001",
    employeeName: "Alex",
    duration: "12:34",
    timestamp: "2024-06-20T09:00:00Z",
    date: "Jun 20, 2024",
    actions: 45,
    status: "completed",
    thumbnail: "S",
  },
  {
    id: "replay-002",
    name: "Invoice Processing",
    employeeId: "emp-002",
    employeeName: "Jordan",
    duration: "08:12",
    timestamp: "2024-06-20T10:30:00Z",
    date: "Jun 20, 2024",
    actions: 32,
    status: "completed",
    thumbnail: "J",
  },
  {
    id: "replay-003",
    name: "CRM Data Entry",
    employeeId: "emp-003",
    employeeName: "Morgan",
    duration: "15:45",
    timestamp: "2024-06-19T14:00:00Z",
    date: "Jun 19, 2024",
    actions: 67,
    status: "completed",
    thumbnail: "M",
  },
  {
    id: "replay-004",
    name: "Email Campaign Setup",
    employeeId: "emp-004",
    employeeName: "Riley",
    duration: "22:18",
    timestamp: "2024-06-19T11:00:00Z",
    date: "Jun 19, 2024",
    actions: 89,
    status: "completed",
    thumbnail: "R",
  },
  {
    id: "replay-005",
    name: "Customer Support Ticket",
    employeeId: "emp-001",
    employeeName: "Alex",
    duration: "05:33",
    timestamp: "2024-06-18T16:45:00Z",
    date: "Jun 18, 2024",
    actions: 18,
    status: "completed",
    thumbnail: "S",
  },
  {
    id: "replay-006",
    name: "Lead Qualification",
    employeeId: "emp-004",
    employeeName: "Riley",
    duration: "18:07",
    timestamp: "2024-06-18T13:20:00Z",
    date: "Jun 18, 2024",
    actions: 54,
    status: "completed",
    thumbnail: "R",
  },
];
