// Seed data for Mouse Platform demo

export const platform = {
  name: "Mouse",
  tagline: "AI Workforce Operating System",
};

export const resellers = [
  {
    id: "res-001",
    name: "Automio",
    status: "active",
    mrr: 24750,
    customers: 8,
    stripeStatus: "connected",
    joinedAt: "2024-01-15",
  },
  {
    id: "res-002",
    name: "WorkForce AI Solutions",
    status: "active",
    mrr: 11940,
    customers: 4,
    stripeStatus: "connected",
    joinedAt: "2024-03-02",
  },
  {
    id: "res-003",
    name: "Nexus Digital Partners",
    status: "pending",
    mrr: 0,
    customers: 0,
    stripeStatus: "pending",
    joinedAt: "2024-06-18",
  },
  {
    id: "res-004",
    name: "Apex Automation Group",
    status: "active",
    mrr: 8970,
    customers: 3,
    stripeStatus: "connected",
    joinedAt: "2024-02-20",
  },
];

export const platformStats = {
  totalResellers: 4,
  totalRevenue: 45660,
  totalUsage: 12840,
  systemHealth: "Operational",
  uptime: "99.97%",
  activeEmployees: 47,
};

export const customers = [
  {
    id: "cust-001",
    company: "Redwood Construction Co.",
    plan: "Growth",
    mrr: 2997,
    employees: 3,
    health: "green",
    resellerId: "res-001",
  },
  {
    id: "cust-002",
    company: "Pacific Coast Realty Group",
    plan: "Growth",
    mrr: 2997,
    employees: 3,
    health: "green",
    resellerId: "res-001",
  },
  {
    id: "cust-003",
    company: "Summit Healthcare Partners",
    plan: "Enterprise",
    mrr: 7500,
    employees: 10,
    health: "green",
    resellerId: "res-001",
  },
  {
    id: "cust-004",
    company: "Lakefront Professional Services",
    plan: "Starter",
    mrr: 997,
    employees: 1,
    health: "yellow",
    resellerId: "res-001",
  },
  {
    id: "cust-005",
    company: "Ironbridge Mechanical LLC",
    plan: "Growth",
    mrr: 2997,
    employees: 3,
    health: "green",
    resellerId: "res-001",
  },
  {
    id: "cust-006",
    company: "Clearview Dental Group",
    plan: "Starter",
    mrr: 997,
    employees: 1,
    health: "red",
    resellerId: "res-001",
  },
  {
    id: "cust-007",
    company: "Highpoint Retail Corp",
    plan: "Growth",
    mrr: 2997,
    employees: 3,
    health: "green",
    resellerId: "res-001",
  },
  {
    id: "cust-008",
    company: "NorthStar Logistics",
    plan: "Starter",
    mrr: 997,
    employees: 1,
    health: "yellow",
    resellerId: "res-001",
  },
];

export const resellerStats = {
  customerCount: 8,
  mrr: 24739,
  activeEmployees: 22,
  usageCost: 3840,
  grossProcessed: 24739,
  platformFee: 2968,
  usageBilled: 3840,
  estimatedMargin: 17931,
};

export const employees = [
  {
    id: "emp-001",
    name: "Alex",
    role: "Sales Follow-Up Specialist",
    status: "active",
    fteEquivalent: 0.8,
    costPerMonth: 997,
    customerId: "cust-001",
    customerName: "Redwood Construction Co.",
    tasksToday: 24,
    hoursSaved: 38,
    valueGenerated: 14200,
  },
  {
    id: "emp-002",
    name: "Jordan",
    role: "Accounts Receivable Agent",
    status: "working",
    fteEquivalent: 0.7,
    costPerMonth: 997,
    customerId: "cust-001",
    customerName: "Redwood Construction Co.",
    tasksToday: 18,
    hoursSaved: 29,
    valueGenerated: 8900,
  },
  {
    id: "emp-003",
    name: "Morgan",
    role: "Data Entry Specialist",
    status: "idle",
    fteEquivalent: 0.6,
    costPerMonth: 997,
    customerId: "cust-001",
    customerName: "Redwood Construction Co.",
    tasksToday: 12,
    hoursSaved: 21,
    valueGenerated: 5400,
  },
  {
    id: "emp-004",
    name: "Riley",
    role: "Executive Assistant",
    status: "active",
    fteEquivalent: 0.9,
    costPerMonth: 997,
    customerId: "cust-002",
    customerName: "Pacific Coast Realty Group",
    tasksToday: 31,
    hoursSaved: 44,
    valueGenerated: 18700,
  },
  {
    id: "emp-005",
    name: "Casey",
    role: "Sales Follow-Up Specialist",
    status: "error",
    fteEquivalent: 0.0,
    costPerMonth: 997,
    customerId: "cust-006",
    customerName: "Clearview Dental Group",
    tasksToday: 0,
    hoursSaved: 0,
    valueGenerated: 0,
  },
];

export const activityFeed = [
  {
    id: "act-001",
    employeeId: "emp-001",
    action: "Logged into Salesforce CRM",
    timestamp: "2024-06-20T09:02:14Z",
    status: "success",
  },
  {
    id: "act-002",
    employeeId: "emp-001",
    action: "Identified 7 leads requiring follow-up",
    timestamp: "2024-06-20T09:03:41Z",
    status: "success",
  },
  {
    id: "act-003",
    employeeId: "emp-001",
    action: 'Drafted personalized email for "Martinez Construction"',
    timestamp: "2024-06-20T09:05:22Z",
    status: "success",
  },
  {
    id: "act-004",
    employeeId: "emp-001",
    action: "Sent follow-up SMS to 3 contacts",
    timestamp: "2024-06-20T09:07:55Z",
    status: "success",
  },
  {
    id: "act-005",
    employeeId: "emp-001",
    action: "Updated pipeline stage for 5 opportunities",
    timestamp: "2024-06-20T09:11:03Z",
    status: "success",
  },
  {
    id: "act-006",
    employeeId: "emp-001",
    action: "Logged into HubSpot — syncing contact records",
    timestamp: "2024-06-20T09:15:30Z",
    status: "success",
  },
  {
    id: "act-007",
    employeeId: "emp-001",
    action: 'Attempted to access "Blue Ridge Contractors" account — access denied',
    timestamp: "2024-06-20T09:18:44Z",
    status: "error",
  },
  {
    id: "act-008",
    employeeId: "emp-001",
    action: "Retried with alternate credentials — success",
    timestamp: "2024-06-20T09:19:12Z",
    status: "success",
  },
];

export const taskQueue = [
  {
    id: "task-001",
    employeeId: "emp-001",
    title: "Follow up with Riverside Roofing — 14 days no response",
    status: "completed",
    priority: "high",
    createdAt: "2024-06-20T08:00:00Z",
    completedAt: "2024-06-20T09:04:00Z",
  },
  {
    id: "task-002",
    employeeId: "emp-001",
    title: "Send Q3 proposal to Summit Materials — 3 attachments",
    status: "active",
    priority: "high",
    createdAt: "2024-06-20T09:00:00Z",
    completedAt: null,
  },
  {
    id: "task-003",
    employeeId: "emp-001",
    title: "Update pipeline: move 8 deals past 'Proposal Sent'",
    status: "pending",
    priority: "medium",
    createdAt: "2024-06-20T09:00:00Z",
    completedAt: null,
  },
  {
    id: "task-004",
    employeeId: "emp-001",
    title: "Draft re-engagement email for 30-day cold leads (12 contacts)",
    status: "pending",
    priority: "medium",
    createdAt: "2024-06-20T09:00:00Z",
    completedAt: null,
  },
  {
    id: "task-005",
    employeeId: "emp-001",
    title: "Cross-reference new leads from trade show list",
    status: "pending",
    priority: "low",
    createdAt: "2024-06-20T09:00:00Z",
    completedAt: null,
  },
];

export const invoices = [
  {
    id: "inv-001",
    date: "2024-06-01",
    amount: 2997,
    status: "paid",
    plan: "Growth Plan — June 2024",
  },
  {
    id: "inv-002",
    date: "2024-05-01",
    amount: 2997,
    status: "paid",
    plan: "Growth Plan — May 2024",
  },
  {
    id: "inv-003",
    date: "2024-04-01",
    amount: 2997,
    status: "paid",
    plan: "Growth Plan — April 2024",
  },
  {
    id: "inv-004",
    date: "2024-03-01",
    amount: 997,
    status: "paid",
    plan: "Starter Plan — March 2024",
  },
];

export const portalStats = {
  employeesActive: 2,
  tasksToday: 54,
  hoursSaved: 88,
  valueGenerated: 28500,
  roiPercent: 847,
};
