/**
 * GET /api/export/documents?customer_id=xxx
 * Exports King Mouse documents as JSON (ZIP requires a library — placeholder for now).
 */

import { NextRequest, NextResponse } from 'next/server';
import { supabaseQuery } from '@/lib/supabase-server';

export async function GET(request: NextRequest) {
  const customerId = request.nextUrl.searchParams.get('customer_id');

  if (!customerId) {
    return NextResponse.json({ error: 'customer_id required' }, { status: 400 });
  }

  try {
    // Get task screenshots / files generated by King Mouse
    const screenshots = await supabaseQuery(
      'task_screenshots',
      'GET',
      undefined,
      `customer_id=eq.${customerId}&select=id,task_id,screenshot_url,captured_at&order=captured_at.desc&limit=500`
    );

    // Get workspace files if any
    const apps = await supabaseQuery(
      'workspace_apps',
      'GET',
      undefined,
      `customer_id=eq.${customerId}&select=app_slug,app_name,app_url,config&order=app_slug.asc`
    );

    const data = {
      exported_at: new Date().toISOString(),
      customer_id: customerId,
      screenshots: screenshots || [],
      workspace_apps: apps || [],
    };

    return new NextResponse(JSON.stringify(data, null, 2), {
      headers: {
        'Content-Type': 'application/json',
        'Content-Disposition': 'attachment; filename="documents.json"',
      },
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Internal server error';
    console.error('[EXPORT_DOCUMENTS]', message);
    return NextResponse.json({ error: 'Failed to export documents' }, { status: 500 });
  }
}
