import type { ProTemplate } from '../schema';

export const eventsEntertainmentTemplates: ProTemplate[] = [
  {
    id: 'dj-service',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'dj-service',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Setting the perfect vibe for every event',
      description: 'A professional DJ service bringing the right music, energy, and equipment to make every event unforgettable — from weddings to corporate parties.',
      primaryColor: '#6A1B9A',
      secondaryColor: '#F3E5F5',
      tone: 'energetic, professional, fun',
      personality: 'Like the life of the party who also happens to be incredibly organized and reliable — all vibe, no stress.',
    },
    demoExperience: {
      headline: 'Your DJ Business, Perfectly Mixed',
      subheadline: 'Mouse handles booking inquiries, event coordination, and follow-ups — so you can focus on what you do best: reading the room.',
      heroImage: 'dj-setup-colorful-lights-event',
      socialProof: 'DJs using Mouse book 40% more events through automated inquiry responses.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your DJ business advisor',
      greeting: "What's up! Let's turn up your booking game. I'll handle the inquiries, contracts, and follow-ups so you can focus on the music and the crowd.",
      sampleAdvice: [
        'Wedding season starts in 8 weeks and you only have 60% of Saturdays booked. Time to push your wedding package on social media.',
        'You have 3 event inquiries that are 5+ days old with no response. Speed matters — want me to send a follow-up with your availability?',
        'Your average wedding package is $1,500 but similar DJs in your area charge $2,000. Consider updating your pricing.',
      ],
      knowledgeDomains: ['event entertainment', 'music programming', 'event planning', 'audio equipment', 'booking management', 'client relations'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, the virtual assistant. I can help you with availability, packages, pricing, or booking info. What's your event?",
      personality: "Upbeat and professional. Gets excited about events. Asks the right questions to understand the vibe the client wants. Never dismissive about budget — works to find solutions. Makes clients feel confident they've found the right DJ.",
      faqs: [
        { question: 'Are you available on [date]?', answer: "Let me check! What's the date and type of event? I'll get back to you with {{dj_name}}'s availability right away." },
        { question: 'How much do you charge?', answer: "Our packages start at {{starting_price}}. Final pricing depends on the event type, duration, and any extras like lighting or photo booths. Want me to set up a free consultation to get you an exact quote?" },
        { question: 'What type of events do you do?', answer: "We do it all — {{event_types}}. Every event gets a customized music plan." },
        { question: 'Do you take requests?', answer: "Absolutely! We send a request form before the event so we get your must-plays and do-not-plays. And we always take live requests too." },
        { question: 'Do you bring your own equipment?', answer: "Yes! We bring a professional sound system, microphones, and {{equipment_extras}}. We show up early to set up and test everything." },
        { question: 'Do you MC too?', answer: "{{mc_policy}}" },
      ],
      transferTriggers: [
        'Ready to book or requesting contract',
        'Wedding with complex timeline',
        'Corporate event over 200 guests',
        'Multi-event package inquiry',
      ],
      escalationRules: {
        urgentKeywords: ['this weekend', 'tomorrow', 'last minute', 'emergency', 'cancel'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're probably at an event right now. Leave a message with your event date and type, and we'll get back to you within 24 hours. You can also text us!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your DJ Business',
          description: "Let's set up your profile.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., DJ Smooth Beats' },
            { id: 'dj_name', label: 'DJ Name', type: 'text', required: true, placeholder: 'e.g., DJ Mike' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Greater Orlando area, up to 50 miles' },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What do you offer?',
          fields: [
            { id: 'event_types', label: 'Event Types', type: 'multiselect', required: true, options: ['Weddings', 'Corporate Events', 'Birthday Parties', 'School Dances', 'Club Events', 'Private Parties', 'Holiday Parties', 'Festivals'] },
            { id: 'starting_price', label: 'Starting Package Price', type: 'currency', required: true, placeholder: '500' },
            { id: 'mc_policy', label: 'MC Services', type: 'text', required: false, placeholder: 'e.g., Yes! Full MC services included — introductions, timeline management, the works' },
          ],
        },
        {
          id: 'equipment',
          title: 'Equipment & Extras',
          description: 'What do you bring to the party?',
          fields: [
            { id: 'equipment_extras', label: 'Extra Equipment', type: 'multiselect', required: false, options: ['Dance Floor Lighting', 'LED Uplighting', 'Photo Booth', 'Fog Machine', 'Projector/Screen', 'Wireless Microphones'] },
            { id: 'music_genres', label: 'Music Specialties', type: 'text', required: false, placeholder: 'e.g., Top 40, R&B, Latin, Country, EDM, Classic Rock' },
          ],
        },
        {
          id: 'booking',
          title: 'Booking Process',
          description: 'How do you handle bookings?',
          fields: [
            { id: 'deposit_policy', label: 'Deposit Required', type: 'text', required: true, placeholder: 'e.g., $200 non-refundable deposit to hold your date' },
            { id: 'website', label: 'Website', type: 'url', required: false },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'upcoming-events', type: 'list', title: 'Upcoming Events', dataSource: 'calendar_upcoming', refreshInterval: 3600 },
      { id: 'pending-inquiries', type: 'list', title: 'Pending Inquiries', dataSource: 'inquiries_pending', refreshInterval: 600 },
      { id: 'monthly-bookings', type: 'metric', title: 'Bookings This Month', dataSource: 'bookings_monthly', refreshInterval: 3600 },
      { id: 'revenue', type: 'chart', title: 'Monthly Revenue', dataSource: 'revenue_monthly', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'inquiry-followup', title: 'Follow Up on Inquiries', description: 'Send follow-ups to event inquiries that haven\'t responded in 48+ hours', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'event-prep', title: 'Send Event Prep Form', description: 'Send music request forms and timeline sheets to clients 2 weeks before their event', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'review-request', title: 'Request Reviews', description: 'Send review requests to clients 3 days after their event', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 8000, currentValue: 0 },
      { id: 'bookings', label: 'Events Booked/Month', format: 'number', target: 8, currentValue: 0 },
      { id: 'avg-package', label: 'Average Package Price', format: 'currency', target: 1200, currentValue: 0 },
      { id: 'inquiry-conversion', label: 'Inquiry to Booking Rate', format: 'percentage', target: 35, currentValue: 0 },
    ],
    integrations: [
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'the-knot', name: 'The Knot', category: 'marketplace', priority: 'recommended', setupTime: 15 },
      { id: 'weddingwire', name: 'WeddingWire', category: 'marketplace', priority: 'recommended', setupTime: 15 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'inquiry-response', name: 'Inquiry Response', subject: "Let's make your {{event_type}} unforgettable! - {{business_name}}", body: "Hi {{customer_name}},\n\nThanks for reaching out about your {{event_type}} on {{event_date}}! I'd love to be part of your celebration.\n\nI have that date available! Here's what I'd suggest for your event:\n\n{{package_recommendation}}\n\nWant to hop on a quick call to discuss the details? I'd love to hear your vision for the music and vibe.\n\n{{dj_name}}\n{{business_name}}\n{{phone}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'inquiry-followup', name: 'Inquiry Follow-Up', body: "Hey {{customer_name}}! Just following up on your {{event_type}} inquiry. {{dj_name}} from {{business_name}} would love to chat about your event on {{event_date}}. Still interested? 🎵", trigger: 'automated' },
      { id: 'post-event', name: 'Post-Event Thank You', body: 'Thanks for having {{business_name}} at your {{event_type}}! Hope everyone had a blast. If you loved it, a review would mean the world: {{review_link}} 🎶', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'dj', 'entertainment', 'music'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'event-planner',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'event-planner',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Stress-free events, unforgettable memories',
      description: 'A professional event planning service that handles every detail — from concept to cleanup — so clients can actually enjoy their own event.',
      primaryColor: '#C2185B',
      secondaryColor: '#FCE4EC',
      tone: 'polished, organized, warm',
      personality: 'Like having a brilliant, detail-obsessed best friend who happens to know every vendor in town and never lets anything fall through the cracks.',
    },
    demoExperience: {
      headline: 'Your Event Planning Business, Effortlessly Organized',
      subheadline: 'Mouse handles inquiries, vendor coordination, and client communication — so you can focus on creating magic.',
      heroImage: 'elegant-event-setup-ballroom',
      socialProof: 'Event planners using Mouse respond to inquiries 5x faster and book 35% more events.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your event planning business advisor',
      greeting: "Hello, party planner extraordinaire! Let's make your business run as smoothly as your events. I'll handle the admin so you can focus on the creative magic.",
      sampleAdvice: [
        'You have 2 event proposals outstanding for over a week. Clients who wait more than 5 days are 50% less likely to book. Want me to send a follow-up?',
        'Your venue partner at {{venue_name}} just posted availability for 3 Saturday dates in October. Those will go fast — share with your interested clients.',
        'Holiday party season is 10 weeks out. Last year you booked 8 corporate events. Time to start your outreach to last year\'s corporate clients.',
      ],
      knowledgeDomains: ['event planning', 'vendor management', 'budgeting', 'timeline coordination', 'corporate events', 'social events'],
    },
    aiReceptionist: {
      greeting: "Hello, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I'd love to help you with event planning inquiries, availability, or information about our services. What kind of event are you planning?",
      personality: "Polished and warm. Makes clients feel like their event is the most important one. Asks thoughtful questions about vision, budget, and timeline. Never judgmental about budget size — creates magic at every level.",
      faqs: [
        { question: 'What types of events do you plan?', answer: "We plan {{event_types}}. No event is too big or too small — we bring the same passion to everything." },
        { question: 'How much does event planning cost?', answer: "Our planning packages start at {{starting_price}}. We offer {{package_types}}. Every event is different, so we'd love to learn about yours and give you a custom quote." },
        { question: 'How far in advance should I book?', answer: "For large events like weddings and galas, we recommend {{lead_time_large}}. For smaller events, {{lead_time_small}} usually works. But don't worry — we've pulled off beautiful events on tight timelines too!" },
        { question: 'Do you handle vendor coordination?', answer: "Absolutely — that's one of our superpowers! We have trusted relationships with the best caterers, florists, photographers, DJs, and venues in the area." },
        { question: 'Do you do day-of coordination?', answer: "{{day_of_policy}}" },
      ],
      transferTriggers: [
        'Client ready to book or requesting a proposal',
        'Corporate event with 100+ guests',
        'Budget discussion over $10,000',
        'Vendor conflict or issue during active event planning',
      ],
      escalationRules: {
        urgentKeywords: ['cancel', 'emergency', 'vendor cancelled', 'this week', 'tomorrow', 'urgent'],
        afterHoursMessage: "Thank you for calling {{business_name}}! We're not available right now, but your event matters to us. Leave a message with your name, event date, and what you're planning, and we'll get back to you within one business day.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your event planning business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Elegant Affairs Events' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'email', label: 'Business Email', type: 'email', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Greater Dallas-Fort Worth area' },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What do you offer?',
          fields: [
            { id: 'event_types', label: 'Event Types', type: 'multiselect', required: true, options: ['Weddings', 'Corporate Events', 'Galas', 'Birthday Parties', 'Baby Showers', 'Anniversaries', 'Holiday Parties', 'Fundraisers', 'Conferences'] },
            { id: 'package_types', label: 'Package Types', type: 'text', required: true, placeholder: 'e.g., full planning, partial planning, and day-of coordination' },
            { id: 'starting_price', label: 'Starting Price', type: 'currency', required: true, placeholder: '1500' },
          ],
        },
        {
          id: 'details',
          title: 'Planning Details',
          description: 'Help us understand your process.',
          fields: [
            { id: 'lead_time_large', label: 'Lead Time for Large Events', type: 'text', required: true, placeholder: 'e.g., 6-12 months' },
            { id: 'lead_time_small', label: 'Lead Time for Small Events', type: 'text', required: true, placeholder: 'e.g., 4-8 weeks' },
            { id: 'day_of_policy', label: 'Day-Of Coordination', type: 'text', required: false, placeholder: 'e.g., Yes! Our day-of package starts at $800 and covers full event management on the big day' },
          ],
        },
        {
          id: 'online',
          title: 'Online Presence',
          description: 'How do clients find you?',
          fields: [
            { id: 'website', label: 'Website', type: 'url', required: false },
            { id: 'instagram', label: 'Instagram', type: 'text', required: false, placeholder: '@yourbusiness' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'active-events', type: 'list', title: 'Active Events', dataSource: 'events_active', refreshInterval: 3600 },
      { id: 'pending-proposals', type: 'list', title: 'Pending Proposals', dataSource: 'proposals_pending', refreshInterval: 1800 },
      { id: 'upcoming-deadlines', type: 'alert', title: 'Vendor Deadlines', dataSource: 'deadlines_upcoming', refreshInterval: 3600 },
      { id: 'monthly-revenue', type: 'metric', title: 'Revenue This Month', dataSource: 'revenue_monthly', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'proposal-followup', title: 'Follow Up on Proposals', description: 'Send follow-ups to prospects who received proposals but haven\'t responded', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'vendor-confirm', title: 'Confirm Vendors', description: 'Send confirmation requests to all vendors for upcoming events', difficulty: 'needs-approval', estimatedMinutes: 10 },
      { id: 'post-event-review', title: 'Post-Event Review Request', description: 'Send thank-you and review request to clients after their event', difficulty: 'automatic', estimatedMinutes: 2 },
    ],
    kpis: [
      { id: 'active-events', label: 'Active Events', format: 'number', target: 8, currentValue: 0 },
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 12000, currentValue: 0 },
      { id: 'proposal-conversion', label: 'Proposal to Booking', format: 'percentage', target: 40, currentValue: 0 },
      { id: 'avg-event-value', label: 'Average Event Value', format: 'currency', target: 3500, currentValue: 0 },
    ],
    integrations: [
      { id: 'honeybook', name: 'HoneyBook', category: 'crm', priority: 'essential', setupTime: 15 },
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'recommended', setupTime: 10 },
      { id: 'the-knot', name: 'The Knot', category: 'marketplace', priority: 'recommended', setupTime: 15 },
    ],
    emailTemplates: [
      { id: 'consultation-booked', name: 'Consultation Confirmation', subject: "Can't wait to plan your {{event_type}}! - {{business_name}}", body: "Hi {{customer_name}},\n\nI'm so excited to learn about your {{event_type}}! Your consultation is confirmed for {{consultation_date}} at {{consultation_time}}.\n\nBefore we meet, it would be helpful if you could think about:\n- Your vision for the event\n- Approximate guest count\n- Budget range you're comfortable with\n- Any must-have elements\n\nNo pressure to have it all figured out — that's what I'm here for!\n\nLooking forward to it,\n{{planner_name}}\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'inquiry-response', name: 'Quick Inquiry Response', body: "Hi {{customer_name}}! Thanks for reaching out to {{business_name}} about your {{event_type}}. We'd love to help! When's a good time for a quick call? 🎉", trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'event-planner', 'planning', 'coordination'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'wedding-photographer',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'wedding-photographer',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Your love story, beautifully told',
      description: 'A professional wedding photographer who captures the real moments, genuine emotions, and beautiful details that make every wedding unique.',
      primaryColor: '#5C6BC0',
      secondaryColor: '#E8EAF6',
      tone: 'artistic, warm, genuine',
      personality: 'Like a trusted friend with an incredible eye — someone who makes you feel comfortable being yourself while capturing moments you\'ll treasure forever.',
    },
    demoExperience: {
      headline: 'Your Photography Business, Picture Perfect',
      subheadline: 'Mouse handles inquiries, booking coordination, and gallery delivery — so you can focus on capturing love stories.',
      heroImage: 'wedding-photographer-couple-golden-hour',
      socialProof: 'Wedding photographers using Mouse book 45% more weddings through faster inquiry responses.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your photography business advisor',
      greeting: "Hey there, artist! Let's make sure your talent gets the business it deserves. I'll handle the inquiries and admin so you can focus on what you do best — making people look amazing.",
      sampleAdvice: [
        'You have 4 wedding inquiries for next October that are 3+ days old. In this market, responding within 24 hours doubles your booking rate.',
        'Your 2026 wedding season is only 40% booked. Want me to run a limited-time booking incentive campaign?',
        'You have 6 galleries that are edited but not delivered. Clients start worrying after 6 weeks — let\'s get those out.',
      ],
      knowledgeDomains: ['wedding photography', 'portrait photography', 'photo editing workflow', 'client management', 'album design', 'second shooting'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. Congratulations if you're engaged! I can help with availability, packages, or any questions about our photography services. What's your wedding date?",
      personality: "Warm and genuinely happy for couples. Makes the photography booking process feel exciting, not stressful. Asks about the couple's vision and vibe, not just logistics. Never makes couples feel like a transaction.",
      faqs: [
        { question: 'Are you available on [date]?', answer: "Let me check! What's your wedding date and venue? I'll check {{photographer_name}}'s availability and get back to you right away." },
        { question: 'How much do you charge?', answer: "Our wedding packages start at {{starting_price}} and include {{base_package_includes}}. We have several packages to fit different needs and budgets. Want me to set up a consultation?" },
        { question: 'How many photos do we get?', answer: "On average, you'll receive {{photo_count}} professionally edited photos from a full wedding day. Every image is hand-edited." },
        { question: 'When do we get our photos?', answer: "You'll receive your full gallery within {{delivery_timeline}} of your wedding. We also share a sneak peek of {{sneak_peek_count}} images within 48 hours!" },
        { question: 'Do you do engagement sessions?', answer: "{{engagement_policy}}" },
        { question: 'Do you have a second photographer?', answer: "{{second_shooter_policy}}" },
      ],
      transferTriggers: [
        'Couple is ready to book',
        'Custom package request',
        'Destination wedding inquiry',
        'Album or print order questions',
      ],
      escalationRules: {
        urgentKeywords: ['cancel', 'emergency', 'reschedule', 'refund', 'this weekend'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're probably out capturing something beautiful. Leave a message with your name, wedding date, and venue, and we'll get back to you within 24 hours. You can also check availability on our website: {{website}}",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your photography business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Sarah Lane Photography' },
            { id: 'photographer_name', label: 'Your Name', type: 'text', required: true },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Austin, TX and surrounding areas. Destination weddings welcome!' },
          ],
        },
        {
          id: 'packages',
          title: 'Your Packages',
          description: 'Tell us about your offerings.',
          fields: [
            { id: 'starting_price', label: 'Starting Package Price', type: 'currency', required: true, placeholder: '2500' },
            { id: 'base_package_includes', label: 'Base Package Includes', type: 'text', required: true, placeholder: 'e.g., 8 hours of coverage, online gallery, print rights' },
            { id: 'photo_count', label: 'Typical Photo Count', type: 'text', required: true, placeholder: 'e.g., 500-700' },
            { id: 'delivery_timeline', label: 'Gallery Delivery Timeline', type: 'text', required: true, placeholder: 'e.g., 6-8 weeks' },
          ],
        },
        {
          id: 'extras',
          title: 'Extra Services',
          description: 'What else do you offer?',
          fields: [
            { id: 'engagement_policy', label: 'Engagement Sessions', type: 'text', required: false, placeholder: 'e.g., Included with all wedding packages! Great way for us to get comfortable together before the big day.' },
            { id: 'second_shooter_policy', label: 'Second Photographer', type: 'text', required: false, placeholder: 'e.g., Available as an add-on for $500. Recommended for weddings over 150 guests.' },
            { id: 'sneak_peek_count', label: 'Sneak Peek Count', type: 'text', required: false, placeholder: 'e.g., 15-20', defaultValue: '15-20' },
          ],
        },
        {
          id: 'style',
          title: 'Your Style',
          description: 'Help couples understand your approach.',
          fields: [
            { id: 'photography_style', label: 'Photography Style', type: 'multiselect', required: true, options: ['Documentary/Photojournalistic', 'Light & Airy', 'Dark & Moody', 'Classic/Timeless', 'Bold & Colorful', 'Film-Inspired', 'Editorial'] },
            { id: 'website', label: 'Portfolio Website', type: 'url', required: false },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'upcoming-weddings', type: 'list', title: 'Upcoming Weddings', dataSource: 'calendar_upcoming', refreshInterval: 3600 },
      { id: 'pending-inquiries', type: 'list', title: 'Pending Inquiries', dataSource: 'inquiries_pending', refreshInterval: 600 },
      { id: 'galleries-due', type: 'alert', title: 'Galleries Due', dataSource: 'galleries_pending', refreshInterval: 86400 },
      { id: 'booking-rate', type: 'metric', title: 'Booking Rate', dataSource: 'booking_rate', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'inquiry-response', title: 'Respond to Inquiries', description: 'Send personalized responses to new wedding inquiries', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'sneak-peek', title: 'Deliver Sneak Peeks', description: 'Send sneak peek images to couples within 48 hours of their wedding', difficulty: 'needs-approval', estimatedMinutes: 3 },
      { id: 'review-request', title: 'Request Reviews', description: 'Ask past couples for Google/Knot reviews after gallery delivery', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'annual-bookings', label: 'Weddings Booked (Year)', format: 'number', target: 30, currentValue: 0 },
      { id: 'avg-package', label: 'Average Package Value', format: 'currency', target: 3500, currentValue: 0 },
      { id: 'inquiry-response-time', label: 'Avg Response Time (hrs)', format: 'number', target: 12, currentValue: 0 },
      { id: 'booking-rate', label: 'Inquiry to Booking', format: 'percentage', target: 35, currentValue: 0 },
    ],
    integrations: [
      { id: 'honeybook', name: 'HoneyBook', category: 'crm', priority: 'essential', setupTime: 15 },
      { id: 'pic-time', name: 'Pic-Time', category: 'gallery', priority: 'essential', setupTime: 15 },
      { id: 'the-knot', name: 'The Knot', category: 'marketplace', priority: 'recommended', setupTime: 15 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'gallery-delivery', name: 'Gallery Delivery', subject: "Your wedding photos are ready! 📸 - {{business_name}}", body: "{{customer_name_1}} & {{customer_name_2}},\n\nYour wedding gallery is ready! I am SO excited for you to see these.\n\nView your gallery here: {{gallery_link}}\n\nYour gallery is available for download and sharing. Take your time going through them — there are a lot of beautiful moments in there.\n\nThank you for trusting me with your day. It was truly an honor.\n\nWith love,\n{{photographer_name}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'sneak-peek', name: 'Sneak Peek Ready', body: "Hey {{customer_name}}! Your sneak peek photos are ready! 📸✨ Check your email — I can't wait for you to see them! - {{photographer_name}}", trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'photography', 'wedding', 'portrait'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'wedding-venue',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'wedding-venue',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Where your forever begins',
      description: 'A wedding venue offering beautiful spaces, exceptional service, and the flexibility to make every couple\'s dream day a reality.',
      primaryColor: '#B8860B',
      secondaryColor: '#FFF8E7',
      tone: 'elegant, welcoming, romantic',
      personality: 'Like a gracious host who takes genuine pride in making every celebration feel personal and magical — never cookie-cutter.',
    },
    demoExperience: {
      headline: 'Your Venue, Booked and Beautiful',
      subheadline: 'Mouse handles tour scheduling, availability inquiries, and vendor coordination — so you can focus on creating unforgettable experiences.',
      heroImage: 'wedding-venue-garden-ceremony',
      socialProof: 'Wedding venues using Mouse book 40% more tours through instant availability responses.',
      ctaText: 'See Your Venue on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your venue business advisor',
      greeting: "Welcome! Let's fill your calendar with beautiful celebrations. I'll handle the inquiries, tours, and admin so you can focus on making every event stunning.",
      sampleAdvice: [
        'You have 6 open Saturdays in peak season (June-October). At your average booking value of $8,000, that\'s $48,000 in potential revenue. Time to push availability.',
        'Your Sunday/Friday bookings are only 20% of capacity. Consider a discounted off-peak package to fill those dates.',
        '3 couples who toured this month haven\'t received a follow-up. Want me to send a personalized check-in?',
      ],
      knowledgeDomains: ['venue management', 'event logistics', 'vendor coordination', 'seasonal pricing', 'capacity planning', 'hospitality'],
    },
    aiReceptionist: {
      greeting: "Hello, thank you for calling {{business_name}}! This is Mouse, our virtual assistant. Congratulations on your upcoming celebration! I can help with availability, tours, venue details, and pricing. What date are you looking at?",
      personality: "Elegant and warm. Treats every inquiry as the beginning of someone's dream day. Creates excitement about the venue without being salesy. Patient with couples who are early in their planning process.",
      faqs: [
        { question: 'Are you available on [date]?', answer: "Let me check! What date are you considering? I'll look at our availability and get right back to you." },
        { question: 'How much does it cost to rent the venue?', answer: "Our venue rental starts at {{starting_price}} depending on the day of the week and time of year. This includes {{rental_includes}}. Want to schedule a tour to see the space and discuss packages?" },
        { question: 'What is your capacity?', answer: "We can accommodate up to {{max_capacity}} guests for a seated dinner and {{cocktail_capacity}} for a cocktail-style reception." },
        { question: 'Can we bring our own caterer?', answer: "{{catering_policy}}" },
        { question: 'Can we bring our own alcohol?', answer: "{{alcohol_policy}}" },
        { question: 'Do you have an indoor backup for rain?', answer: "{{rain_plan}}" },
        { question: 'How do we book a tour?', answer: "We'd love to show you around! Tours are available {{tour_availability}}. I can schedule one right now — what day works best?" },
      ],
      transferTriggers: [
        'Ready to book or discussing contract',
        'Custom event request (non-wedding)',
        'Vendor coordination issues',
        'Day-of event concerns or emergencies',
      ],
      escalationRules: {
        urgentKeywords: ['cancel', 'emergency', 'weather', 'this weekend', 'today', 'damage'],
        afterHoursMessage: "Thank you for calling {{business_name}}! We're not available right now. For tour requests and availability, please leave your name, phone number, and preferred wedding date, and we'll call you back within one business day. Or visit {{website}} to submit an inquiry.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Venue Info',
          description: "Let's set up your venue profile.",
          fields: [
            { id: 'business_name', label: 'Venue Name', type: 'text', required: true, placeholder: 'e.g., Willow Creek Estate' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'address', label: 'Venue Address', type: 'text', required: true },
            { id: 'website', label: 'Website', type: 'url', required: false },
          ],
        },
        {
          id: 'venue-details',
          title: 'Venue Details',
          description: 'Tell us about your space.',
          fields: [
            { id: 'max_capacity', label: 'Max Seated Capacity', type: 'number', required: true, placeholder: '200' },
            { id: 'cocktail_capacity', label: 'Max Cocktail Capacity', type: 'number', required: false, placeholder: '300' },
            { id: 'venue_type', label: 'Venue Style', type: 'multiselect', required: true, options: ['Barn/Rustic', 'Garden/Outdoor', 'Ballroom', 'Historic', 'Modern/Industrial', 'Waterfront', 'Vineyard/Winery', 'Estate/Mansion'] },
            { id: 'rain_plan', label: 'Indoor/Rain Backup', type: 'text', required: true, placeholder: 'e.g., Yes, our climate-controlled pavilion seats 200 guests' },
          ],
        },
        {
          id: 'pricing',
          title: 'Pricing & Packages',
          description: 'How do you price your venue?',
          fields: [
            { id: 'starting_price', label: 'Starting Rental Price', type: 'currency', required: true, placeholder: '5000' },
            { id: 'rental_includes', label: 'What\'s Included', type: 'text', required: true, placeholder: 'e.g., ceremony & reception space, tables, chairs, setup & teardown, parking' },
            { id: 'catering_policy', label: 'Catering Policy', type: 'text', required: true, placeholder: 'e.g., We have a preferred caterer list, or you can bring your own with a $500 kitchen fee' },
            { id: 'alcohol_policy', label: 'Alcohol Policy', type: 'text', required: true, placeholder: 'e.g., BYOB welcome with licensed bartender required, or use our bar service starting at $20/person' },
          ],
        },
        {
          id: 'tours',
          title: 'Tours & Booking',
          description: 'How do you show your space?',
          fields: [
            { id: 'tour_availability', label: 'Tour Availability', type: 'text', required: true, placeholder: 'e.g., Tuesday-Saturday by appointment' },
            { id: 'deposit_required', label: 'Deposit to Book', type: 'text', required: true, placeholder: 'e.g., $1,500 non-refundable deposit to reserve your date' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'upcoming-events', type: 'list', title: 'Upcoming Events', dataSource: 'events_upcoming', refreshInterval: 3600 },
      { id: 'pending-tours', type: 'list', title: 'Scheduled Tours', dataSource: 'tours_scheduled', refreshInterval: 1800 },
      { id: 'availability', type: 'chart', title: 'Date Availability', dataSource: 'calendar_availability', refreshInterval: 86400 },
      { id: 'pending-inquiries', type: 'list', title: 'Pending Inquiries', dataSource: 'inquiries_pending', refreshInterval: 600 },
    ],
    sampleTasks: [
      { id: 'tour-followup', title: 'Follow Up After Tours', description: 'Send personalized follow-ups to couples who toured but haven\'t booked', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'availability-update', title: 'Share Available Dates', description: 'Post remaining peak-season availability to social media', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'vendor-confirm', title: 'Confirm Event Vendors', description: 'Send vendor confirmation for this week\'s events', difficulty: 'automatic', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'annual-events', label: 'Events Booked (Year)', format: 'number', target: 50, currentValue: 0 },
      { id: 'avg-booking', label: 'Average Booking Value', format: 'currency', target: 8000, currentValue: 0 },
      { id: 'tour-to-booking', label: 'Tour to Booking Rate', format: 'percentage', target: 40, currentValue: 0 },
      { id: 'peak-utilization', label: 'Peak Saturday Utilization', format: 'percentage', target: 90, currentValue: 0 },
    ],
    integrations: [
      { id: 'honeybook', name: 'HoneyBook', category: 'crm', priority: 'recommended', setupTime: 15 },
      { id: 'the-knot', name: 'The Knot', category: 'marketplace', priority: 'essential', setupTime: 15 },
      { id: 'weddingwire', name: 'WeddingWire', category: 'marketplace', priority: 'essential', setupTime: 15 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'tour-confirmation', name: 'Tour Confirmation', subject: "Your tour at {{business_name}} is confirmed!", body: "Hi {{customer_name}},\n\nWe're thrilled to show you {{business_name}}! Your tour is confirmed for:\n\n📅 {{tour_date}} at {{tour_time}}\n📍 {{address}}\n\nFeel free to bring family or your wedding party. Wear comfortable shoes — we'll walk the grounds together!\n\nSee you soon,\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'tour-reminder', name: 'Tour Reminder', body: "Hi {{customer_name}}! Just a reminder about your tour at {{business_name}} tomorrow at {{tour_time}}. We can't wait to show you around! 🌿", trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'venue', 'wedding-venue', 'weddings'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'party-rental',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'party-rental',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Everything you need to throw the perfect party',
      description: 'A party rental company providing tents, tables, chairs, linens, and event essentials — delivering and setting up everything so hosts can focus on enjoying their event.',
      primaryColor: '#FF6F00',
      secondaryColor: '#FFF3E0',
      tone: 'helpful, organized, enthusiastic',
      personality: 'Like a super-organized friend who shows up with everything you need and makes setup look effortless.',
    },
    demoExperience: {
      headline: 'Your Rental Business, Perfectly Set Up',
      subheadline: 'Mouse handles quotes, delivery scheduling, and inventory tracking — so you can focus on making events happen.',
      heroImage: 'party-tent-elegant-setup-outdoor',
      socialProof: 'Party rental companies using Mouse generate 30% more quotes through instant inquiry responses.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your party rental business advisor',
      greeting: "Hey there! Let's make your rental business the first call for every event in town. I'll handle the quotes and logistics so you can focus on delivering great events.",
      sampleAdvice: [
        'You have 3 quote requests over $2,000 that are 4+ days old. Those expire fast — want me to send follow-ups?',
        'This weekend you have 4 deliveries and 3 pickups. Your truck can handle 3 trips max. You may need to adjust the schedule.',
        'Graduation season starts in 6 weeks. Last year it was your busiest month. Time to promote graduation party packages.',
      ],
      knowledgeDomains: ['event rentals', 'logistics management', 'inventory control', 'delivery routing', 'seasonal demand', 'event setup'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help you with rental items, quotes, availability, and delivery info. What kind of event are you planning?",
      personality: "Helpful and organized. Asks the right questions about event size, location, and needs. Makes the rental process feel easy and stress-free. Good at suggesting items people might not think of.",
      faqs: [
        { question: 'What do you rent?', answer: "We rent {{inventory_categories}}. We've got everything you need to throw a great event!" },
        { question: 'How much does a tent cost?', answer: "Our tent rentals start at {{tent_starting_price}} depending on size. A {{common_tent_size}} is our most popular and runs about {{common_tent_price}}. Want me to put together a custom quote?" },
        { question: 'Do you deliver and set up?', answer: "Absolutely! {{delivery_policy}}. We handle all the setup and takedown so you don't have to lift a finger." },
        { question: 'How far in advance should I book?', answer: "For peak season ({{peak_season}}), we recommend booking {{peak_lead_time}}. For off-peak events, {{offpeak_lead_time}} is usually fine." },
        { question: 'What\'s your cancellation policy?', answer: "{{cancellation_policy}}" },
      ],
      transferTriggers: [
        'Quote request over $3,000',
        'Corporate or multi-event account',
        'Custom setup or unusual item request',
        'Delivery logistics for difficult locations',
      ],
      escalationRules: {
        urgentKeywords: ['tomorrow', 'today', 'emergency', 'cancel', 'damaged', 'missing item'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but back at {{next_open}}. Leave a message with your event date and what you need, and we'll get back to you ASAP. For day-of emergencies, text us at {{phone}}.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your rental business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Grand Event Rentals' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'address', label: 'Warehouse Address', type: 'text', required: true },
            { id: 'delivery_area', label: 'Delivery Area', type: 'text', required: true, placeholder: 'e.g., within 40 miles of warehouse' },
          ],
        },
        {
          id: 'inventory',
          title: 'Your Inventory',
          description: 'What do you rent out?',
          fields: [
            { id: 'inventory_categories', label: 'Rental Categories', type: 'multiselect', required: true, options: ['Tents', 'Tables', 'Chairs', 'Linens', 'Dinnerware', 'Dance Floors', 'Staging', 'Lighting', 'Heaters/Fans', 'Inflatables', 'Games', 'Bars', 'Cooking Equipment'] },
            { id: 'tent_starting_price', label: 'Tent Starting Price', type: 'text', required: false, placeholder: 'e.g., $250 for a 10x10' },
            { id: 'common_tent_size', label: 'Most Popular Tent Size', type: 'text', required: false, placeholder: 'e.g., 20x40' },
            { id: 'common_tent_price', label: 'Popular Tent Price', type: 'text', required: false, placeholder: 'e.g., $800' },
          ],
        },
        {
          id: 'logistics',
          title: 'Delivery & Setup',
          description: 'How do you handle delivery?',
          fields: [
            { id: 'delivery_policy', label: 'Delivery & Setup Policy', type: 'text', required: true, placeholder: 'e.g., Free delivery & setup within 20 miles. Setup fee of $1/mile beyond that.' },
            { id: 'peak_season', label: 'Peak Season', type: 'text', required: true, placeholder: 'e.g., May through October' },
            { id: 'peak_lead_time', label: 'Peak Booking Lead Time', type: 'text', required: true, placeholder: 'e.g., at least 4-6 weeks out' },
            { id: 'offpeak_lead_time', label: 'Off-Peak Lead Time', type: 'text', required: false, placeholder: 'e.g., 1-2 weeks is usually fine' },
          ],
        },
        {
          id: 'policies',
          title: 'Policies',
          description: 'Your business policies.',
          fields: [
            { id: 'cancellation_policy', label: 'Cancellation Policy', type: 'text', required: true, placeholder: 'e.g., Full refund if cancelled 14+ days before event. 50% refund within 14 days.' },
            { id: 'damage_policy', label: 'Damage Policy', type: 'text', required: true, placeholder: 'e.g., Normal wear expected. Excessive damage charged at replacement cost.' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'upcoming-deliveries', type: 'list', title: 'Upcoming Deliveries', dataSource: 'deliveries_scheduled', refreshInterval: 1800 },
      { id: 'pending-quotes', type: 'list', title: 'Pending Quotes', dataSource: 'quotes_pending', refreshInterval: 600 },
      { id: 'pickups-due', type: 'alert', title: 'Pickups Due', dataSource: 'pickups_due', refreshInterval: 3600 },
      { id: 'inventory-status', type: 'chart', title: 'Inventory Availability', dataSource: 'inventory_availability', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'quote-followup', title: 'Follow Up on Quotes', description: 'Send follow-ups to pending quotes that are 3+ days old', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'pickup-schedule', title: 'Schedule Pickups', description: 'Coordinate post-event equipment pickup times with clients', difficulty: 'needs-approval', estimatedMinutes: 10 },
      { id: 'inventory-check', title: 'Weekly Inventory Check', description: 'Verify inventory counts and flag damaged items needing repair', difficulty: 'needs-approval', estimatedMinutes: 15 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 25000, currentValue: 0 },
      { id: 'events-served', label: 'Events Served/Month', format: 'number', target: 20, currentValue: 0 },
      { id: 'avg-order', label: 'Average Order Value', format: 'currency', target: 1200, currentValue: 0 },
      { id: 'utilization', label: 'Equipment Utilization', format: 'percentage', target: 60, currentValue: 0 },
    ],
    integrations: [
      { id: 'goodshuffle', name: 'Goodshuffle Pro', category: 'inventory', priority: 'recommended', setupTime: 20 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'quote', name: 'Rental Quote', subject: 'Your event rental quote from {{business_name}}', body: "Hi {{customer_name}},\n\nThanks for reaching out about your {{event_type}} on {{event_date}}! Here's your custom rental quote:\n\n{{quote_details}}\n\nThis quote is valid for 14 days. To lock in your date, we just need a {{deposit_amount}} deposit.\n\nQuestions? We're here to help!\n\n{{business_name}}\n{{phone}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'delivery-confirm', name: 'Delivery Confirmation', body: '🎪 Hi {{customer_name}}! Your {{business_name}} delivery is confirmed for {{delivery_date}} between {{delivery_window}}. We\'ll call when we\'re on the way!', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'party-rental', 'tent-rental', 'equipment'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'photo-booth',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'photo-booth',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Instant memories, endless fun',
      description: 'A photo booth rental service bringing interactive photo fun to weddings, parties, and corporate events — complete with props, backdrops, and instant prints.',
      primaryColor: '#FF4081',
      secondaryColor: '#FCE4EC',
      tone: 'fun, energetic, playful',
      personality: 'Like the fun friend at the party who gets everyone laughing and posing — instant good vibes guaranteed.',
    },
    demoExperience: {
      headline: 'Your Photo Booth Business, Say Cheese!',
      subheadline: 'Mouse handles booking inquiries and event coordination — so you can focus on delivering the fun.',
      heroImage: 'photo-booth-guests-props-laughing',
      socialProof: 'Photo booth companies using Mouse book 35% more events through instant inquiry responses.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your photo booth business advisor',
      greeting: "Say cheese! Let's get your photo booth business booking like crazy. I'll handle the inquiries and logistics while you deliver the fun.",
      sampleAdvice: [
        'Prom season is 6 weeks out. Last year you booked 12 school events. Time to reach out to event coordinators at local high schools.',
        'Your 360 booth is booked every weekend but your classic booth sits empty 40% of the time. Consider a discounted classic package.',
        'Add a "social sharing station" upsell — Instagram-ready digital copies drive 60% of referral bookings for photo booth companies.',
      ],
      knowledgeDomains: ['photo booth operations', 'event entertainment', 'social media marketing', 'print technology', 'prop management', 'corporate branding'],
    },
    aiReceptionist: {
      greeting: "Hey there, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. Looking for a photo booth for your event? I can help with availability, packages, and pricing. What's the occasion?",
      personality: "Fun and enthusiastic. Gets people excited about the photo booth experience. Asks about the event vibe to recommend the right booth type. Makes booking feel easy and exciting.",
      faqs: [
        { question: 'How much does a photo booth cost?', answer: "Our packages start at {{starting_price}} for {{base_hours}} hours. This includes {{base_includes}}. We have packages for every budget!" },
        { question: 'What types of booths do you have?', answer: "We offer {{booth_types}}. Each creates a different experience — I'd love to help you pick the right one for your event!" },
        { question: 'Do you provide props?', answer: "Yes! We bring a full prop collection — hats, glasses, signs, and themed props. We can also create custom props for your event!" },
        { question: 'Can we customize the photo strips?', answer: "Absolutely! Every booking includes custom-designed photo strips with your event name, date, colors, and even a logo. We'll send you a design proof before the event." },
        { question: 'Do you deliver and set up?', answer: "{{delivery_policy}}" },
        { question: 'Are digital copies included?', answer: "{{digital_policy}}" },
      ],
      transferTriggers: [
        'Corporate event with custom branding needs',
        'Multi-booth event',
        'Ready to book and needs contract',
        'Custom backdrop or prop request',
      ],
      escalationRules: {
        urgentKeywords: ['tomorrow', 'this weekend', 'cancel', 'emergency', 'equipment issue'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're probably at an event right now capturing smiles. Leave your name, event date, and type of event, and we'll get back to you within 24 hours!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your photo booth business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., SnapZone Photo Booth' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Greater Chicago area, up to 60 miles' },
          ],
        },
        {
          id: 'booths',
          title: 'Your Booth Options',
          description: 'What kinds of photo booths do you offer?',
          fields: [
            { id: 'booth_types', label: 'Booth Types', type: 'multiselect', required: true, options: ['Classic Enclosed Booth', 'Open Air Booth', '360 Video Booth', 'Mirror Booth', 'GIF Booth', 'Glam Booth', 'Selfie Station'] },
            { id: 'starting_price', label: 'Starting Package Price', type: 'currency', required: true, placeholder: '400' },
            { id: 'base_hours', label: 'Base Package Hours', type: 'text', required: true, placeholder: 'e.g., 2' },
            { id: 'base_includes', label: 'Base Package Includes', type: 'text', required: true, placeholder: 'e.g., unlimited prints, props, custom photo strip design, attendant' },
          ],
        },
        {
          id: 'details',
          title: 'Service Details',
          description: 'Help us understand your service.',
          fields: [
            { id: 'delivery_policy', label: 'Delivery & Setup', type: 'text', required: true, placeholder: 'e.g., We arrive 1 hour early for setup and handle everything. Teardown after the event is included.' },
            { id: 'digital_policy', label: 'Digital Copies', type: 'text', required: true, placeholder: 'e.g., Yes! All photos are available digitally via text/email sharing. Online gallery included.' },
          ],
        },
        {
          id: 'booking',
          title: 'Booking Details',
          description: 'Your booking process.',
          fields: [
            { id: 'deposit', label: 'Deposit Amount', type: 'text', required: true, placeholder: 'e.g., $100 non-refundable deposit to reserve your date' },
            { id: 'website', label: 'Website', type: 'url', required: false },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'upcoming-events', type: 'list', title: 'Upcoming Events', dataSource: 'calendar_upcoming', refreshInterval: 3600 },
      { id: 'pending-inquiries', type: 'list', title: 'Pending Inquiries', dataSource: 'inquiries_pending', refreshInterval: 600 },
      { id: 'monthly-bookings', type: 'metric', title: 'Bookings This Month', dataSource: 'bookings_monthly', refreshInterval: 86400 },
      { id: 'revenue', type: 'chart', title: 'Monthly Revenue', dataSource: 'revenue_monthly', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'inquiry-followup', title: 'Follow Up on Inquiries', description: 'Send follow-ups to pending inquiries that are 48+ hours old', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'review-request', title: 'Request Reviews', description: 'Send review requests 2 days after events', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'gallery-share', title: 'Share Event Gallery', description: 'Send online gallery link to event host the day after their event', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 6000, currentValue: 0 },
      { id: 'events-month', label: 'Events/Month', format: 'number', target: 10, currentValue: 0 },
      { id: 'avg-booking', label: 'Average Booking', format: 'currency', target: 600, currentValue: 0 },
      { id: 'inquiry-conversion', label: 'Inquiry to Booking', format: 'percentage', target: 40, currentValue: 0 },
    ],
    integrations: [
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'gallery-share', name: 'Event Gallery', subject: '📸 Your photo booth gallery from {{event_name}}!', body: "Hey {{customer_name}},\n\nYour photo booth gallery is live! Share it with your guests:\n\n{{gallery_link}}\n\nEveryone had such a blast — thank you for choosing {{business_name}}!\n\nIf you loved the experience, we'd be so grateful for a review: {{review_link}}\n\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'gallery-sms', name: 'Gallery Link', body: '📸 Your {{business_name}} photo booth pics are ready! View & download: {{gallery_link}} Thanks for a great time!', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'photo-booth', 'photography', 'entertainment'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'limo-service',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'limo-service',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Arrive in style, leave the driving to us',
      description: 'A professional limousine and luxury transportation service providing elegant, reliable rides for weddings, proms, corporate events, and special occasions.',
      primaryColor: '#212121',
      secondaryColor: '#F5F5F5',
      tone: 'professional, luxurious, reliable',
      personality: 'Like a five-star concierge on wheels — impeccable service, attention to detail, and always on time.',
    },
    demoExperience: {
      headline: 'Your Limo Business, Running Like Clockwork',
      subheadline: 'Mouse handles reservations, dispatch, and customer communication — so you can focus on delivering first-class experiences.',
      heroImage: 'stretch-limo-elegant-entrance',
      socialProof: 'Limo services using Mouse book 30% more rides through after-hours reservation handling.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your transportation business advisor',
      greeting: "Welcome aboard! Let's make your limo service the most in-demand ride in town. I'll handle reservations and communication so your drivers can focus on delivering a premium experience.",
      sampleAdvice: [
        'Prom season starts in 8 weeks. Last year you were fully booked 3 weeks before prom night. Start marketing now and consider hiring a freelance driver.',
        'Your Saturday evening fleet utilization is 95% but weekday utilization is only 30%. Consider corporate shuttle or airport transfer packages.',
        'You have 2 reservations for this weekend that haven\'t been confirmed. Want me to reach out?',
      ],
      knowledgeDomains: ['luxury transportation', 'fleet management', 'chauffeur operations', 'event logistics', 'airport transfers', 'DOT compliance'],
    },
    aiReceptionist: {
      greeting: "Thank you for calling {{business_name}}! This is Mouse, our virtual assistant. I can help you with reservations, vehicle availability, pricing, or any questions about our luxury transportation services. What's the occasion?",
      personality: "Professional and polished. Makes every caller feel like a VIP. Asks about the occasion, party size, and special requests. Understands that limo service is about creating an experience, not just a ride.",
      faqs: [
        { question: 'What vehicles do you have?', answer: "Our fleet includes {{fleet_description}}. Each vehicle is impeccably maintained and stocked with {{amenities}}." },
        { question: 'How much does it cost?', answer: "Our rates start at {{starting_rate}}. Final pricing depends on the vehicle, date, duration, and pick-up location. Want me to put together a custom quote?" },
        { question: 'Do you do airport transfers?', answer: "{{airport_policy}}" },
        { question: 'How far in advance should I book?', answer: "For proms and weddings, we recommend booking {{event_lead_time}}. For other occasions, {{general_lead_time}} is usually fine." },
        { question: 'What\'s your cancellation policy?', answer: "{{cancellation_policy}}" },
        { question: 'Do you serve alcohol in the limo?', answer: "{{alcohol_policy}}" },
      ],
      transferTriggers: [
        'Wedding or prom booking',
        'Multi-vehicle reservation',
        'Corporate account setup',
        'Complaint or service issue',
      ],
      escalationRules: {
        urgentKeywords: ['driver late', 'no show', 'cancel', 'emergency', 'tonight', 'accident'],
        afterHoursMessage: "Thank you for calling {{business_name}}. For existing reservations, press or say 1. For new reservations, leave a message with your date, time, party size, and pick-up location, and we'll call you back within 4 hours during business hours.",
        maxTransferAttempts: 3,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your limo service.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Elite Class Limousine' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Tri-state area — NY, NJ, CT' },
          ],
        },
        {
          id: 'fleet',
          title: 'Your Fleet',
          description: 'Tell us about your vehicles.',
          fields: [
            { id: 'fleet_description', label: 'Fleet Description', type: 'text', required: true, placeholder: 'e.g., stretch limos (8-10 passengers), SUV limos (14-16), party buses (20-30), luxury sedans (3)' },
            { id: 'amenities', label: 'Standard Amenities', type: 'text', required: false, placeholder: 'e.g., bottled water, ice, glassware, Bluetooth, LED lighting' },
          ],
        },
        {
          id: 'pricing',
          title: 'Pricing & Services',
          description: 'Your rates and services.',
          fields: [
            { id: 'starting_rate', label: 'Starting Hourly Rate', type: 'text', required: true, placeholder: 'e.g., $125/hour with a 3-hour minimum' },
            { id: 'airport_policy', label: 'Airport Transfer Info', type: 'text', required: false, placeholder: 'e.g., One-way airport transfers from $85. We monitor your flight for delays.' },
            { id: 'alcohol_policy', label: 'Alcohol Policy', type: 'text', required: true, placeholder: 'e.g., BYOB is welcome for passengers 21+. We provide ice, glasses, and a cooler.' },
          ],
        },
        {
          id: 'policies',
          title: 'Policies',
          description: 'Your booking policies.',
          fields: [
            { id: 'event_lead_time', label: 'Event Booking Lead Time', type: 'text', required: true, placeholder: 'e.g., at least 2-3 months for weddings and proms' },
            { id: 'general_lead_time', label: 'General Booking Lead Time', type: 'text', required: false, placeholder: 'e.g., 48-72 hours for most occasions' },
            { id: 'cancellation_policy', label: 'Cancellation Policy', type: 'text', required: true, placeholder: 'e.g., Full refund with 72+ hours notice. 50% within 72 hours. No refund within 24 hours.' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'todays-rides', type: 'list', title: "Today's Rides", dataSource: 'reservations_today', refreshInterval: 300 },
      { id: 'upcoming-reservations', type: 'list', title: 'Upcoming Reservations', dataSource: 'reservations_upcoming', refreshInterval: 1800 },
      { id: 'fleet-status', type: 'chart', title: 'Fleet Availability', dataSource: 'fleet_status', refreshInterval: 3600 },
      { id: 'pending-quotes', type: 'list', title: 'Pending Quotes', dataSource: 'quotes_pending', refreshInterval: 600 },
    ],
    sampleTasks: [
      { id: 'ride-confirmation', title: 'Confirm Rides', description: 'Send confirmation texts 24 hours before scheduled pickups', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'quote-followup', title: 'Follow Up on Quotes', description: 'Send follow-ups to pending quotes that are 48+ hours old', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'review-request', title: 'Request Reviews', description: 'Send review request the day after a ride', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 20000, currentValue: 0 },
      { id: 'rides-month', label: 'Rides/Month', format: 'number', target: 30, currentValue: 0 },
      { id: 'avg-booking', label: 'Average Booking', format: 'currency', target: 650, currentValue: 0 },
      { id: 'fleet-utilization', label: 'Fleet Utilization', format: 'percentage', target: 55, currentValue: 0 },
    ],
    integrations: [
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'reservation-confirm', name: 'Reservation Confirmation', subject: 'Your reservation with {{business_name}} is confirmed!', body: "Dear {{customer_name}},\n\nYour luxury transportation is confirmed:\n\n📅 Date: {{ride_date}}\n⏰ Pickup: {{pickup_time}}\n📍 Location: {{pickup_location}}\n🚗 Vehicle: {{vehicle_type}}\n⏱️ Duration: {{duration}}\n\nYour chauffeur will arrive 10 minutes early. You'll receive a text when they're on the way.\n\nQuestions? Call us at {{phone}}.\n\nThank you for choosing {{business_name}}!", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'driver-enroute', name: 'Driver En Route', body: 'Your {{business_name}} chauffeur is on the way! Estimated arrival: {{eta}}. Vehicle: {{vehicle_description}}. Call {{driver_phone}} if needed.', trigger: 'automated' },
      { id: 'ride-confirm', name: 'Ride Confirmation', body: '✅ Reminder: Your {{business_name}} ride is tomorrow at {{pickup_time}} from {{pickup_location}}. Reply CONFIRM or call {{phone}} with questions.', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'limo', 'transportation', 'luxury'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'wedding-planner',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'wedding-planner',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Your dream wedding, without the stress',
      description: 'A dedicated wedding planning service that turns your vision into reality — handling every detail from the first "yes" to the last dance.',
      primaryColor: '#AD1457',
      secondaryColor: '#FCE4EC',
      tone: 'romantic, organized, reassuring',
      personality: 'Like having a calm, experienced best friend who has planned 200 weddings and makes you feel like yours is the only one that matters.',
    },
    demoExperience: {
      headline: 'Your Wedding Planning Business, Beautifully Organized',
      subheadline: 'Mouse handles inquiries, vendor follow-ups, and client communication — so you can focus on creating the wedding of their dreams.',
      heroImage: 'wedding-planner-detail-table-setup',
      socialProof: 'Wedding planners using Mouse save 10 hours per week on client communication alone.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your wedding planning business advisor',
      greeting: "Hello, wedding extraordinaire! Let's make your business as beautiful as the weddings you plan. I'll handle the admin so every couple gets your full creative attention.",
      sampleAdvice: [
        'You have 3 active weddings in the next 30 days. All vendor confirmations should go out this week — want me to send them?',
        'Engagement season peaks in December. Start your January marketing campaign for newly engaged couples now.',
        'Your last 5 clients came from Instagram. Consider increasing your posting frequency and adding Reels of your weddings.',
      ],
      knowledgeDomains: ['wedding planning', 'vendor management', 'budgeting', 'design & decor', 'timeline coordination', 'destination weddings'],
    },
    aiReceptionist: {
      greeting: "Hello, thank you for calling {{business_name}}! This is Mouse, our virtual assistant. First off — congratulations! I can help with information about our planning services, availability, and packages. Tell me about your dream wedding!",
      personality: "Romantic and reassuring. Makes couples feel like their wedding is the most important event in the world (because to them, it is). Asks about their vision, not just logistics. Never makes the process feel transactional. Reassures anxious couples that everything will be perfect.",
      faqs: [
        { question: 'What services do you offer?', answer: "We offer {{service_levels}}. Whether you want us to handle everything from day one or just need someone amazing on the big day, we've got you covered." },
        { question: 'How much does wedding planning cost?', answer: "Our packages start at {{starting_price}}. Every wedding is unique, so we'd love to have a consultation to understand your vision and create a custom proposal." },
        { question: 'How far in advance should we book?', answer: "For full planning, we recommend {{full_planning_lead}}. For day-of coordination, {{day_of_lead}} usually works. But reach out anytime — we'll make it work!" },
        { question: 'Do you travel for destination weddings?', answer: "{{destination_policy}}" },
        { question: 'How many weddings do you do at once?', answer: "We intentionally limit ourselves to {{concurrent_max}} weddings at a time so every couple gets our full attention." },
      ],
      transferTriggers: [
        'Couple ready to book a consultation',
        'Destination wedding inquiry',
        'Budget over $50,000',
        'Vendor emergency for an active wedding',
      ],
      escalationRules: {
        urgentKeywords: ['cancel', 'vendor cancelled', 'emergency', 'this week', 'disaster', 'help'],
        afterHoursMessage: "Thank you for calling {{business_name}}! We can't wait to hear about your wedding plans. Leave a message with your name, wedding date, and a little about your vision, and we'll call you back within one business day.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your wedding planning business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Bliss & Bloom Weddings' },
            { id: 'planner_name', label: 'Your Name', type: 'text', required: true },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Southern California + destination' },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What planning services do you offer?',
          fields: [
            { id: 'service_levels', label: 'Service Levels', type: 'text', required: true, placeholder: 'e.g., full planning, partial planning, and month-of coordination' },
            { id: 'starting_price', label: 'Starting Price', type: 'currency', required: true, placeholder: '2000' },
            { id: 'concurrent_max', label: 'Max Concurrent Weddings', type: 'number', required: true, placeholder: '4' },
          ],
        },
        {
          id: 'details',
          title: 'Planning Details',
          description: 'Help us understand your approach.',
          fields: [
            { id: 'full_planning_lead', label: 'Full Planning Lead Time', type: 'text', required: true, placeholder: 'e.g., 9-12 months before the wedding' },
            { id: 'day_of_lead', label: 'Day-Of Coordination Lead Time', type: 'text', required: true, placeholder: 'e.g., 6-8 weeks before' },
            { id: 'destination_policy', label: 'Destination Weddings', type: 'text', required: false, placeholder: 'e.g., We love destination weddings! Travel fees apply — let\'s chat about your dream location.' },
          ],
        },
        {
          id: 'presence',
          title: 'Online Presence',
          description: 'How do couples find you?',
          fields: [
            { id: 'website', label: 'Website', type: 'url', required: false },
            { id: 'instagram', label: 'Instagram', type: 'text', required: false, placeholder: '@yourbusiness' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'active-weddings', type: 'list', title: 'Active Weddings', dataSource: 'weddings_active', refreshInterval: 3600 },
      { id: 'upcoming-deadlines', type: 'alert', title: 'Vendor Deadlines', dataSource: 'deadlines_vendor', refreshInterval: 3600 },
      { id: 'pending-inquiries', type: 'list', title: 'New Inquiries', dataSource: 'inquiries_pending', refreshInterval: 600 },
      { id: 'next-30-days', type: 'list', title: 'Next 30 Days', dataSource: 'calendar_30_day', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'vendor-confirm', title: 'Confirm Wedding Vendors', description: 'Send final confirmations to all vendors 2 weeks before each wedding', difficulty: 'needs-approval', estimatedMinutes: 15 },
      { id: 'inquiry-response', title: 'Respond to Inquiries', description: 'Send personalized responses to new couple inquiries', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'post-wedding', title: 'Post-Wedding Follow-Up', description: 'Send thank-you notes and review requests after each wedding', difficulty: 'automatic', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'active-weddings', label: 'Active Weddings', format: 'number', target: 4, currentValue: 0 },
      { id: 'annual-revenue', label: 'Annual Revenue', format: 'currency', target: 80000, currentValue: 0 },
      { id: 'avg-package', label: 'Average Package', format: 'currency', target: 4500, currentValue: 0 },
      { id: 'referral-rate', label: 'Referral Rate', format: 'percentage', target: 50, currentValue: 0 },
    ],
    integrations: [
      { id: 'honeybook', name: 'HoneyBook', category: 'crm', priority: 'essential', setupTime: 15 },
      { id: 'aisle-planner', name: 'Aisle Planner', category: 'planning', priority: 'recommended', setupTime: 15 },
      { id: 'the-knot', name: 'The Knot', category: 'marketplace', priority: 'essential', setupTime: 15 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'consultation-confirm', name: 'Consultation Confirmation', subject: "Let's plan your dream wedding! - {{business_name}}", body: "Dear {{customer_name}},\n\nI am SO excited to meet with you and hear all about your wedding vision!\n\nYour consultation is confirmed:\n📅 {{consultation_date}} at {{consultation_time}}\n📍 {{consultation_location}}\n\nBefore we meet, think about:\n- Your dream wedding vibe (rustic? glam? garden party?)\n- Must-have elements\n- Approximate guest count\n- Budget range\n\nDon't worry if you don't have all the answers — that's what I'm here for!\n\nCan't wait,\n{{planner_name}}\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'inquiry-response', name: 'Quick Inquiry Response', body: "Hi {{customer_name}}! Congratulations on your engagement! 💍 This is {{planner_name}} from {{business_name}}. I'd love to hear about your wedding plans. When's a good time to chat?", trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'wedding-planner', 'weddings', 'planning'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'live-band',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'live-band',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Live music that makes your event legendary',
      description: 'A professional live band bringing energy, talent, and the magic of live music to weddings, corporate events, and private parties.',
      primaryColor: '#F57F17',
      secondaryColor: '#FFF8E1',
      tone: 'energetic, talented, professional',
      personality: 'Like a group of incredibly talented musicians who are also genuinely fun people — they make every crowd come alive.',
    },
    demoExperience: {
      headline: 'Your Band Business, Hitting Every Note',
      subheadline: 'Mouse handles booking inquiries and event logistics — so you and your band can focus on performing.',
      heroImage: 'live-band-stage-crowd-energy',
      socialProof: 'Live bands using Mouse book 35% more gigs through faster inquiry responses.',
      ctaText: 'See Your Band on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your band business advisor',
      greeting: "Rock on! Let's get your band booked solid. I'll handle the business side so you can focus on making music and blowing crowds away.",
      sampleAdvice: [
        'You have 5 open Saturdays in June-September. Wedding bands in your area average $4,000/gig — that\'s $20,000 in potential bookings.',
        'Your demo video is 3 years old. Modern couples want to see recent footage — consider filming at your next gig.',
        'Corporate holiday party inquiries usually start in September. Time to reach out to last year\'s corporate clients.',
      ],
      knowledgeDomains: ['live music industry', 'event performance', 'booking management', 'setlist planning', 'sound equipment', 'band logistics'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. Interested in live music for your event? I can help with availability, packages, and song list info. What kind of event are you planning?",
      personality: "Energetic and passionate about music. Gets people excited about having a live band at their event. Explains the difference between live music and a DJ in a positive way. Asks about the crowd and vibe to recommend the right performance style.",
      faqs: [
        { question: 'How much does the band cost?', answer: "Our packages start at {{starting_price}} for {{base_set_length}}. Pricing varies by event type, duration, and date. Want me to set up a call to discuss your event?" },
        { question: 'What kind of music do you play?', answer: "We cover a wide range including {{genres}}. We customize every setlist to match your event's vibe. We can also learn special songs for first dances or key moments!" },
        { question: 'How many musicians are in the band?', answer: "{{band_size}}. We can also scale up or down depending on your venue and budget." },
        { question: 'Do you bring your own sound equipment?', answer: "Yes! We bring a full professional sound system and lighting rig. We also do a sound check before guests arrive to make sure everything sounds perfect." },
        { question: 'Can you learn our first dance song?', answer: "Absolutely! We love learning special songs. Just let us know at least {{song_lead_time}} before the event so we can rehearse it to perfection." },
        { question: 'Can we see you perform live?', answer: "{{demo_policy}}" },
      ],
      transferTriggers: [
        'Ready to book or request contract',
        'Wedding with special song requests',
        'Multi-set or festival booking',
        'Corporate event over 300 guests',
      ],
      escalationRules: {
        urgentKeywords: ['cancel', 'this weekend', 'emergency', 'tomorrow', 'equipment'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're probably rehearsing or at a gig. Leave us a message with your event date, type, and guest count, and we'll get back to you within 24 hours. You can also check out our demo videos at {{website}}.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Band Info',
          description: "Let's set up your band's profile.",
          fields: [
            { id: 'business_name', label: 'Band Name', type: 'text', required: true, placeholder: 'e.g., The Silver Linings' },
            { id: 'phone', label: 'Booking Phone', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Southeast US — will travel for the right gig!' },
            { id: 'band_size', label: 'Band Size', type: 'text', required: true, placeholder: 'e.g., Our core band is 6 pieces: vocals, guitar, bass, drums, keys, and horns' },
          ],
        },
        {
          id: 'music',
          title: 'Your Music',
          description: 'What do you play?',
          fields: [
            { id: 'genres', label: 'Music Genres', type: 'text', required: true, placeholder: 'e.g., Top 40, Motown, funk, classic rock, country, R&B' },
            { id: 'song_lead_time', label: 'Special Song Lead Time', type: 'text', required: true, placeholder: 'e.g., 4 weeks' },
            { id: 'demo_policy', label: 'Demo/Preview Options', type: 'text', required: false, placeholder: 'e.g., Check out our live videos at our website, or attend one of our upcoming public shows!' },
          ],
        },
        {
          id: 'packages',
          title: 'Packages & Pricing',
          description: 'Your booking details.',
          fields: [
            { id: 'starting_price', label: 'Starting Price', type: 'currency', required: true, placeholder: '2500' },
            { id: 'base_set_length', label: 'Base Performance Length', type: 'text', required: true, placeholder: 'e.g., 3 hours (three 50-minute sets with breaks)' },
            { id: 'deposit', label: 'Deposit Required', type: 'text', required: true, placeholder: 'e.g., 50% deposit to reserve your date' },
          ],
        },
        {
          id: 'online',
          title: 'Online Presence',
          description: 'Where can people find you?',
          fields: [
            { id: 'website', label: 'Website', type: 'url', required: false },
            { id: 'instagram', label: 'Instagram', type: 'text', required: false, placeholder: '@yourband' },
            { id: 'youtube', label: 'YouTube Channel', type: 'url', required: false },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'upcoming-gigs', type: 'list', title: 'Upcoming Gigs', dataSource: 'calendar_upcoming', refreshInterval: 3600 },
      { id: 'pending-inquiries', type: 'list', title: 'Pending Inquiries', dataSource: 'inquiries_pending', refreshInterval: 600 },
      { id: 'monthly-bookings', type: 'metric', title: 'Gigs This Month', dataSource: 'bookings_monthly', refreshInterval: 86400 },
      { id: 'revenue', type: 'chart', title: 'Monthly Revenue', dataSource: 'revenue_monthly', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'inquiry-followup', title: 'Follow Up on Inquiries', description: 'Send follow-ups to pending booking inquiries over 48 hours old', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'setlist-prep', title: 'Send Setlist Questionnaire', description: 'Send song request forms to booked clients 4 weeks before their event', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'post-gig-review', title: 'Post-Gig Review Request', description: 'Send thank-you and review request 2 days after each gig', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 12000, currentValue: 0 },
      { id: 'gigs-month', label: 'Gigs/Month', format: 'number', target: 6, currentValue: 0 },
      { id: 'avg-booking', label: 'Average Booking Value', format: 'currency', target: 3500, currentValue: 0 },
      { id: 'booking-rate', label: 'Inquiry to Booking', format: 'percentage', target: 30, currentValue: 0 },
    ],
    integrations: [
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'the-knot', name: 'The Knot', category: 'marketplace', priority: 'recommended', setupTime: 15 },
      { id: 'gigsalad', name: 'GigSalad', category: 'marketplace', priority: 'recommended', setupTime: 15 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'booking-confirm', name: 'Booking Confirmation', subject: "You're booked! 🎶 {{business_name}} at your {{event_type}}", body: "Hi {{customer_name}},\n\nWe are SO excited to perform at your {{event_type}} on {{event_date}}!\n\nHere's what happens next:\n1. We'll send you a song request form {{song_lead_time}} before your event\n2. We'll coordinate load-in and sound check times with your venue\n3. On the day, we arrive early, set up quietly, and bring the house down\n\nThis is going to be an incredible night!\n\n🎵 {{business_name}}\n{{phone}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'inquiry-response', name: 'Inquiry Response', body: "Hey {{customer_name}}! Thanks for reaching out to {{business_name}}! We'd love to rock your {{event_type}} on {{event_date}}. When's a good time to chat? 🎸", trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'live-band', 'music', 'entertainment'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'karaoke-bar',
    version: '1.0.0',
    vertical: 'events-entertainment',
    subVertical: 'karaoke-bar',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Your stage, your song, your night',
      description: 'A karaoke bar where everyone from shower singers to secret rock stars can grab the mic, pick their song, and have the best night out in town.',
      primaryColor: '#E040FB',
      secondaryColor: '#F3E5F5',
      tone: 'fun, inclusive, lively',
      personality: 'Like the hype friend who cheers for everyone — whether they nail the high note or hilariously miss it. No judgment, all fun.',
    },
    demoExperience: {
      headline: 'Your Karaoke Bar, Always on Key',
      subheadline: 'Mouse handles reservations, private room bookings, and event inquiries — so you can focus on keeping the party going.',
      heroImage: 'karaoke-bar-colorful-stage-singing',
      socialProof: 'Karaoke bars using Mouse fill 40% more private room bookings through automated reservation handling.',
      ctaText: 'See Your Bar on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your karaoke bar business advisor',
      greeting: "Hey, superstar! Let's pack your bar every night of the week. I'll handle reservations and promotions so you can keep the crowd singing.",
      sampleAdvice: [
        'Tuesday and Wednesday nights are your slowest. Consider a "Half-Price Happy Hour + Free Karaoke" special to drive midweek traffic.',
        'Your private rooms are 90% booked on weekends but only 20% on weeknights. Offer a weeknight party package for birthday groups.',
        'Your most requested songs are from the 80s and 90s — make sure your catalog is current and consider themed throwback nights.',
      ],
      knowledgeDomains: ['bar operations', 'entertainment venue management', 'event hosting', 'food & beverage', 'nightlife marketing', 'private events'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with tonight's info, private room bookings, party reservations, or song list questions. What can I help you with?",
      personality: "Fun and welcoming. Makes everyone feel like a star. Gets people excited about coming in. Never makes anyone feel self-conscious about singing. Promotes the fun, social atmosphere.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Come grab the mic!" },
        { question: 'Do I need a reservation?', answer: "Walk-ins are always welcome for our main stage! For private rooms, we recommend reserving, especially on {{busy_nights}}." },
        { question: 'Do you have private rooms?', answer: "{{private_rooms}}" },
        { question: 'How much does it cost?', answer: "{{pricing_structure}}" },
        { question: 'Do you serve food?', answer: "{{food_menu}}" },
        { question: 'What songs do you have?', answer: "We have over {{song_count}} songs in our catalog — everything from classic rock to K-pop to country to today's hits. We add new songs every month!" },
        { question: 'Can I book a birthday party?', answer: "Absolutely! We love birthday parties. {{party_packages}}" },
        { question: 'Is there a minimum age?', answer: "{{age_policy}}" },
      ],
      transferTriggers: [
        'Private event or large party booking (10+ people)',
        'Corporate event inquiry',
        'Noise or safety complaint',
        'Liquor license or business inquiry',
      ],
      escalationRules: {
        urgentKeywords: ['fight', 'emergency', 'sick', 'ambulance', 'police', 'safety'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed right now but we open at {{next_open}}. For private room reservations, leave a message or text us. Can't wait to hear you sing! 🎤",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Bar Info',
          description: "Let's set up your karaoke bar.",
          fields: [
            { id: 'business_name', label: 'Bar Name', type: 'text', required: true, placeholder: 'e.g., Mic Drop Karaoke' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Hours', type: 'text', required: true, placeholder: 'e.g., Tue-Thu 6pm-12am, Fri-Sat 6pm-2am, Sun 5pm-11pm' },
            { id: 'address', label: 'Address', type: 'text', required: true },
          ],
        },
        {
          id: 'experience',
          title: 'The Experience',
          description: 'What makes your karaoke bar special?',
          fields: [
            { id: 'private_rooms', label: 'Private Rooms', type: 'text', required: false, placeholder: 'e.g., Yes! 5 private rooms for 4-15 people each, starting at $30/hour' },
            { id: 'song_count', label: 'Song Catalog Size', type: 'text', required: true, placeholder: 'e.g., 50,000' },
            { id: 'pricing_structure', label: 'Pricing', type: 'text', required: true, placeholder: 'e.g., No cover for main stage. Private rooms $30-$75/hour. Full bar and food menu.' },
            { id: 'busy_nights', label: 'Busiest Nights', type: 'text', required: true, placeholder: 'e.g., Friday and Saturday nights' },
          ],
        },
        {
          id: 'food-drink',
          title: 'Food & Drink',
          description: 'What do you serve?',
          fields: [
            { id: 'food_menu', label: 'Food Offerings', type: 'text', required: true, placeholder: 'e.g., Full menu with appetizers, sliders, wings, and late-night bites' },
            { id: 'drink_specials', label: 'Drink Specials', type: 'text', required: false, placeholder: 'e.g., $5 margaritas on Tuesdays, $3 beers before 8pm' },
            { id: 'age_policy', label: 'Age Policy', type: 'text', required: true, placeholder: 'e.g., 21+ after 9pm. All ages welcome before 9pm with a parent or guardian.' },
          ],
        },
        {
          id: 'events',
          title: 'Events & Parties',
          description: 'Tell us about your party options.',
          fields: [
            { id: 'party_packages', label: 'Party Packages', type: 'text', required: false, placeholder: 'e.g., Birthday packages start at $199 — includes private room, drink specials, and a song dedication!' },
            { id: 'corporate_events', label: 'Do Corporate Events?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'tonight-reservations', type: 'list', title: "Tonight's Reservations", dataSource: 'reservations_tonight', refreshInterval: 300 },
      { id: 'room-status', type: 'chart', title: 'Private Room Status', dataSource: 'rooms_status', refreshInterval: 300 },
      { id: 'weekly-revenue', type: 'metric', title: 'Weekly Revenue', dataSource: 'revenue_weekly', refreshInterval: 3600 },
      { id: 'upcoming-events', type: 'list', title: 'Upcoming Party Bookings', dataSource: 'events_upcoming', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'party-followup', title: 'Follow Up on Party Inquiries', description: 'Send follow-ups to pending party booking inquiries', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'weekly-promo', title: 'Promote Weekly Specials', description: 'Post this week\'s themed nights and drink specials', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'birthday-outreach', title: 'Birthday Outreach', description: 'Send birthday offers to customers with upcoming birthdays', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'weekly-revenue', label: 'Weekly Revenue', format: 'currency', target: 8000, currentValue: 0 },
      { id: 'private-room-utilization', label: 'Room Utilization', format: 'percentage', target: 70, currentValue: 0 },
      { id: 'avg-check', label: 'Average Check', format: 'currency', target: 35, currentValue: 0 },
      { id: 'party-bookings', label: 'Party Bookings/Month', format: 'number', target: 12, currentValue: 0 },
    ],
    integrations: [
      { id: 'toast', name: 'Toast POS', category: 'pos', priority: 'essential', setupTime: 20 },
      { id: 'yelp', name: 'Yelp', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'party-confirm', name: 'Party Booking Confirmation', subject: '🎤 Your party at {{business_name}} is booked!', body: "Hey {{customer_name}},\n\nGet ready to sing your heart out! Your party is confirmed:\n\n📅 {{party_date}} at {{party_time}}\n🚪 {{room_or_area}}\n👥 {{guest_count}} guests\n🎶 {{package_details}}\n\nPro tip: Send your guests our song list ahead of time so they can pick their go-to karaoke jams!\n\nSee you on stage!\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'birthday-offer', name: 'Birthday Special', body: '🎂🎤 Happy Birthday, {{customer_name}}! Celebrate at {{business_name}} — birthday stars get a FREE hour in a private room! Book: {{phone}}', trigger: 'automated' },
      { id: 'tonight-promo', name: 'Tonight\'s Theme', body: "🎵 Tonight at {{business_name}}: {{theme_night}}! {{drink_special}}. Doors open at {{open_time}}. Grab the mic! 🎤", trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['events', 'karaoke', 'bar', 'nightlife', 'entertainment'],
      requiredPlan: 'pro',
    },
  },
];
