import type { ProTemplate } from '../schema';

export const retailTemplates: ProTemplate[] = [
  {
    id: 'clothing-boutique',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'clothing-boutique',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Curated styles that make you feel like you',
      description: 'A local clothing boutique offering carefully selected fashion, personalized styling advice, and a shopping experience that makes every customer feel special.',
      primaryColor: '#8B4585',
      secondaryColor: '#F5E6F0',
      tone: 'warm, stylish, encouraging',
      personality: 'Like a fashionable best friend who always knows what looks great on you and never judges your budget.',
    },
    demoExperience: {
      headline: 'Your Boutique, Running Like a Fashion House',
      subheadline: 'Mouse handles your appointments, new arrivals buzz, and customer styling — so you can focus on curating.',
      heroImage: 'boutique-storefront-warm-lighting',
      socialProof: 'Boutiques using Mouse see 40% more personal shopping appointments booked.',
      ctaText: 'See Your Boutique on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your boutique business advisor',
      greeting: "Hey there, fashion boss! Let's make your boutique the go-to spot in town. I'll handle the behind-the-scenes stuff so you can do what you love — help people look amazing.",
      sampleAdvice: [
        'Your top-selling items this month are all in earth tones — consider featuring a fall collection display up front.',
        "You have 12 customers who haven't visited in 60 days. Want me to send them a 'We miss you' text with a sneak peek at new arrivals?",
        'Saturday afternoons are your busiest time. Consider adding a second staff member from 1-5 PM.',
      ],
      knowledgeDomains: ['retail merchandising', 'fashion trends', 'inventory management', 'customer loyalty', 'visual merchandising', 'seasonal buying'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, the virtual assistant. I can help you with store hours, new arrivals, personal shopping appointments, or anything else. What can I help you with?",
      personality: "Friendly and fashion-forward. Uses approachable language. Gets excited about new collections and styling. Never pushy — helps customers feel welcome whether they're browsing or buying.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. We'd love to see you — there's always something new on the racks!" },
        { question: 'Do you carry plus sizes?', answer: "We carry sizes {{size_range}}. We believe great style comes in every size and we'd love to help you find something perfect." },
        { question: 'Can I book a personal shopping appointment?', answer: "Absolutely! Our stylists love helping customers find their perfect look. I can book you a free 30-minute session. When works best for you?" },
        { question: 'Do you do alterations?', answer: "{{alterations_policy}}. We want everything to fit you perfectly!" },
        { question: 'What brands do you carry?', answer: "We carry a curated mix including {{brands}}. We're always bringing in new finds too — stop by to see what's fresh!" },
        { question: 'Do you have a return policy?', answer: "Yes! {{return_policy}}. We want you to love everything you take home." },
        { question: 'Do you offer gift cards?', answer: "We sure do! Gift cards are available in any amount starting at $25. They make the perfect gift when you're not sure of someone's style or size." },
      ],
      transferTriggers: [
        'Customer wants to place a large or special order',
        'Questions about wholesale or consignment',
        'Complaint about a purchase',
        'Request for private shopping event',
      ],
      escalationRules: {
        urgentKeywords: ['complaint', 'damaged', 'wrong item', 'overcharged'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed right now but we open at {{next_open}}. Leave a message and we'll get back to you, or text us anytime!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Boutique Info',
          description: "Let's get your store set up so customers can find you.",
          fields: [
            { id: 'business_name', label: 'Boutique Name', type: 'text', required: true, placeholder: 'e.g., Bella Rose Boutique' },
            { id: 'address', label: 'Store Address', type: 'text', required: true, placeholder: '123 Main Street, Suite A' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 10am-6pm, Sun 12-5pm' },
          ],
        },
        {
          id: 'style',
          title: 'Your Style & Offerings',
          description: 'Tell us about what makes your boutique special.',
          fields: [
            { id: 'style_focus', label: 'Style Focus', type: 'multiselect', required: true, options: ['Casual', 'Business Casual', 'Formal', 'Bohemian', 'Streetwear', 'Vintage', 'Athleisure', 'Resort Wear'] },
            { id: 'size_range', label: 'Size Range', type: 'text', required: true, placeholder: 'e.g., XS-3XL or 0-24' },
            { id: 'brands', label: 'Featured Brands', type: 'text', required: false, placeholder: 'e.g., Free People, Anthropologie, local designers' },
            { id: 'price_range', label: 'Price Range', type: 'select', required: true, options: ['Budget-Friendly ($10-$50)', 'Mid-Range ($30-$150)', 'Premium ($75-$300)', 'Luxury ($200+)'] },
          ],
        },
        {
          id: 'services',
          title: 'Extra Services',
          description: 'What special services do you offer?',
          fields: [
            { id: 'personal_shopping', label: 'Offer Personal Shopping Appointments?', type: 'toggle', required: false, defaultValue: true },
            { id: 'alterations_policy', label: 'Alterations Policy', type: 'text', required: false, placeholder: 'e.g., We offer in-house alterations starting at $15' },
            { id: 'return_policy', label: 'Return Policy', type: 'text', required: true, placeholder: 'e.g., Full refund within 14 days with tags attached' },
          ],
        },
        {
          id: 'marketing',
          title: 'Stay Connected',
          description: 'How do you want to keep customers coming back?',
          fields: [
            { id: 'loyalty_program', label: 'Have a Loyalty Program?', type: 'toggle', required: false, defaultValue: false },
            { id: 'social_media', label: 'Instagram Handle', type: 'text', required: false, placeholder: '@yourboutique' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'appointments-today', type: 'list', title: "Today's Styling Appointments", dataSource: 'calendar_today', refreshInterval: 600 },
      { id: 'top-sellers', type: 'chart', title: 'Top Sellers This Week', dataSource: 'inventory_top_items', refreshInterval: 3600 },
      { id: 'low-stock', type: 'alert', title: 'Low Stock Alerts', dataSource: 'inventory_low_stock', refreshInterval: 1800 },
      { id: 'customer-messages', type: 'list', title: 'Customer Messages', dataSource: 'messages_unread', refreshInterval: 120 },
    ],
    sampleTasks: [
      { id: 'new-arrival-blast', title: 'Send New Arrivals Text', description: 'Text your VIP list about new inventory that just hit the floor', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'reorder-bestseller', title: 'Reorder Best-Selling Item', description: 'Check stock levels and reorder your top seller before it runs out', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'birthday-discount', title: 'Send Birthday Discounts', description: 'Automatically send a birthday discount to customers this month', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'seasonal-markdown', title: 'Create Seasonal Markdowns', description: 'Mark down end-of-season inventory to make room for new collections', difficulty: 'needs-approval', estimatedMinutes: 10 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 25000, currentValue: 0 },
      { id: 'avg-transaction', label: 'Average Transaction', format: 'currency', target: 85, currentValue: 0 },
      { id: 'return-customers', label: 'Repeat Customer Rate', format: 'percentage', target: 40, currentValue: 0 },
      { id: 'inventory-turnover', label: 'Inventory Turnover', format: 'number', target: 4, currentValue: 0 },
    ],
    integrations: [
      { id: 'shopify', name: 'Shopify POS', category: 'pos', priority: 'essential', setupTime: 15 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram Shopping', category: 'social', priority: 'recommended', setupTime: 20 },
      { id: 'mailchimp', name: 'Mailchimp', category: 'email', priority: 'recommended', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'new-arrivals', name: 'New Arrivals Announcement', subject: 'Just In! New styles at {{business_name}} ✨', body: "Hi {{customer_name}},\n\nWe just unpacked some gorgeous new pieces and you're going to love them.\n\nStop by {{business_name}} this week to see what's new — or book a personal shopping session and we'll have picks ready for you.\n\n{{address}}\n{{hours}}\n\nSee you soon!", trigger: 'manual' },
      { id: 'birthday', name: 'Birthday Discount', subject: 'Happy Birthday! A gift from {{business_name}} 🎂', body: "Happy Birthday, {{customer_name}}!\n\nTo celebrate your special day, here's 20% off your next visit to {{business_name}}. Treat yourself — you deserve it!\n\nUse code: BDAY20\nValid for 30 days.\n\nCheers,\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'new-arrivals-sms', name: 'New Arrivals Text', body: '✨ New styles just dropped at {{business_name}}! Stop by to see what\'s fresh or book a styling appt: {{booking_link}}', trigger: 'manual' },
      { id: 'sale-alert', name: 'Sale Alert', body: '🛍️ {{business_name}} sale starts tomorrow! Up to 40% off select styles. Come early for the best picks!', trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'clothing', 'fashion', 'boutique'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'jewelry-store',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'jewelry-store',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Pieces as unique as the moments they celebrate',
      description: 'A local jewelry store offering fine jewelry, custom designs, repairs, and the kind of personal attention that makes every purchase feel like an occasion.',
      primaryColor: '#1A3A5C',
      secondaryColor: '#F5F0E8',
      tone: 'elegant, trustworthy, warm',
      personality: 'Like a knowledgeable friend who helps you find the perfect piece without the intimidation of a fancy store.',
    },
    demoExperience: {
      headline: 'Your Jewelry Store, Polished and Organized',
      subheadline: 'Mouse handles appointments, repair tracking, and customer follow-ups — so you can focus on creating beautiful moments.',
      heroImage: 'jewelry-display-elegant-lighting',
      socialProof: 'Jewelry stores using Mouse book 35% more custom design consultations.',
      ctaText: 'See Your Store on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your jewelry business advisor',
      greeting: "Welcome! Let's make your jewelry store shine even brighter. I'll help you track repairs, follow up with customers, and never miss an anniversary reminder.",
      sampleAdvice: [
        "Valentine's Day is 6 weeks out — last year your custom orders peaked 3 weeks before. Time to start promoting custom pieces now.",
        'You have 8 repair jobs that have been ready for pickup for over a week. Want me to send reminder texts?',
        "Engagement ring consultations convert at 70% when you follow up within 24 hours. I'll set up automatic follow-ups.",
      ],
      knowledgeDomains: ['fine jewelry', 'gemology basics', 'repair tracking', 'custom design workflow', 'occasion-based marketing', 'insurance appraisals'],
    },
    aiReceptionist: {
      greeting: "Thank you for calling {{business_name}}! This is Mouse, the virtual assistant. I can help with store hours, repair status, appointments for custom designs or appraisals, and more. How can I help you today?",
      personality: "Warm and professional. Treats every inquiry with care — whether someone is buying a $50 bracelet or a $5,000 engagement ring. Never condescending about budget. Understands that jewelry purchases are emotional.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. We'd love to see you!" },
        { question: 'Do you do repairs?', answer: "Yes! We handle ring sizing, chain repair, stone replacement, prong tightening, and more. Bring your piece in and we'll give you a free estimate." },
        { question: 'How long do repairs take?', answer: "Most repairs take {{repair_timeline}}. We'll give you an exact timeframe when you drop off your piece." },
        { question: 'Do you do custom designs?', answer: "We love creating custom pieces! Book a free design consultation and we'll work with you to create something truly one-of-a-kind. The process typically takes {{custom_timeline}}." },
        { question: 'Do you buy gold or diamonds?', answer: "{{buy_policy}}. Bring your items in for a free, no-obligation evaluation." },
        { question: 'Do you do appraisals?', answer: "Yes, we offer jewelry appraisals for insurance purposes. {{appraisal_policy}}. Appointments are recommended." },
        { question: 'Do you offer financing?', answer: "{{financing_policy}}. We want to help you find something you love within your comfort zone." },
      ],
      transferTriggers: [
        'Customer asking about high-value purchase over $2,000',
        'Custom engagement ring consultation',
        'Insurance claim or appraisal dispute',
        'Complaint about repair quality',
      ],
      escalationRules: {
        urgentKeywords: ['lost stone', 'broken', 'engagement ring', 'proposal', 'insurance claim'],
        afterHoursMessage: "Thank you for calling {{business_name}}. We're closed now but open again at {{next_open}}. For repair status, text us your name. For everything else, leave a message and we'll call you back!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Store Info',
          description: "Let's set up your jewelry store.",
          fields: [
            { id: 'business_name', label: 'Store Name', type: 'text', required: true, placeholder: 'e.g., Diamond Creek Jewelers' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 10am-6pm' },
            { id: 'address', label: 'Store Address', type: 'text', required: true },
          ],
        },
        {
          id: 'services',
          title: 'What You Offer',
          description: 'Tell us about your services so we can inform customers.',
          fields: [
            { id: 'services_offered', label: 'Services', type: 'multiselect', required: true, options: ['Repairs', 'Custom Design', 'Appraisals', 'Engraving', 'Watch Repair', 'Buy Gold/Diamonds', 'Ear Piercing'] },
            { id: 'repair_timeline', label: 'Typical Repair Time', type: 'text', required: true, placeholder: 'e.g., 3-5 business days' },
            { id: 'custom_timeline', label: 'Custom Design Timeline', type: 'text', required: false, placeholder: 'e.g., 4-6 weeks' },
          ],
        },
        {
          id: 'policies',
          title: 'Your Policies',
          description: 'Help us answer customer questions accurately.',
          fields: [
            { id: 'financing_policy', label: 'Financing Options', type: 'text', required: false, placeholder: 'e.g., We offer 12-month no-interest financing on purchases over $500' },
            { id: 'buy_policy', label: 'Gold/Diamond Buying Policy', type: 'text', required: false, placeholder: 'e.g., Yes, we buy gold, silver, and diamonds at competitive prices' },
            { id: 'appraisal_policy', label: 'Appraisal Details', type: 'text', required: false, placeholder: 'e.g., $75 per item, certified appraisals' },
          ],
        },
        {
          id: 'marketing',
          title: 'Stay Connected',
          description: 'How should we help you stay in touch with customers?',
          fields: [
            { id: 'anniversary_reminders', label: 'Send Anniversary/Birthday Reminders?', type: 'toggle', required: false, defaultValue: true },
            { id: 'social_media', label: 'Instagram Handle', type: 'text', required: false, placeholder: '@yourstore' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'repair-tracker', type: 'list', title: 'Active Repairs', dataSource: 'repairs_active', refreshInterval: 600 },
      { id: 'appointments', type: 'list', title: 'Upcoming Appointments', dataSource: 'calendar_upcoming', refreshInterval: 600 },
      { id: 'ready-pickup', type: 'alert', title: 'Ready for Pickup', dataSource: 'repairs_ready', refreshInterval: 900 },
      { id: 'anniversaries', type: 'list', title: 'Upcoming Customer Anniversaries', dataSource: 'customer_anniversaries', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'pickup-reminder', title: 'Send Repair Pickup Reminders', description: 'Text customers whose repairs have been ready for 3+ days', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'anniversary-outreach', title: 'Anniversary Reminders', description: 'Send personalized messages to customers with upcoming anniversaries', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'appraisal-followup', title: 'Follow Up on Appraisals', description: 'Check in with customers who got appraisals but may need insurance updates', difficulty: 'needs-approval', estimatedMinutes: 5 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 40000, currentValue: 0 },
      { id: 'repairs-completed', label: 'Repairs Completed', format: 'number', target: 30, currentValue: 0 },
      { id: 'avg-ticket', label: 'Average Sale', format: 'currency', target: 250, currentValue: 0 },
      { id: 'custom-orders', label: 'Custom Orders This Month', format: 'number', target: 5, currentValue: 0 },
    ],
    integrations: [
      { id: 'the-edge', name: 'The Edge POS', category: 'pos', priority: 'recommended', setupTime: 20 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'repair-ready', name: 'Repair Ready for Pickup', subject: 'Your jewelry is ready at {{business_name}}!', body: "Hi {{customer_name}},\n\nGreat news — your {{repair_type}} is finished and ready for pickup!\n\nWe're open {{hours}}. Can't wait for you to see it.\n\n{{business_name}}\n{{address}}", trigger: 'automated' },
      { id: 'anniversary', name: 'Anniversary Reminder', subject: "A special anniversary is coming up! 💎", body: "Hi {{customer_name}},\n\nYour anniversary is coming up on {{anniversary_date}} — and we'd love to help you celebrate with something special.\n\nStop by or call us to explore gift ideas. We know what they love!\n\n{{business_name}}\n{{phone}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'repair-ready-sms', name: 'Repair Ready Text', body: 'Hi {{customer_name}}! Your jewelry repair at {{business_name}} is ready for pickup. We\'re open {{hours}}. See you soon!', trigger: 'automated' },
      { id: 'anniversary-sms', name: 'Anniversary Reminder', body: "Hey {{customer_name}}, your anniversary is coming up! Stop by {{business_name}} — we'll help you find the perfect surprise. 💎", trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'jewelry', 'fine-jewelry', 'repairs'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'gift-shop',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'gift-shop',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Thoughtful gifts for every occasion',
      description: 'A local gift shop offering unique, curated gifts, cards, and specialty items for every occasion — with the personal touch that online retailers can never match.',
      primaryColor: '#E85D75',
      secondaryColor: '#FFF5F7',
      tone: 'cheerful, helpful, creative',
      personality: 'Like the friend who always finds the perfect gift — thoughtful, creative, and full of great ideas.',
    },
    demoExperience: {
      headline: 'Your Gift Shop, Wrapped Up Nicely',
      subheadline: 'Mouse handles inventory alerts, gift registry, and customer follow-ups so you can focus on finding the perfect products.',
      heroImage: 'gift-shop-colorful-display',
      socialProof: 'Gift shops using Mouse see 30% more repeat customers through automated follow-ups.',
      ctaText: 'See Your Shop on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your gift shop business advisor',
      greeting: "Hey there! Let's make your gift shop the first place people think of when they need something special. I'll handle the details so you can focus on curating amazing finds.",
      sampleAdvice: [
        "Mother's Day is 8 weeks out — your biggest sales week last year. Time to start ordering specialty items and promoting gift wrapping.",
        'Your candle section outsells everything else 3-to-1. Consider expanding that area and adding a candle-of-the-month feature.',
        "You haven't posted on social media in 2 weeks. Want me to draft a post featuring your newest arrivals?",
      ],
      knowledgeDomains: ['gift retail', 'seasonal merchandising', 'gift wrapping', 'occasion marketing', 'vendor relations', 'impulse purchase optimization'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with store hours, gift ideas, gift wrapping, or anything else. What are you looking for today?",
      personality: "Enthusiastic and creative. Loves helping people find the right gift. Asks great questions to narrow down options. Makes customers feel like their gift-giving is going to be a hit.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Come on in and browse — there's always something new!" },
        { question: 'Do you gift wrap?', answer: "Absolutely! {{gift_wrap_policy}}. We make everything look beautiful." },
        { question: 'Do you ship gifts?', answer: "{{shipping_policy}}. We can even include a handwritten card!" },
        { question: 'Do you have gift cards?', answer: "Yes! Gift cards start at $10 and are perfect when you want them to pick their own favorite thing." },
        { question: 'Can you help me pick a gift?', answer: "That's our favorite thing to do! Tell me a little about the person — their age, interests, and the occasion — and we'll point you in the right direction." },
        { question: 'Do you carry local products?', answer: "We love supporting local! We carry products from {{local_vendors}}. It's a great way to give a gift that's truly unique to our area." },
      ],
      transferTriggers: [
        'Corporate or bulk gift orders',
        'Custom gift basket requests',
        'Wholesale or vendor inquiries',
        'Complaint about a product',
      ],
      escalationRules: {
        urgentKeywords: ['bulk order', 'corporate gifts', 'broken', 'complaint', 'wrong item'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed right now but open again at {{next_open}}. Leave us a message or shop online at {{website}}!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Shop Info',
          description: "Let's get your gift shop set up.",
          fields: [
            { id: 'business_name', label: 'Shop Name', type: 'text', required: true, placeholder: 'e.g., Treasure Trove Gifts' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 10am-7pm, Sun 11am-5pm' },
            { id: 'address', label: 'Store Address', type: 'text', required: true },
          ],
        },
        {
          id: 'offerings',
          title: 'What You Carry',
          description: 'Help us understand your product mix.',
          fields: [
            { id: 'categories', label: 'Product Categories', type: 'multiselect', required: true, options: ['Candles', 'Home Decor', 'Cards & Stationery', 'Toys & Games', 'Jewelry & Accessories', 'Bath & Body', 'Food & Treats', 'Books', 'Local Artisan Goods', 'Baby Gifts', 'Pet Gifts'] },
            { id: 'local_vendors', label: 'Local Brands You Carry', type: 'text', required: false, placeholder: 'e.g., Honeybee Candles, River City Pottery' },
            { id: 'price_range', label: 'Typical Price Range', type: 'text', required: true, placeholder: 'e.g., $5 - $150' },
          ],
        },
        {
          id: 'services',
          title: 'Extra Services',
          description: 'What makes your shop special?',
          fields: [
            { id: 'gift_wrap_policy', label: 'Gift Wrapping Policy', type: 'text', required: true, placeholder: 'e.g., Free gift wrapping on all purchases!' },
            { id: 'shipping_policy', label: 'Shipping Policy', type: 'text', required: false, placeholder: 'e.g., We ship anywhere in the US — $5 flat rate' },
            { id: 'custom_baskets', label: 'Offer Custom Gift Baskets?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
        {
          id: 'online',
          title: 'Online Presence',
          description: 'Help customers find you online.',
          fields: [
            { id: 'website', label: 'Website', type: 'url', required: false },
            { id: 'social_media', label: 'Instagram Handle', type: 'text', required: false, placeholder: '@yourgiftshop' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'top-categories', type: 'chart', title: 'Top Categories This Week', dataSource: 'sales_by_category', refreshInterval: 3600 },
      { id: 'low-stock', type: 'alert', title: 'Low Stock Items', dataSource: 'inventory_low_stock', refreshInterval: 1800 },
      { id: 'messages', type: 'list', title: 'Customer Messages', dataSource: 'messages_unread', refreshInterval: 120 },
    ],
    sampleTasks: [
      { id: 'restock-alert', title: 'Check Restock Needs', description: 'Review items running low and create purchase orders', difficulty: 'needs-approval', estimatedMinutes: 10 },
      { id: 'holiday-promo', title: 'Send Holiday Promotion', description: 'Text your customer list about upcoming holiday gift ideas', difficulty: 'needs-approval', estimatedMinutes: 3 },
      { id: 'new-product-post', title: 'Post New Arrivals', description: 'Share photos of new products on social media', difficulty: 'needs-approval', estimatedMinutes: 5 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 15000, currentValue: 0 },
      { id: 'avg-transaction', label: 'Average Transaction', format: 'currency', target: 35, currentValue: 0 },
      { id: 'items-per-sale', label: 'Items per Sale', format: 'number', target: 3, currentValue: 0 },
      { id: 'repeat-rate', label: 'Repeat Customer Rate', format: 'percentage', target: 35, currentValue: 0 },
    ],
    integrations: [
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'shopify', name: 'Shopify', category: 'ecommerce', priority: 'recommended', setupTime: 20 },
      { id: 'instagram', name: 'Instagram Shopping', category: 'social', priority: 'recommended', setupTime: 15 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'holiday-guide', name: 'Holiday Gift Guide', subject: '🎁 Your Holiday Gift Guide from {{business_name}}', body: "Hi {{customer_name}},\n\nNot sure what to get? We've got you covered!\n\nStop by {{business_name}} and let us help you find the perfect gift. We'll even wrap it for you.\n\n{{address}}\n{{hours}}\n\nHappy gifting!\n{{business_name}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'new-arrivals', name: 'New Arrivals', body: "🎁 New goodies just arrived at {{business_name}}! Stop by to see what's new — perfect for upcoming birthdays & events!", trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'gift-shop', 'gifts', 'specialty'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'pet-store',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'pet-store',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Everything your pet needs, with people who care',
      description: 'A local pet store offering premium food, supplies, treats, and expert advice from people who genuinely love animals.',
      primaryColor: '#4CAF50',
      secondaryColor: '#F1F8E9',
      tone: 'friendly, caring, knowledgeable',
      personality: 'Like a fellow pet parent who happens to know everything about animal nutrition, toys, and care — always happy to help.',
    },
    demoExperience: {
      headline: 'Your Pet Store, Fetching More Customers',
      subheadline: 'Mouse handles food subscription reminders, loyalty tracking, and customer questions — so you can focus on the animals.',
      heroImage: 'pet-store-happy-dog-shopping',
      socialProof: 'Pet stores using Mouse see 45% more repeat food purchases through automated reorder reminders.',
      ctaText: 'See Your Store on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your pet store business advisor',
      greeting: "Hey there, fellow animal lover! Let's make your pet store the neighborhood favorite. I'll help you keep customers coming back and their pets happy and healthy.",
      sampleAdvice: [
        '23 customers are due for a food reorder based on their last purchase date. Want me to send them a reminder text?',
        'Your dog treat section has the highest margin in the store. Consider expanding it and adding a treat bar where customers can mix and match.',
        'Yappy Hour events at other pet stores drive 2x weekend traffic. Want to plan one for this month?',
      ],
      knowledgeDomains: ['pet nutrition', 'pet retail', 'subscription models', 'pet events', 'vendor management', 'seasonal pet needs'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with store hours, product questions, food reorders, or anything pet-related. What can I help you with?",
      personality: "Warm and genuinely enthusiastic about pets. Uses pet-friendly language. Asks about the customer's pet by name if known. Never dismissive about pet concerns — understands that pets are family. IMPORTANT: Never give veterinary medical advice. Always refer health questions to a veterinarian.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Leashed and friendly pets are always welcome in the store!" },
        { question: 'Do you carry [specific brand]?', answer: "We carry a great selection of premium brands including {{brands}}. If we don't have something, we can usually special order it within a week." },
        { question: 'Do you do dog grooming?', answer: "{{grooming_policy}}" },
        { question: 'Can I bring my dog in?', answer: "Absolutely! Well-behaved, leashed dogs are always welcome. We even have treats at the counter!" },
        { question: 'Do you sell live animals?', answer: "{{live_animals_policy}}" },
        { question: 'My pet is sick, what should I do?', answer: "I'm sorry to hear that! For any health concerns, please contact your veterinarian right away. If it's an emergency, {{emergency_vet}}. We're not able to give medical advice, but we're here for you." },
        { question: 'Do you offer delivery?', answer: "{{delivery_policy}}" },
      ],
      transferTriggers: [
        'Bulk or wholesale orders',
        'Special diet or prescription food questions',
        'Complaint about a product',
        'Questions about pet adoption events',
      ],
      escalationRules: {
        urgentKeywords: ['sick pet', 'allergic reaction', 'recall', 'poisoned', 'emergency'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed right now but back open at {{next_open}}. For pet emergencies, please call your vet or {{emergency_vet}}.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Store Info',
          description: "Let's get your pet store set up.",
          fields: [
            { id: 'business_name', label: 'Store Name', type: 'text', required: true, placeholder: 'e.g., Paws & Claws Pet Supply' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 9am-7pm, Sun 10am-5pm' },
            { id: 'address', label: 'Store Address', type: 'text', required: true },
          ],
        },
        {
          id: 'products',
          title: 'What You Carry',
          description: 'Tell us about your product selection.',
          fields: [
            { id: 'pet_types', label: 'Pets You Serve', type: 'multiselect', required: true, options: ['Dogs', 'Cats', 'Birds', 'Fish', 'Reptiles', 'Small Animals', 'Horses'] },
            { id: 'brands', label: 'Featured Food Brands', type: 'text', required: false, placeholder: 'e.g., Orijen, Fromm, Stella & Chewy\'s' },
            { id: 'live_animals_policy', label: 'Live Animals Policy', type: 'text', required: true, placeholder: 'e.g., We carry freshwater fish and small animals. We partner with local rescues for dog/cat adoption events.' },
          ],
        },
        {
          id: 'services',
          title: 'Services',
          description: 'What extra services do you offer?',
          fields: [
            { id: 'grooming_policy', label: 'Grooming Services', type: 'text', required: false, placeholder: 'e.g., Yes! Full grooming services by appointment. Call to book.' },
            { id: 'delivery_policy', label: 'Delivery Options', type: 'text', required: false, placeholder: 'e.g., Free local delivery on orders over $50' },
            { id: 'emergency_vet', label: 'Local Emergency Vet', type: 'text', required: true, placeholder: 'e.g., Animal Emergency Clinic at 555-0199' },
          ],
        },
        {
          id: 'loyalty',
          title: 'Keep Them Coming Back',
          description: 'Set up customer retention features.',
          fields: [
            { id: 'loyalty_program', label: 'Loyalty Program Details', type: 'text', required: false, placeholder: 'e.g., Buy 10 bags of food, get the 11th free' },
            { id: 'reorder_reminders', label: 'Send Food Reorder Reminders?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'reorder-due', type: 'list', title: 'Customers Due for Reorder', dataSource: 'customers_reorder_due', refreshInterval: 86400 },
      { id: 'top-products', type: 'chart', title: 'Top Sellers This Week', dataSource: 'inventory_top_items', refreshInterval: 3600 },
      { id: 'low-stock', type: 'alert', title: 'Low Stock Alerts', dataSource: 'inventory_low_stock', refreshInterval: 1800 },
    ],
    sampleTasks: [
      { id: 'reorder-reminders', title: 'Send Reorder Reminders', description: 'Text customers who are due to reorder pet food based on purchase history', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'adoption-event', title: 'Promote Adoption Event', description: 'Send announcement about upcoming pet adoption event', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'loyalty-update', title: 'Update Loyalty Points', description: 'Notify customers who are close to earning a free bag of food', difficulty: 'automatic', estimatedMinutes: 2 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 20000, currentValue: 0 },
      { id: 'reorder-rate', label: 'Food Reorder Rate', format: 'percentage', target: 60, currentValue: 0 },
      { id: 'avg-transaction', label: 'Average Transaction', format: 'currency', target: 45, currentValue: 0 },
      { id: 'new-customers', label: 'New Customers/Month', format: 'number', target: 40, currentValue: 0 },
    ],
    integrations: [
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'facebook', name: 'Facebook', category: 'social', priority: 'recommended', setupTime: 10 },
      { id: 'astro-loyalty', name: 'Astro Loyalty', category: 'loyalty', priority: 'recommended', setupTime: 15 },
    ],
    emailTemplates: [
      { id: 'reorder', name: 'Food Reorder Reminder', subject: "Time to restock {{pet_name}}'s food! 🐾", body: "Hi {{customer_name}},\n\nBased on your last purchase, {{pet_name}} is probably running low on {{food_brand}}!\n\nStop by {{business_name}} to grab another bag — or call us and we'll have it ready for you.\n\n{{phone}}\n{{hours}}\n\nGive {{pet_name}} a treat from us! 🐕", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'reorder-sms', name: 'Reorder Reminder', body: "🐾 Hey {{customer_name}}! {{pet_name}} is probably running low on food. Stop by {{business_name}} or call {{phone}} and we'll have it ready!", trigger: 'automated' },
      { id: 'adoption-event-sms', name: 'Adoption Event', body: '🐶 Adoption event this {{event_date}} at {{business_name}}! Come meet adoptable pets from local rescues. Bring the whole family!', trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'pet-store', 'pets', 'pet-supplies'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'hardware-store',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'hardware-store',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Your neighborhood knows how — since {{year_founded}}',
      description: 'A local hardware store where you get expert advice from people who actually know how to fix things, plus the parts and tools to get it done right.',
      primaryColor: '#D32F2F',
      secondaryColor: '#FFF3E0',
      tone: 'practical, knowledgeable, neighborly',
      personality: 'Like the handy neighbor who always knows the right tool, the right part, and the right way to do a project — and is happy to show you.',
    },
    demoExperience: {
      headline: 'Your Hardware Store, Built to Last',
      subheadline: 'Mouse handles customer questions, project advice requests, and special orders — so you can focus on being the expert your community relies on.',
      heroImage: 'hardware-store-organized-aisles',
      socialProof: 'Independent hardware stores using Mouse see 25% more special orders through automated follow-ups.',
      ctaText: 'See Your Store on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your hardware store business advisor',
      greeting: "Hey there! Let's make your hardware store the place everyone turns to first — before they even think of the big box stores. I'll help you shine where they can't: expert advice, personal service, and community trust.",
      sampleAdvice: [
        'Spring is 4 weeks out — time to build your garden center and lawn care displays. Last year your fertilizer and seed sales spiked 300% in March.',
        'You have 6 pending special orders with no follow-up. Want me to text those customers with status updates?',
        'Saturday morning DIY workshops drive 40% more weekend sales at similar stores. Want to plan one?',
      ],
      knowledgeDomains: ['hardware retail', 'seasonal merchandising', 'DIY project advice', 'special orders', 'tool knowledge', 'paint matching'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with store hours, check if we have something in stock, or connect you with our experts. What do you need?",
      personality: "Straightforward and helpful. No-nonsense but friendly. Understands that customers often have a project in mind and need quick, practical answers. Speaks in plain language about tools and materials.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Come on in!" },
        { question: 'Do you carry [specific item]?', answer: "We carry a wide range of {{departments}}. For specific items, I'd recommend calling during business hours so one of our team members can check for you, or stop by — if we don't have it, we can usually special order it." },
        { question: 'Do you do key cutting?', answer: "{{key_cutting_policy}}" },
        { question: 'Do you mix paint?', answer: "{{paint_policy}}" },
        { question: 'Can you help me figure out what I need for my project?', answer: "That's what we do best! Stop by with your project details and our team will walk you through everything you need. We love helping DIYers get it right the first time." },
        { question: 'Do you deliver?', answer: "{{delivery_policy}}" },
        { question: 'Do you rent tools?', answer: "{{tool_rental_policy}}" },
      ],
      transferTriggers: [
        'Large contractor or commercial orders',
        'Special order status inquiries',
        'Detailed project consulting needs',
        'Complaint about a product',
      ],
      escalationRules: {
        urgentKeywords: ['emergency', 'flood', 'pipe burst', 'no heat', 'power out'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For plumbing or heating emergencies, we recommend calling a licensed professional — we can point you to one when we open.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Store Info',
          description: "Let's get your hardware store set up.",
          fields: [
            { id: 'business_name', label: 'Store Name', type: 'text', required: true, placeholder: "e.g., Johnson's Hardware" },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 7am-6pm, Sun 9am-4pm' },
            { id: 'year_founded', label: 'Year Founded', type: 'text', required: false, placeholder: 'e.g., 1985' },
          ],
        },
        {
          id: 'departments',
          title: 'Your Departments',
          description: 'What areas does your store cover?',
          fields: [
            { id: 'departments', label: 'Departments', type: 'multiselect', required: true, options: ['Plumbing', 'Electrical', 'Paint', 'Tools', 'Lawn & Garden', 'Lumber', 'Fasteners', 'Cleaning', 'Automotive', 'Sporting Goods'] },
            { id: 'key_cutting_policy', label: 'Key Cutting', type: 'text', required: false, placeholder: 'e.g., Yes! Key cutting while you wait, starting at $2' },
            { id: 'paint_policy', label: 'Paint Services', type: 'text', required: false, placeholder: 'e.g., Full paint mixing and color matching with Benjamin Moore and Clark+Kensington' },
          ],
        },
        {
          id: 'services',
          title: 'Extra Services',
          description: 'What sets you apart from the big box stores?',
          fields: [
            { id: 'delivery_policy', label: 'Delivery Options', type: 'text', required: false, placeholder: 'e.g., Free local delivery on orders over $75' },
            { id: 'tool_rental_policy', label: 'Tool Rental', type: 'text', required: false, placeholder: 'e.g., We rent power tools by the day — ask in store for rates' },
            { id: 'special_orders', label: 'Special Order Capability?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
        {
          id: 'community',
          title: 'Community Connection',
          description: 'How do you connect with your community?',
          fields: [
            { id: 'workshops', label: 'Offer DIY Workshops?', type: 'toggle', required: false, defaultValue: false },
            { id: 'contractor_accounts', label: 'Contractor Accounts Available?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'special-orders', type: 'list', title: 'Pending Special Orders', dataSource: 'orders_special_pending', refreshInterval: 1800 },
      { id: 'top-departments', type: 'chart', title: 'Sales by Department', dataSource: 'sales_by_department', refreshInterval: 3600 },
      { id: 'messages', type: 'list', title: 'Customer Questions', dataSource: 'messages_unread', refreshInterval: 120 },
    ],
    sampleTasks: [
      { id: 'special-order-update', title: 'Update Special Orders', description: 'Check status of pending special orders and notify customers when ready', difficulty: 'needs-approval', estimatedMinutes: 10 },
      { id: 'seasonal-display', title: 'Plan Seasonal Display', description: 'Get recommendations for seasonal product displays based on upcoming weather and holidays', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'contractor-outreach', title: 'Contractor Outreach', description: 'Send monthly specials to your contractor account holders', difficulty: 'needs-approval', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 45000, currentValue: 0 },
      { id: 'avg-transaction', label: 'Average Transaction', format: 'currency', target: 38, currentValue: 0 },
      { id: 'special-orders', label: 'Special Orders Filled', format: 'number', target: 20, currentValue: 0 },
      { id: 'repeat-rate', label: 'Repeat Customer Rate', format: 'percentage', target: 50, currentValue: 0 },
    ],
    integrations: [
      { id: 'epicor', name: 'Epicor Eagle', category: 'pos', priority: 'recommended', setupTime: 30 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'special-order-ready', name: 'Special Order Ready', subject: 'Your special order is in at {{business_name}}!', body: "Hi {{customer_name}},\n\nGreat news — your {{item_description}} has arrived and is ready for pickup!\n\nWe're open {{hours}}. See you soon!\n\n{{business_name}}\n{{phone}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'special-order-sms', name: 'Special Order Ready', body: 'Hi {{customer_name}}! Your special order at {{business_name}} is ready for pickup. We\'re open {{hours}}.', trigger: 'automated' },
      { id: 'seasonal-sale', name: 'Seasonal Sale', body: '🔧 Spring sale at {{business_name}}! 20% off lawn & garden this weekend. Stop by — {{address}}', trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'hardware', 'home-improvement', 'tools'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'florist',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'florist',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Fresh blooms and heartfelt arrangements',
      description: 'A local florist creating beautiful arrangements for every occasion — from everyday joy to life\'s biggest moments.',
      primaryColor: '#E91E63',
      secondaryColor: '#FCE4EC',
      tone: 'warm, creative, romantic',
      personality: 'Like a talented artist friend who speaks the language of flowers and always knows how to make someone\'s day.',
    },
    demoExperience: {
      headline: 'Your Flower Shop, In Full Bloom',
      subheadline: 'Mouse handles orders, delivery coordination, and event inquiries — so you can focus on creating beautiful arrangements.',
      heroImage: 'florist-colorful-bouquets-shop',
      socialProof: 'Florists using Mouse see 50% more same-day delivery orders through after-hours booking.',
      ctaText: 'See Your Shop on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your floral business advisor',
      greeting: "Hey there, flower boss! Let's grow your business together. I'll handle the orders, reminders, and logistics so you can do what you love — make people happy with flowers.",
      sampleAdvice: [
        "Valentine's Day is 3 weeks out. Last year you sold 200 arrangements. Time to pre-order roses and hire temp delivery drivers.",
        'You have 15 customers with anniversaries this month. Want me to send them a reminder that flowers make the perfect surprise?',
        'Your sympathy arrangements have a 90% reorder rate — those families come back. Consider a sympathy follow-up card 30 days later.',
      ],
      knowledgeDomains: ['floral design', 'flower sourcing', 'delivery logistics', 'event florals', 'seasonal availability', 'occasion marketing'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help you place an order, check delivery availability, or answer questions about arrangements. What can I help with?",
      personality: "Warm and expressive. Understands that flowers are emotional — they celebrate love, comfort grief, and mark milestones. Treats every order with care, whether it's a $30 bouquet or a $3,000 wedding.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Walk-ins are always welcome!" },
        { question: 'Do you deliver?', answer: "Yes! We deliver to {{delivery_area}}. Same-day delivery is available if you order before {{same_day_cutoff}}." },
        { question: 'How much do arrangements cost?', answer: "Our arrangements start at {{starting_price}}. We have options for every budget and can customize to your needs." },
        { question: 'Can I order flowers for a funeral?', answer: "Of course. We create beautiful sympathy arrangements with care and sensitivity. We can deliver directly to the funeral home. Just let us know the name and service time." },
        { question: 'Do you do wedding flowers?', answer: "We love doing weddings! We offer free consultations to discuss your vision, flowers, and budget. Want me to schedule one for you?" },
        { question: 'Can I get same-day delivery?', answer: "Yes, as long as you order before {{same_day_cutoff}}. After that, we can arrange delivery for the next business day." },
        { question: 'Do you have plants too?', answer: "{{plants_policy}}" },
      ],
      transferTriggers: [
        'Wedding consultation request',
        'Large event or corporate account',
        'Same-day rush order',
        'Complaint about delivery or arrangement',
      ],
      escalationRules: {
        urgentKeywords: ['funeral', 'death', 'emergency', 'same-day', 'today', 'rush', 'hospital'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For same-day orders, call when we open before {{same_day_cutoff}}. You can also order online at {{website}} anytime.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Shop Info',
          description: "Let's set up your flower shop.",
          fields: [
            { id: 'business_name', label: 'Shop Name', type: 'text', required: true, placeholder: 'e.g., Petals & Posies' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Fri 8am-6pm, Sat 8am-4pm' },
            { id: 'address', label: 'Shop Address', type: 'text', required: true },
          ],
        },
        {
          id: 'delivery',
          title: 'Delivery Details',
          description: 'Tell us about your delivery service.',
          fields: [
            { id: 'delivery_area', label: 'Delivery Area', type: 'text', required: true, placeholder: 'e.g., within 20 miles of downtown' },
            { id: 'same_day_cutoff', label: 'Same-Day Order Cutoff', type: 'text', required: true, placeholder: 'e.g., 1:00 PM' },
            { id: 'delivery_fee', label: 'Delivery Fee', type: 'text', required: true, placeholder: 'e.g., $12.99 local delivery' },
            { id: 'starting_price', label: 'Starting Arrangement Price', type: 'text', required: true, placeholder: 'e.g., $35' },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What special services do you offer?',
          fields: [
            { id: 'weddings', label: 'Do Wedding Florals?', type: 'toggle', required: false, defaultValue: true },
            { id: 'events', label: 'Do Corporate/Event Florals?', type: 'toggle', required: false, defaultValue: true },
            { id: 'plants_policy', label: 'Plants & Non-Floral Items', type: 'text', required: false, placeholder: 'e.g., Yes! We carry houseplants, succulents, and gift items' },
          ],
        },
        {
          id: 'online',
          title: 'Online Orders',
          description: 'Do customers order online?',
          fields: [
            { id: 'website', label: 'Website / Online Ordering', type: 'url', required: false },
            { id: 'wire_service', label: 'Wire Service', type: 'select', required: false, options: ['None', 'FTD', 'Teleflora', '1-800-Flowers', 'BloomNation'] },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-orders', type: 'metric', title: "Today's Orders", dataSource: 'orders_today', refreshInterval: 300 },
      { id: 'deliveries', type: 'list', title: "Today's Deliveries", dataSource: 'deliveries_today', refreshInterval: 300 },
      { id: 'upcoming-events', type: 'list', title: 'Upcoming Event Orders', dataSource: 'orders_events', refreshInterval: 3600 },
      { id: 'revenue', type: 'chart', title: 'Weekly Revenue', dataSource: 'revenue_weekly', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'anniversary-reminders', title: 'Send Anniversary Reminders', description: 'Remind customers about upcoming anniversaries with a link to order', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'delivery-confirm', title: 'Confirm Deliveries', description: 'Send delivery confirmation texts to senders when arrangements are delivered', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'weekly-special', title: 'Promote Weekly Special', description: 'Share this week\'s featured arrangement on social media and via text', difficulty: 'needs-approval', estimatedMinutes: 5 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 18000, currentValue: 0 },
      { id: 'orders-per-day', label: 'Orders per Day', format: 'number', target: 12, currentValue: 0 },
      { id: 'avg-order', label: 'Average Order Value', format: 'currency', target: 65, currentValue: 0 },
      { id: 'delivery-success', label: 'On-Time Delivery Rate', format: 'percentage', target: 95, currentValue: 0 },
    ],
    integrations: [
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'bloomnation', name: 'BloomNation', category: 'marketplace', priority: 'recommended', setupTime: 15 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'delivery-confirm', name: 'Delivery Confirmation', subject: 'Your flowers have been delivered! 💐', body: "Hi {{customer_name}},\n\nJust letting you know — your arrangement has been delivered to {{recipient_name}}!\n\nThank you for choosing {{business_name}}. We hope they love it!\n\nWarmly,\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'anniversary-reminder', name: 'Anniversary Reminder', body: "💐 Hey {{customer_name}}! Your anniversary is coming up on {{anniversary_date}}. Surprise them with fresh flowers from {{business_name}}! Order: {{website}}", trigger: 'automated' },
      { id: 'delivery-confirm-sms', name: 'Delivery Confirmation', body: '✅ Your flowers from {{business_name}} have been delivered to {{recipient_name}}! Thanks for brightening someone\'s day.', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'florist', 'flowers', 'delivery'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'thrift-store',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'thrift-store',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Great finds, great prices, great cause',
      description: 'A thrift store offering quality secondhand goods at unbeatable prices, making sustainable shopping accessible to everyone.',
      primaryColor: '#FF9800',
      secondaryColor: '#FFF8E1',
      tone: 'friendly, fun, down-to-earth',
      personality: 'Like a treasure-hunting buddy who gets genuinely excited about great finds and loves a good deal as much as you do.',
    },
    demoExperience: {
      headline: 'Your Thrift Store, a Well-Oiled Machine',
      subheadline: 'Mouse handles donation scheduling, volunteer coordination, and customer engagement — so you can focus on curating amazing finds.',
      heroImage: 'thrift-store-organized-racks',
      socialProof: 'Thrift stores using Mouse see 35% more donations through automated scheduling.',
      ctaText: 'See Your Store on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your thrift store business advisor',
      greeting: "Hey there! Let's make your thrift store the busiest spot in town. I'll help you manage donations, get the word out, and keep customers coming back for the thrill of the hunt.",
      sampleAdvice: [
        'Your half-price Saturdays bring in 3x normal traffic. Consider adding a color-tag rotation sale on Wednesdays to boost midweek sales.',
        'You have 8 pending donation pickup requests. Want me to route them for this week?',
        'Back-to-school season starts in 6 weeks. Time to stock up on kids\' clothing and school supplies.',
      ],
      knowledgeDomains: ['secondhand retail', 'donation management', 'volunteer coordination', 'pricing strategies', 'nonprofit operations', 'sustainable retail'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with store hours, donation questions, or anything else. What can I help you with?",
      personality: "Upbeat and welcoming. Makes everyone feel valued — whether they're donating, shopping, or volunteering. No judgment about what people buy or why. Celebrates the joy of secondhand shopping.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Come on in and see what treasures we have today!" },
        { question: 'Do you accept donations?', answer: "We'd love your donations! {{donation_policy}}. Thank you for thinking of us!" },
        { question: 'Do you pick up donations?', answer: "{{pickup_policy}}" },
        { question: 'What items do you accept?', answer: "We accept {{accepted_items}}. Items should be clean and in working condition. We're unable to accept {{not_accepted}}." },
        { question: 'Do you give tax receipts?', answer: "{{tax_receipt_policy}}" },
        { question: 'When do you restock?', answer: "New items hit the floor every day! Our busiest restocking days are {{restock_days}}." },
        { question: 'How can I volunteer?', answer: "We'd love to have you! {{volunteer_policy}}" },
      ],
      transferTriggers: [
        'Large donation pickup request',
        'Volunteer application',
        'Bulk purchase for organization',
        'Media or partnership inquiry',
      ],
      escalationRules: {
        urgentKeywords: ['large donation', 'estate', 'business closing', 'truck', 'bulk'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For donation drop-offs, {{after_hours_donation}}. See you soon!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Store Info',
          description: "Let's set up your thrift store.",
          fields: [
            { id: 'business_name', label: 'Store Name', type: 'text', required: true, placeholder: 'e.g., Second Chance Thrift' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 9am-6pm, Sun 12pm-5pm' },
            { id: 'address', label: 'Store Address', type: 'text', required: true },
          ],
        },
        {
          id: 'donations',
          title: 'Donation Details',
          description: 'How do you handle donations?',
          fields: [
            { id: 'donation_policy', label: 'Donation Drop-Off Info', type: 'text', required: true, placeholder: 'e.g., Drop off donations during store hours at our back entrance' },
            { id: 'pickup_policy', label: 'Pickup Service', type: 'text', required: false, placeholder: 'e.g., We offer free furniture pickup within 15 miles — call to schedule' },
            { id: 'accepted_items', label: 'Items You Accept', type: 'text', required: true, placeholder: 'e.g., clothing, furniture, housewares, books, electronics' },
            { id: 'not_accepted', label: 'Items You Don\'t Accept', type: 'text', required: true, placeholder: 'e.g., mattresses, cribs, car seats, hazardous materials' },
          ],
        },
        {
          id: 'operations',
          title: 'Store Operations',
          description: 'Tell us about how your store runs.',
          fields: [
            { id: 'tax_receipt_policy', label: 'Tax Receipt Policy', type: 'text', required: false, placeholder: 'e.g., Yes, we provide tax-deductible receipts for all donations' },
            { id: 'restock_days', label: 'Busiest Restock Days', type: 'text', required: false, placeholder: 'e.g., Tuesday and Friday' },
            { id: 'sale_schedule', label: 'Regular Sales', type: 'text', required: false, placeholder: 'e.g., Half-price Saturdays on color-tagged items' },
          ],
        },
        {
          id: 'community',
          title: 'Community',
          description: 'How does your store serve the community?',
          fields: [
            { id: 'mission', label: 'Your Mission (if nonprofit)', type: 'textarea', required: false, placeholder: 'e.g., All proceeds support local job training programs' },
            { id: 'volunteer_policy', label: 'Volunteer Info', type: 'text', required: false, placeholder: 'e.g., Stop by and fill out a volunteer application, or email volunteers@...' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'donations-scheduled', type: 'list', title: 'Scheduled Donation Pickups', dataSource: 'donations_scheduled', refreshInterval: 3600 },
      { id: 'inventory-volume', type: 'chart', title: 'Items In vs Sold', dataSource: 'inventory_flow', refreshInterval: 86400 },
      { id: 'volunteers', type: 'list', title: 'Volunteer Schedule', dataSource: 'volunteer_schedule', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'donation-followup', title: 'Follow Up on Donations', description: 'Send thank-you messages to recent donors with tax receipt info', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'sale-announcement', title: 'Announce Weekly Sale', description: 'Text customers about this week\'s color tag sale', difficulty: 'needs-approval', estimatedMinutes: 3 },
      { id: 'volunteer-reminder', title: 'Volunteer Shift Reminders', description: 'Send shift reminders to scheduled volunteers', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 12000, currentValue: 0 },
      { id: 'donations-received', label: 'Donations Received', format: 'number', target: 200, currentValue: 0 },
      { id: 'avg-transaction', label: 'Average Transaction', format: 'currency', target: 18, currentValue: 0 },
      { id: 'volunteer-hours', label: 'Volunteer Hours', format: 'number', target: 160, currentValue: 0 },
    ],
    integrations: [
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'facebook', name: 'Facebook', category: 'social', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'donation-thanks', name: 'Donation Thank You', subject: 'Thank you for your donation to {{business_name}}!', body: "Dear {{customer_name}},\n\nThank you so much for your generous donation to {{business_name}}!\n\n{{tax_receipt_info}}\n\nYour donation helps us {{mission}}. We truly appreciate your support.\n\nGratefully,\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'sale-alert', name: 'Sale Alert', body: '🏷️ It\'s {{sale_type}} at {{business_name}}! Great finds at even better prices. Open {{hours}}. See you there!', trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'thrift', 'secondhand', 'nonprofit'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'sporting-goods',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'sporting-goods',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Gear up for what you love',
      description: 'A local sporting goods store with knowledgeable staff who actually play the sports they sell — offering expert advice, quality gear, and community.',
      primaryColor: '#1565C0',
      secondaryColor: '#E3F2FD',
      tone: 'energetic, knowledgeable, encouraging',
      personality: 'Like a coach who helps you pick the right equipment for your level and gets you excited about your next adventure.',
    },
    demoExperience: {
      headline: 'Your Sporting Goods Store, In Peak Form',
      subheadline: 'Mouse handles equipment inquiries, team orders, and seasonal promotions — so you can focus on getting people out there doing what they love.',
      heroImage: 'sporting-goods-organized-gear',
      socialProof: 'Sporting goods stores using Mouse see 40% more team and league orders through streamlined quoting.',
      ctaText: 'See Your Store on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your sporting goods business advisor',
      greeting: "Hey there, champ! Let's make your store the go-to for every athlete and outdoor enthusiast in town. I'll handle the logistics so you can focus on helping people find their gear.",
      sampleAdvice: [
        'Youth baseball season starts in 6 weeks. Time to stock up on bats, gloves, and team uniform options. Last year this was your #2 revenue month.',
        'You have 3 team quote requests pending for over a week. Want me to send a follow-up with your team pricing sheet?',
        'Ski season is ending — start marking down winter gear to make room for spring/summer inventory.',
      ],
      knowledgeDomains: ['sporting goods retail', 'team sales', 'seasonal inventory', 'equipment fitting', 'league partnerships', 'outdoor recreation'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with store hours, product availability, team orders, or anything else. What are you looking for?",
      personality: "Enthusiastic and knowledgeable. Asks about skill level and intended use before recommending gear. Treats beginners and pros with equal respect. Gets genuinely excited about helping people find the right equipment.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Come on in!" },
        { question: 'Do you do team orders?', answer: "Absolutely! We handle team uniforms, equipment packages, and league orders. We offer team discounts too. Let me connect you with our team sales person." },
        { question: 'Do you do equipment fitting?', answer: "{{fitting_services}}" },
        { question: 'Do you buy used equipment?', answer: "{{used_equipment_policy}}" },
        { question: 'Do you do repairs?', answer: "{{repair_services}}" },
        { question: 'Do you offer rentals?', answer: "{{rental_policy}}" },
      ],
      transferTriggers: [
        'Team or league order over $500',
        'Equipment fitting appointment',
        'Used equipment trade-in evaluation',
        'Sponsorship or partnership inquiry',
      ],
      escalationRules: {
        urgentKeywords: ['team order deadline', 'tournament', 'safety recall', 'broken', 'defective'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. Leave a message and we'll get back to you. For team orders, email {{email}}.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Store Info',
          description: "Let's get your sporting goods store set up.",
          fields: [
            { id: 'business_name', label: 'Store Name', type: 'text', required: true, placeholder: 'e.g., All-Star Sports' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 9am-7pm, Sun 10am-5pm' },
            { id: 'address', label: 'Store Address', type: 'text', required: true },
          ],
        },
        {
          id: 'sports',
          title: 'Sports You Cover',
          description: 'What sports and activities does your store focus on?',
          fields: [
            { id: 'sports_focus', label: 'Primary Sports', type: 'multiselect', required: true, options: ['Baseball/Softball', 'Basketball', 'Football', 'Soccer', 'Hockey', 'Tennis', 'Golf', 'Running', 'Swimming', 'Cycling', 'Skiing/Snowboarding', 'Hiking/Camping', 'Fishing', 'Hunting'] },
            { id: 'fitting_services', label: 'Fitting Services', type: 'text', required: false, placeholder: 'e.g., Free glove steaming, bat sizing, and cleat fitting' },
          ],
        },
        {
          id: 'services',
          title: 'Extra Services',
          description: 'What sets you apart?',
          fields: [
            { id: 'used_equipment_policy', label: 'Used Equipment Policy', type: 'text', required: false, placeholder: 'e.g., We buy and sell quality used equipment — bring yours in for evaluation' },
            { id: 'repair_services', label: 'Repair Services', type: 'text', required: false, placeholder: 'e.g., We restring rackets and repair gloves' },
            { id: 'rental_policy', label: 'Rental Options', type: 'text', required: false, placeholder: 'e.g., Ski and snowboard rentals available seasonally' },
          ],
        },
        {
          id: 'teams',
          title: 'Team Sales',
          description: 'Do you work with teams and leagues?',
          fields: [
            { id: 'team_sales', label: 'Offer Team Sales?', type: 'toggle', required: false, defaultValue: true },
            { id: 'email', label: 'Team Orders Email', type: 'email', required: false, placeholder: 'teams@yourstore.com' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'team-orders', type: 'list', title: 'Pending Team Orders', dataSource: 'orders_team_pending', refreshInterval: 1800 },
      { id: 'top-categories', type: 'chart', title: 'Sales by Sport', dataSource: 'sales_by_category', refreshInterval: 3600 },
      { id: 'seasonal-stock', type: 'alert', title: 'Seasonal Stock Alerts', dataSource: 'inventory_seasonal', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'team-followup', title: 'Follow Up on Team Quotes', description: 'Check in on pending team order quotes that haven\'t been confirmed', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'season-promo', title: 'Seasonal Sport Promotion', description: 'Send targeted promotions based on upcoming sports seasons', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'clearance-alert', title: 'End-of-Season Clearance', description: 'Mark down out-of-season gear and notify bargain hunters', difficulty: 'needs-approval', estimatedMinutes: 10 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 35000, currentValue: 0 },
      { id: 'team-orders', label: 'Team Orders/Month', format: 'number', target: 8, currentValue: 0 },
      { id: 'avg-transaction', label: 'Average Transaction', format: 'currency', target: 55, currentValue: 0 },
      { id: 'inventory-turn', label: 'Inventory Turnover', format: 'number', target: 5, currentValue: 0 },
    ],
    integrations: [
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'facebook', name: 'Facebook', category: 'social', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'season-start', name: 'Season Starter', subject: "{{sport}} season is here! Gear up at {{business_name}}", body: "Hi {{customer_name}},\n\n{{sport}} season is right around the corner! Stop by {{business_name}} for the latest gear, expert fitting, and team discounts.\n\n{{address}}\n{{hours}}\n\nLet's have a great season!\n{{business_name}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'season-sale', name: 'Seasonal Sale', body: '⚾ {{sport}} season is here! {{business_name}} has everything you need. Team discounts available. Stop by: {{address}}', trigger: 'manual' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'sporting-goods', 'sports', 'team-sales'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'bookstore',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'bookstore',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Your neighborhood page-turner',
      description: 'An independent bookstore offering curated selections, author events, book clubs, and the personal recommendations that algorithms can never replace.',
      primaryColor: '#5D4037',
      secondaryColor: '#EFEBE9',
      tone: 'warm, literary, inviting',
      personality: 'Like a well-read friend who always has the perfect book recommendation and makes the store feel like a second home.',
    },
    demoExperience: {
      headline: 'Your Bookstore, a Real Page-Turner',
      subheadline: 'Mouse handles special orders, event promotion, and book club management — so you can focus on connecting readers with their next favorite book.',
      heroImage: 'bookstore-cozy-shelves-reading',
      socialProof: 'Independent bookstores using Mouse see 30% more event attendance through automated reminders.',
      ctaText: 'See Your Bookstore on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your bookstore business advisor',
      greeting: "Hello, fellow book lover! Let's make your bookstore the heart of the community. I'll handle special orders, events, and outreach so you can do what matters — put the right book in the right hands.",
      sampleAdvice: [
        'Your book club has grown from 8 to 22 members in 3 months. Consider adding a second group or genre-specific clubs.',
        'You have 14 special orders ready for pickup with no notification sent. Want me to text those customers?',
        "Local author {{author_name}} has a new book releasing next month. Want to reach out about a signing event?",
      ],
      knowledgeDomains: ['independent bookselling', 'publisher relations', 'author events', 'book clubs', 'hand-selling', 'community programming'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with store hours, book availability, special orders, or event info. What are you looking for?",
      personality: "Warm and enthusiastic about books. Asks great questions to help narrow down recommendations. Never snobby about reading tastes. Celebrates all readers — from romance to literary fiction to kids' books.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Come browse — we always have coffee on!" },
        { question: 'Can you order a specific book?', answer: "Absolutely! We can special order almost any book in print. It usually arrives within {{order_timeline}}. Want me to place an order for you?" },
        { question: 'Do you have a book club?', answer: "{{book_club_info}}" },
        { question: 'Do you host author events?', answer: "We love author events! Check our calendar at {{events_page}} or follow us on social media for upcoming signings and readings." },
        { question: 'Do you buy used books?', answer: "{{used_books_policy}}" },
        { question: 'Do you have a kids section?', answer: "{{kids_section}}" },
        { question: 'Can you recommend a book?', answer: "That's our favorite thing to do! Tell me a book you've loved recently and I'll pass it to our booksellers for a personalized recommendation. Or come in — our staff picks shelf is always full of gems!" },
      ],
      transferTriggers: [
        'Large or institutional book orders',
        'Author event inquiry',
        'Book club partnership request',
        'Wholesale or educator discount',
      ],
      escalationRules: {
        urgentKeywords: ['bulk order', 'school order', 'event', 'author visit', 'complaint'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For special orders, you can also email us at {{email}}. Happy reading!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Bookstore Info',
          description: "Let's set up your bookstore.",
          fields: [
            { id: 'business_name', label: 'Store Name', type: 'text', required: true, placeholder: 'e.g., Lighthouse Books' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 9am-8pm, Sun 10am-6pm' },
            { id: 'address', label: 'Store Address', type: 'text', required: true },
          ],
        },
        {
          id: 'inventory',
          title: 'Your Selection',
          description: 'What kind of bookstore are you?',
          fields: [
            { id: 'specialties', label: 'Specialties', type: 'multiselect', required: true, options: ['General Fiction', 'Mystery/Thriller', 'Sci-Fi/Fantasy', 'Romance', 'Children\'s', 'Young Adult', 'Non-Fiction', 'Local Interest', 'Rare/Collectible', 'Used Books', 'Comics/Graphic Novels'] },
            { id: 'used_books_policy', label: 'Used Books Policy', type: 'text', required: false, placeholder: 'e.g., We buy and sell quality used books — bring them in for store credit' },
            { id: 'kids_section', label: 'Kids Section', type: 'text', required: false, placeholder: 'e.g., Yes! Dedicated kids\' area with story time every Saturday at 10am' },
          ],
        },
        {
          id: 'services',
          title: 'Services & Events',
          description: 'What makes your store special?',
          fields: [
            { id: 'order_timeline', label: 'Special Order Timeline', type: 'text', required: true, placeholder: 'e.g., 3-5 business days' },
            { id: 'book_club_info', label: 'Book Club Details', type: 'text', required: false, placeholder: 'e.g., Our monthly book club meets the first Thursday at 7pm. All are welcome!' },
            { id: 'events_page', label: 'Events Page URL', type: 'url', required: false },
          ],
        },
        {
          id: 'online',
          title: 'Online Presence',
          description: 'Connect with readers online.',
          fields: [
            { id: 'email', label: 'Store Email', type: 'email', required: false },
            { id: 'website', label: 'Website', type: 'url', required: false },
            { id: 'social_media', label: 'Instagram Handle', type: 'text', required: false, placeholder: '@yourbookstore' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'special-orders', type: 'list', title: 'Pending Special Orders', dataSource: 'orders_special_pending', refreshInterval: 1800 },
      { id: 'upcoming-events', type: 'list', title: 'Upcoming Events', dataSource: 'events_upcoming', refreshInterval: 3600 },
      { id: 'top-sellers', type: 'chart', title: 'Top Sellers This Week', dataSource: 'inventory_top_items', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'order-notification', title: 'Special Order Notifications', description: 'Text customers when their special orders arrive', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'event-promotion', title: 'Promote Upcoming Event', description: 'Send event reminder to your mailing list and social media', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'staff-picks', title: 'Update Staff Picks', description: 'Refresh your staff picks display and share on social media', difficulty: 'needs-approval', estimatedMinutes: 10 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 20000, currentValue: 0 },
      { id: 'special-orders', label: 'Special Orders Filled', format: 'number', target: 40, currentValue: 0 },
      { id: 'event-attendance', label: 'Event Attendance', format: 'number', target: 25, currentValue: 0 },
      { id: 'avg-transaction', label: 'Average Transaction', format: 'currency', target: 28, currentValue: 0 },
    ],
    integrations: [
      { id: 'bookmanager', name: 'BookManager', category: 'inventory', priority: 'recommended', setupTime: 30 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'instagram', name: 'Instagram', category: 'social', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'event-invite', name: 'Event Invitation', subject: '📚 {{event_name}} at {{business_name}}!', body: "Hi {{customer_name}},\n\nYou're invited! Join us for {{event_name}} on {{event_date}} at {{event_time}}.\n\n{{event_description}}\n\n{{address}}\nFree and open to all.\n\nHappy reading!\n{{business_name}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'order-ready', name: 'Special Order Ready', body: '📚 Hi {{customer_name}}! Your book order at {{business_name}} is ready for pickup. We\'re open {{hours}}.', trigger: 'automated' },
      { id: 'event-reminder', name: 'Event Reminder', body: '📖 Reminder: {{event_name}} is tomorrow at {{business_name}}! {{event_time}}. See you there!', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'bookstore', 'books', 'independent'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'furniture-store',
    version: '1.0.0',
    vertical: 'retail',
    subVertical: 'furniture-store',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Quality furniture that turns a house into a home',
      description: 'A local furniture store offering quality pieces, design guidance, and delivery — with the personal service that makes furnishing your home a pleasure, not a headache.',
      primaryColor: '#795548',
      secondaryColor: '#F5F0EB',
      tone: 'helpful, tasteful, patient',
      personality: 'Like an interior designer friend who helps you find pieces you\'ll love for years — never pressures you, always honest about what works.',
    },
    demoExperience: {
      headline: 'Your Furniture Store, Perfectly Arranged',
      subheadline: 'Mouse handles delivery scheduling, design consultations, and follow-ups — so you can focus on helping customers create their dream spaces.',
      heroImage: 'furniture-showroom-styled-room',
      socialProof: 'Furniture stores using Mouse close 30% more sales through automated design consultation follow-ups.',
      ctaText: 'See Your Store on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your furniture store business advisor',
      greeting: "Welcome! Let's make your furniture store the place everyone turns to when they want to make their home beautiful. I'll handle the logistics so you can focus on design and sales.",
      sampleAdvice: [
        'You have 4 customers who visited last weekend but didn\'t purchase. Their notes mention they were deciding on sofas. Want me to send a follow-up with your current sofa promotions?',
        'Your delivery schedule for Saturday is overbooked — 6 deliveries in a 4-delivery capacity. Let me help you reschedule 2 to Sunday.',
        'Tax refund season drives 25% of annual mattress sales. Time to promote your mattress collection.',
      ],
      knowledgeDomains: ['furniture retail', 'interior design basics', 'delivery logistics', 'financing options', 'vendor relations', 'showroom merchandising'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with store hours, delivery questions, product availability, or schedule a design consultation. What can I help you with?",
      personality: "Patient and helpful. Understands that furniture is a big purchase that people think about carefully. Never pushy. Happy to answer the same question twice. Treats a $200 nightstand shopper with the same respect as a $10,000 living room set buyer.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Come in and browse — no pressure, ever." },
        { question: 'Do you deliver?', answer: "Yes! {{delivery_policy}}. We handle everything — delivery, setup, and even remove packaging." },
        { question: 'Do you offer financing?', answer: "{{financing_policy}}" },
        { question: 'How long does delivery take?', answer: "For in-stock items, delivery is typically within {{delivery_timeline}}. Custom orders take {{custom_timeline}}. We'll keep you updated every step of the way." },
        { question: 'Can I customize fabric/color?', answer: "{{customization_policy}}" },
        { question: 'Do you have a design service?', answer: "{{design_service}}" },
        { question: 'What\'s your return policy?', answer: "{{return_policy}}" },
      ],
      transferTriggers: [
        'Purchase over $3,000',
        'Design consultation scheduling',
        'Delivery issue or damage report',
        'Financing application questions',
        'Commercial or bulk orders',
      ],
      escalationRules: {
        urgentKeywords: ['damaged delivery', 'wrong item', 'broken', 'cancel order', 'delivery problem'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For delivery questions, text us your order number. For everything else, leave a message and we'll call you back!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Store Info',
          description: "Let's set up your furniture store.",
          fields: [
            { id: 'business_name', label: 'Store Name', type: 'text', required: true, placeholder: 'e.g., Oakwood Home Furnishings' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Store Hours', type: 'text', required: true, placeholder: 'Mon-Sat 10am-7pm, Sun 12pm-5pm' },
            { id: 'address', label: 'Showroom Address', type: 'text', required: true },
          ],
        },
        {
          id: 'products',
          title: 'What You Carry',
          description: 'Tell us about your product selection.',
          fields: [
            { id: 'categories', label: 'Furniture Categories', type: 'multiselect', required: true, options: ['Living Room', 'Bedroom', 'Dining Room', 'Home Office', 'Outdoor', 'Mattresses', 'Rugs & Decor', 'Kids & Nursery'] },
            { id: 'style_focus', label: 'Style Focus', type: 'multiselect', required: false, options: ['Modern', 'Traditional', 'Farmhouse', 'Mid-Century', 'Industrial', 'Coastal', 'Rustic', 'Contemporary'] },
            { id: 'customization_policy', label: 'Customization Options', type: 'text', required: false, placeholder: 'e.g., Many pieces available in 50+ fabric options with 8-12 week lead time' },
          ],
        },
        {
          id: 'delivery',
          title: 'Delivery & Service',
          description: 'How do you deliver?',
          fields: [
            { id: 'delivery_policy', label: 'Delivery Details', type: 'text', required: true, placeholder: 'e.g., White glove delivery within 50 miles — $99 flat rate' },
            { id: 'delivery_timeline', label: 'In-Stock Delivery Time', type: 'text', required: true, placeholder: 'e.g., 3-7 business days' },
            { id: 'custom_timeline', label: 'Custom Order Timeline', type: 'text', required: false, placeholder: 'e.g., 8-12 weeks' },
          ],
        },
        {
          id: 'policies',
          title: 'Policies & Financing',
          description: 'Your store policies.',
          fields: [
            { id: 'financing_policy', label: 'Financing Options', type: 'text', required: false, placeholder: 'e.g., 0% interest for 12 months on purchases over $999 with approved credit' },
            { id: 'return_policy', label: 'Return Policy', type: 'text', required: true, placeholder: 'e.g., 7-day return on in-stock items in original condition. Custom orders are final sale.' },
            { id: 'design_service', label: 'Design Service', type: 'text', required: false, placeholder: 'e.g., Free in-store design help, or book a $99 in-home consultation (credited toward purchase)' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-sales', type: 'metric', title: "Today's Sales", dataSource: 'pos_daily_total', refreshInterval: 300 },
      { id: 'deliveries', type: 'list', title: 'Upcoming Deliveries', dataSource: 'deliveries_scheduled', refreshInterval: 1800 },
      { id: 'pending-orders', type: 'list', title: 'Pending Custom Orders', dataSource: 'orders_custom_pending', refreshInterval: 3600 },
      { id: 'follow-ups', type: 'list', title: 'Customer Follow-Ups Due', dataSource: 'customers_followup_due', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'delivery-confirm', title: 'Confirm Deliveries', description: 'Send delivery window confirmations to customers scheduled this week', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'browse-followup', title: 'Follow Up with Browsers', description: 'Send a friendly check-in to customers who visited but didn\'t purchase', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'custom-update', title: 'Custom Order Updates', description: 'Send status updates to customers waiting on custom furniture orders', difficulty: 'needs-approval', estimatedMinutes: 5 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 60000, currentValue: 0 },
      { id: 'avg-sale', label: 'Average Sale', format: 'currency', target: 850, currentValue: 0 },
      { id: 'deliveries-completed', label: 'Deliveries This Month', format: 'number', target: 25, currentValue: 0 },
      { id: 'close-rate', label: 'Close Rate', format: 'percentage', target: 30, currentValue: 0 },
    ],
    integrations: [
      { id: 'storis', name: 'STORIS', category: 'erp', priority: 'recommended', setupTime: 30 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'synchrony', name: 'Synchrony Financing', category: 'financing', priority: 'recommended', setupTime: 20 },
    ],
    emailTemplates: [
      { id: 'delivery-scheduled', name: 'Delivery Confirmation', subject: 'Your delivery from {{business_name}} is scheduled!', body: "Hi {{customer_name}},\n\nYour furniture delivery is scheduled for {{delivery_date}} between {{delivery_window}}.\n\nOur team will call 30 minutes before arrival. Please make sure the delivery path is clear.\n\nQuestions? Call us at {{phone}}.\n\n{{business_name}}", trigger: 'automated' },
      { id: 'followup', name: 'Visit Follow-Up', subject: 'Great meeting you at {{business_name}}!', body: "Hi {{customer_name}},\n\nThanks for visiting {{business_name}}! We loved helping you explore options for your {{room_type}}.\n\nIf you have any questions about the pieces you liked, or want to schedule a design consultation, we're here to help. No rush, no pressure — just here when you're ready.\n\n{{phone}}\n{{hours}}\n\nWarmly,\n{{business_name}}", trigger: 'manual' },
    ],
    smsTemplates: [
      { id: 'delivery-reminder', name: 'Delivery Reminder', body: '🚚 Reminder: Your furniture delivery from {{business_name}} is tomorrow, {{delivery_date}}, between {{delivery_window}}. We\'ll call 30 min before. See you then!', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['retail', 'furniture', 'home-furnishings', 'delivery'],
      requiredPlan: 'pro',
    },
  },
];
