import type { ProTemplate } from '../schema';

export const specialtyServicesTemplates: ProTemplate[] = [
  {
    id: 'storage-facility',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'storage-facility',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Safe, secure, simple storage',
      description: 'A self-storage facility offering clean, secure units in a range of sizes — with friendly service and easy access for when you need more space.',
      primaryColor: '#1565C0',
      secondaryColor: '#E3F2FD',
      tone: 'reliable, straightforward, helpful',
      personality: 'Like a trustworthy neighbor who keeps an eye on your stuff and makes everything simple and stress-free.',
    },
    demoExperience: {
      headline: 'Your Storage Facility, Fully Occupied',
      subheadline: 'Mouse handles rental inquiries, access questions, and payment reminders — so you can keep your facility running smoothly.',
      heroImage: 'storage-facility-clean-organized',
      socialProof: 'Storage facilities using Mouse fill 30% more units through instant inquiry responses.',
      ctaText: 'See Your Facility on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your storage business advisor',
      greeting: "Hey there! Let's keep your facility full and your tenants happy. I'll handle the inquiries and reminders so you can focus on running a great operation.",
      sampleAdvice: [
        'You have 12 units available and 8 pending inquiries. Speed of response is everything in storage — want me to send pricing right away?',
        '5 tenants are 10+ days past due. Automated payment reminders reduce late payments by 40%.',
        'Summer moving season starts in 6 weeks. Historically your occupancy peaks at 95% — time to raise rates on remaining units.',
      ],
      knowledgeDomains: ['self-storage operations', 'occupancy management', 'revenue optimization', 'facility security', 'tenant relations', 'seasonal demand'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with unit availability, pricing, access hours, or any questions about our storage facility. What do you need?",
      personality: "Straightforward and helpful. Understands that people looking for storage are often going through a life change (moving, downsizing, renovating) and may feel stressed. Makes the process feel easy.",
      faqs: [
        { question: 'What sizes do you have?', answer: "We offer units from {{size_range}}. Our most popular size is {{popular_size}} — it fits {{popular_size_fits}}. Want me to check what's available?" },
        { question: 'How much does a unit cost?', answer: "Prices start at {{starting_price}} per month for our smallest units. Pricing varies by size and features. I can give you an exact price once I know what size you need." },
        { question: 'Do you have climate-controlled units?', answer: "{{climate_control}}" },
        { question: 'What are your access hours?', answer: "{{access_hours}}" },
        { question: 'How secure is the facility?', answer: "{{security_features}}" },
        { question: 'Do I need a lock?', answer: "{{lock_policy}}" },
        { question: 'Is there a contract or minimum stay?', answer: "{{contract_terms}}" },
      ],
      transferTriggers: [
        'Ready to rent a unit',
        'Existing tenant with billing dispute',
        'Report of break-in or damage',
        'Business or commercial storage needs',
      ],
      escalationRules: {
        urgentKeywords: ['break-in', 'theft', 'flood', 'fire', 'emergency', 'locked out', 'gate broken'],
        afterHoursMessage: "Thanks for calling {{business_name}}! Our office is closed but the facility is accessible {{access_hours}}. For emergencies, call {{emergency_phone}}. For unit inquiries, leave a message and we'll call you back first thing.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Facility Info',
          description: "Let's set up your storage facility.",
          fields: [
            { id: 'business_name', label: 'Facility Name', type: 'text', required: true, placeholder: 'e.g., SecureSpace Self Storage' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'address', label: 'Facility Address', type: 'text', required: true },
            { id: 'access_hours', label: 'Access Hours', type: 'text', required: true, placeholder: 'e.g., 6am-10pm daily, 365 days a year' },
          ],
        },
        {
          id: 'units',
          title: 'Your Units',
          description: 'Tell us about your storage units.',
          fields: [
            { id: 'size_range', label: 'Unit Sizes Available', type: 'text', required: true, placeholder: 'e.g., 5x5 to 10x30' },
            { id: 'popular_size', label: 'Most Popular Size', type: 'text', required: true, placeholder: 'e.g., 10x10' },
            { id: 'popular_size_fits', label: 'What That Size Fits', type: 'text', required: true, placeholder: 'e.g., a 1-2 bedroom apartment worth of furniture' },
            { id: 'starting_price', label: 'Starting Monthly Price', type: 'currency', required: true, placeholder: '49' },
          ],
        },
        {
          id: 'features',
          title: 'Features & Security',
          description: 'What makes your facility stand out?',
          fields: [
            { id: 'climate_control', label: 'Climate Control', type: 'text', required: true, placeholder: 'e.g., Yes! Climate-controlled units available starting at $89/month' },
            { id: 'security_features', label: 'Security Features', type: 'text', required: true, placeholder: 'e.g., 24/7 video surveillance, electronic gate access, individual unit alarms, on-site manager' },
            { id: 'lock_policy', label: 'Lock Policy', type: 'text', required: true, placeholder: 'e.g., Bring your own or purchase a high-security disc lock from us for $15' },
          ],
        },
        {
          id: 'policies',
          title: 'Policies',
          description: 'Your rental policies.',
          fields: [
            { id: 'contract_terms', label: 'Contract Terms', type: 'text', required: true, placeholder: 'e.g., Month-to-month, no long-term contract required. 14-day notice to vacate.' },
            { id: 'emergency_phone', label: 'Emergency Contact Number', type: 'phone', required: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'occupancy', type: 'metric', title: 'Occupancy Rate', dataSource: 'units_occupancy', refreshInterval: 3600 },
      { id: 'available-units', type: 'chart', title: 'Available Units by Size', dataSource: 'units_available_by_size', refreshInterval: 3600 },
      { id: 'past-due', type: 'alert', title: 'Past Due Accounts', dataSource: 'accounts_past_due', refreshInterval: 3600 },
      { id: 'inquiries', type: 'list', title: 'New Inquiries', dataSource: 'inquiries_pending', refreshInterval: 600 },
    ],
    sampleTasks: [
      { id: 'payment-reminder', title: 'Send Payment Reminders', description: 'Text tenants whose rent is due in 3 days', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'inquiry-response', title: 'Respond to Inquiries', description: 'Send unit availability and pricing to new inquiries', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'past-due-notice', title: 'Past Due Notices', description: 'Send late payment notices to accounts 5+ days overdue', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'occupancy-rate', label: 'Occupancy Rate', format: 'percentage', target: 92, currentValue: 0 },
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 30000, currentValue: 0 },
      { id: 'avg-rent', label: 'Average Unit Rent', format: 'currency', target: 125, currentValue: 0 },
      { id: 'delinquency', label: 'Delinquency Rate', format: 'percentage', target: 5, currentValue: 0 },
    ],
    integrations: [
      { id: 'sitelink', name: 'SiteLink', category: 'management', priority: 'recommended', setupTime: 30 },
      { id: 'storeedge', name: 'StoreEDGE', category: 'management', priority: 'recommended', setupTime: 25 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'sparefoot', name: 'SpareFoot', category: 'marketplace', priority: 'recommended', setupTime: 15 },
    ],
    emailTemplates: [
      { id: 'welcome', name: 'Welcome New Tenant', subject: 'Welcome to {{business_name}}! Here\'s everything you need to know', body: "Hi {{customer_name}},\n\nWelcome to {{business_name}}! Here are your storage details:\n\n🔑 Unit: {{unit_number}}\n📐 Size: {{unit_size}}\n🔐 Access Code: {{access_code}}\n⏰ Access Hours: {{access_hours}}\n💰 Monthly Rent: {{monthly_rent}} (due on the 1st)\n\nA few tips:\n- Use a quality lock (we sell them at the office if you need one)\n- Don't store perishables, flammables, or anything illegal\n- Keep your access code private\n\nQuestions? Call us at {{phone}}.\n\nWelcome aboard!\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'payment-reminder', name: 'Payment Reminder', body: 'Hi {{customer_name}}, your {{business_name}} storage rent of {{monthly_rent}} is due in 3 days. Pay online or call {{phone}}. Thanks!', trigger: 'automated' },
      { id: 'past-due', name: 'Past Due Notice', body: '⚠️ Hi {{customer_name}}, your {{business_name}} storage rent is past due. Please pay ASAP to avoid late fees. Call {{phone}} with questions.', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'storage', 'self-storage', 'rental'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'laundromat',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'laundromat',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Clean clothes, easy life',
      description: 'A clean, well-maintained laundromat offering self-service machines, wash-and-fold service, and a comfortable environment to get your laundry done.',
      primaryColor: '#0288D1',
      secondaryColor: '#E1F5FE',
      tone: 'friendly, clean, efficient',
      personality: 'Like a helpful attendant who keeps everything spotless and running smoothly — making laundry day actually pleasant.',
    },
    demoExperience: {
      headline: 'Your Laundromat, Clean and Profitable',
      subheadline: 'Mouse handles wash-and-fold orders, machine status, and customer communication — so you can focus on operations.',
      heroImage: 'laundromat-bright-clean-modern',
      socialProof: 'Laundromats using Mouse see 45% more wash-and-fold orders through text ordering.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your laundromat business advisor',
      greeting: "Hey there! Let's keep your laundromat running clean and profitable. I'll handle customer communication and wash-and-fold orders so you can focus on maintenance and growth.",
      sampleAdvice: [
        'Your wash-and-fold service has 60% profit margins vs 30% on self-service. Consider promoting it more prominently with signage and text campaigns.',
        'Machines 5, 8, and 12 have had 3+ service calls this month. It may be time to replace rather than repair.',
        'Your weekday morning hours are dead. Consider a "Drop off by 9am, ready by 5pm" same-day service for commuters.',
      ],
      knowledgeDomains: ['laundromat operations', 'machine maintenance', 'wash-and-fold service', 'commercial laundry', 'vending management', 'customer retention'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with hours, wash-and-fold service, machine questions, or anything else. How can I help?",
      personality: "Friendly and practical. Makes laundry day feel easy. Clear about pricing and turnaround times. Understands that people want quick, reliable service.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. {{last_load_time}}" },
        { question: 'Do you offer wash-and-fold?', answer: "Yes! Our wash-and-fold service is {{wash_fold_price}}. Just drop off your laundry and we'll wash, dry, and fold it for you. Turnaround is {{wash_fold_turnaround}}." },
        { question: 'How much do the machines cost?', answer: "Washers start at {{washer_price}} and dryers are {{dryer_price}}. We have machines in several sizes for different load sizes." },
        { question: 'Do you have change?', answer: "{{payment_methods}}" },
        { question: 'Do you do dry cleaning?', answer: "{{dry_cleaning}}" },
        { question: 'Is there an attendant on site?', answer: "{{attendant_hours}}" },
      ],
      transferTriggers: [
        'Machine malfunction or refund request',
        'Large commercial laundry inquiry',
        'Complaint about cleanliness or safety',
        'Lost item report',
      ],
      escalationRules: {
        urgentKeywords: ['flood', 'fire', 'machine broken', 'stuck', 'emergency', 'safety', 'theft'],
        afterHoursMessage: "Thanks for calling {{business_name}}! Our office is closed but the laundromat is open {{hours}}. For machine issues, note the machine number and call us during business hours for a refund.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Laundromat Info',
          description: "Let's set up your laundromat.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Spin City Laundry' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Operating Hours', type: 'text', required: true, placeholder: 'e.g., 6am-10pm daily' },
            { id: 'last_load_time', label: 'Last Load Time', type: 'text', required: true, placeholder: 'e.g., Last wash must start by 8:30pm' },
          ],
        },
        {
          id: 'pricing',
          title: 'Pricing',
          description: 'Your machine and service pricing.',
          fields: [
            { id: 'washer_price', label: 'Washer Starting Price', type: 'text', required: true, placeholder: 'e.g., $3.50 for a regular load' },
            { id: 'dryer_price', label: 'Dryer Price', type: 'text', required: true, placeholder: 'e.g., $0.25 per 6 minutes' },
            { id: 'wash_fold_price', label: 'Wash & Fold Price', type: 'text', required: false, placeholder: 'e.g., $1.50 per pound, 10 lb minimum' },
            { id: 'wash_fold_turnaround', label: 'Wash & Fold Turnaround', type: 'text', required: false, placeholder: 'e.g., same-day if dropped off before noon, otherwise next day' },
          ],
        },
        {
          id: 'features',
          title: 'Features',
          description: 'What makes your laundromat special?',
          fields: [
            { id: 'payment_methods', label: 'Payment Methods', type: 'text', required: true, placeholder: 'e.g., Coin, credit card, and app-pay on all machines. Change machine available.' },
            { id: 'attendant_hours', label: 'Attendant Hours', type: 'text', required: false, placeholder: 'e.g., Attendant on site 8am-6pm daily' },
            { id: 'dry_cleaning', label: 'Dry Cleaning', type: 'text', required: false, placeholder: 'e.g., Drop-off dry cleaning available through our partner — 2-day turnaround' },
          ],
        },
        {
          id: 'amenities',
          title: 'Amenities',
          description: 'Extra features for your customers.',
          fields: [
            { id: 'wifi', label: 'Free WiFi?', type: 'toggle', required: false, defaultValue: true },
            { id: 'folding_tables', label: 'Folding Tables Available?', type: 'toggle', required: false, defaultValue: true },
            { id: 'vending', label: 'Vending Machines?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'daily-revenue', type: 'metric', title: "Today's Revenue", dataSource: 'revenue_daily', refreshInterval: 300 },
      { id: 'wash-fold-orders', type: 'list', title: 'Wash & Fold Orders', dataSource: 'orders_wash_fold', refreshInterval: 600 },
      { id: 'machine-status', type: 'chart', title: 'Machine Status', dataSource: 'machines_status', refreshInterval: 300 },
      { id: 'maintenance-alerts', type: 'alert', title: 'Maintenance Needed', dataSource: 'machines_maintenance', refreshInterval: 1800 },
    ],
    sampleTasks: [
      { id: 'order-ready', title: 'Notify Orders Ready', description: 'Text customers when their wash-and-fold order is ready for pickup', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'promo-blast', title: 'Weekly Promotion', description: 'Send a midweek promo to drive off-peak wash-and-fold orders', difficulty: 'needs-approval', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 15000, currentValue: 0 },
      { id: 'wash-fold-orders', label: 'Wash & Fold Orders/Month', format: 'number', target: 100, currentValue: 0 },
      { id: 'machine-uptime', label: 'Machine Uptime', format: 'percentage', target: 95, currentValue: 0 },
      { id: 'avg-daily-revenue', label: 'Avg Daily Revenue', format: 'currency', target: 500, currentValue: 0 },
    ],
    integrations: [
      { id: 'cents', name: 'Cents', category: 'operations', priority: 'recommended', setupTime: 20 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'order-ready', name: 'Order Ready for Pickup', subject: 'Your laundry is ready at {{business_name}}! 👕', body: "Hi {{customer_name}},\n\nYour wash-and-fold order is clean, folded, and ready for pickup!\n\nPickup during business hours: {{hours}}\n{{address}}\n\nThanks for letting us handle the laundry!\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'order-ready-sms', name: 'Order Ready', body: '👕 Hi {{customer_name}}! Your laundry at {{business_name}} is ready for pickup. We\'re open {{hours}}. See you soon!', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'laundromat', 'laundry', 'wash-fold'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'dry-cleaner',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'dry-cleaner',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Expert care for your finest clothes',
      description: 'A professional dry cleaning service offering expert garment care, alterations, and the kind of attention to detail your wardrobe deserves.',
      primaryColor: '#00695C',
      secondaryColor: '#E0F2F1',
      tone: 'professional, meticulous, reliable',
      personality: 'Like a trusted tailor who treats every garment with care — whether it\'s a $50 dress shirt or a $5,000 wedding gown.',
    },
    demoExperience: {
      headline: 'Your Dry Cleaner, Pressed for Success',
      subheadline: 'Mouse handles order notifications, pickup reminders, and route management — so you can focus on delivering spotless results.',
      heroImage: 'dry-cleaner-pressed-shirts-rack',
      socialProof: 'Dry cleaners using Mouse see 35% fewer unclaimed garments through automated pickup reminders.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your dry cleaning business advisor',
      greeting: "Hello! Let's make your dry cleaning business crisp and profitable. I'll handle customer communication and reminders so every garment gets picked up on time.",
      sampleAdvice: [
        'You have 23 orders ready for pickup that are 5+ days old. Want me to send pickup reminders? Unclaimed garments cost you storage and cash flow.',
        'Your route delivery service has 40% margins vs 25% for walk-in. Consider expanding your route to the new office park on Oak Street.',
        'Fall coat season starts in 4 weeks. Run a "Coat Cleaning Special" to drive volume.',
      ],
      knowledgeDomains: ['dry cleaning operations', 'garment care', 'route management', 'alterations', 'stain treatment', 'seasonal promotions'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with order status, pricing, services, or drop-off hours. What do you need?",
      personality: "Professional and reassuring. Understands that people worry about their special garments. Gives clear answers about pricing and turnaround. Makes the process feel easy and trustworthy.",
      faqs: [
        { question: 'What are your hours?', answer: "We're open {{hours}}. Drop-off and pickup anytime during business hours!" },
        { question: 'How much does dry cleaning cost?', answer: "{{pricing_info}}" },
        { question: 'When will my order be ready?', answer: "Standard turnaround is {{standard_turnaround}}. We also offer {{rush_service}} for rush orders." },
        { question: 'Do you do alterations?', answer: "{{alterations_policy}}" },
        { question: 'Do you pick up and deliver?', answer: "{{delivery_policy}}" },
        { question: 'Can you clean my wedding dress?', answer: "{{wedding_dress}}" },
        { question: 'Is my order ready?', answer: "I can check! What's the name on the order or your phone number? I'll look it up for you." },
      ],
      transferTriggers: [
        'Complaint about garment damage',
        'Wedding dress or specialty item',
        'Commercial or corporate account',
        'Route delivery setup',
      ],
      escalationRules: {
        urgentKeywords: ['damaged', 'ruined', 'stain worse', 'lost', 'missing', 'wrong item'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. To check your order status, text us your last name. See you soon!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your dry cleaning business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Prestige Cleaners' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Business Hours', type: 'text', required: true, placeholder: 'Mon-Fri 7am-7pm, Sat 8am-4pm' },
            { id: 'address', label: 'Address', type: 'text', required: true },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What services do you offer?',
          fields: [
            { id: 'pricing_info', label: 'Basic Pricing', type: 'text', required: true, placeholder: 'e.g., Shirts $3.50, Pants $6.50, Suits $15, Dresses $12-$18' },
            { id: 'standard_turnaround', label: 'Standard Turnaround', type: 'text', required: true, placeholder: 'e.g., 2 business days' },
            { id: 'rush_service', label: 'Rush Service', type: 'text', required: false, placeholder: 'e.g., same-day service if dropped off by 9am, 50% surcharge' },
            { id: 'alterations_policy', label: 'Alterations', type: 'text', required: false, placeholder: 'e.g., Yes! Hems, zippers, buttons, and custom tailoring by our in-house seamstress' },
          ],
        },
        {
          id: 'specialty',
          title: 'Specialty Services',
          description: 'Do you handle specialty items?',
          fields: [
            { id: 'wedding_dress', label: 'Wedding Dress Cleaning', type: 'text', required: false, placeholder: 'e.g., Yes! Expert wedding dress cleaning and preservation starting at $200' },
            { id: 'delivery_policy', label: 'Pickup & Delivery', type: 'text', required: false, placeholder: 'e.g., Free pickup and delivery on orders over $30 within 10 miles' },
          ],
        },
        {
          id: 'preferences',
          title: 'Notification Preferences',
          description: 'How should we notify your customers?',
          fields: [
            { id: 'notify_ready', label: 'Notify When Order Ready?', type: 'toggle', required: false, defaultValue: true },
            { id: 'notify_pickup_reminder', label: 'Send Pickup Reminders (5+ days)?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'orders-today', type: 'metric', title: "Today's Orders", dataSource: 'orders_today', refreshInterval: 300 },
      { id: 'ready-pickup', type: 'list', title: 'Ready for Pickup', dataSource: 'orders_ready', refreshInterval: 600 },
      { id: 'unclaimed', type: 'alert', title: 'Unclaimed (5+ days)', dataSource: 'orders_unclaimed', refreshInterval: 3600 },
      { id: 'daily-revenue', type: 'metric', title: "Today's Revenue", dataSource: 'revenue_daily', refreshInterval: 300 },
    ],
    sampleTasks: [
      { id: 'order-ready', title: 'Send Ready Notifications', description: 'Text customers when their order is ready for pickup', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'pickup-reminder', title: 'Pickup Reminders', description: 'Remind customers with orders ready for 5+ days to pick up', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'seasonal-promo', title: 'Seasonal Promotion', description: 'Send seasonal cleaning specials to your customer list', difficulty: 'needs-approval', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 12000, currentValue: 0 },
      { id: 'orders-per-day', label: 'Orders per Day', format: 'number', target: 40, currentValue: 0 },
      { id: 'avg-ticket', label: 'Average Ticket', format: 'currency', target: 22, currentValue: 0 },
      { id: 'pickup-rate', label: 'Same-Week Pickup Rate', format: 'percentage', target: 85, currentValue: 0 },
    ],
    integrations: [
      { id: 'cleaner-pos', name: 'SPOT POS', category: 'pos', priority: 'recommended', setupTime: 20 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'order-ready', name: 'Order Ready', subject: 'Your dry cleaning is ready at {{business_name}}!', body: "Hi {{customer_name}},\n\nYour order is clean, pressed, and ready for pickup!\n\n{{address}}\n{{hours}}\n\nSee you soon!\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'order-ready-sms', name: 'Order Ready', body: '✨ Hi {{customer_name}}! Your dry cleaning at {{business_name}} is ready. Pick up during our hours: {{hours}}.', trigger: 'automated' },
      { id: 'pickup-reminder', name: 'Pickup Reminder', body: 'Hi {{customer_name}}, your dry cleaning at {{business_name}} has been ready for pickup since {{ready_date}}. We\'re open {{hours}}. See you soon!', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'dry-cleaner', 'laundry', 'garment-care'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'moving-company',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'moving-company',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Moving made easy — we handle the heavy lifting',
      description: 'A professional moving company providing local and long-distance moves with care, efficiency, and the kind of reliability that takes the stress out of moving day.',
      primaryColor: '#E65100',
      secondaryColor: '#FFF3E0',
      tone: 'reliable, strong, reassuring',
      personality: 'Like having your strongest, most organized friend show up with a truck and a plan — everything handled, nothing broken.',
    },
    demoExperience: {
      headline: 'Your Moving Company, Always on the Move',
      subheadline: 'Mouse handles estimates, booking, and customer communication — so your crew can focus on safe, efficient moves.',
      heroImage: 'moving-truck-crew-loading-home',
      socialProof: 'Moving companies using Mouse close 40% more moves through instant estimate follow-ups.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your moving company business advisor',
      greeting: "Hey there, mover! Let's keep your trucks full and your customers happy. I'll handle the estimates and follow-ups so your crew can do what they do best.",
      sampleAdvice: [
        'You have 7 estimate requests in the last 3 days with no follow-up. Moving leads go cold fast — 80% book within 48 hours of their first call.',
        'June-August is 40% of your annual revenue. You\'re at 60% capacity for July — time to push marketing.',
        'Your Google reviews mention "careful with furniture" 15 times. Lead with that in your ads — it\'s your differentiator.',
      ],
      knowledgeDomains: ['moving operations', 'logistics', 'estimating', 'crew management', 'truck fleet', 'packing services'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. Planning a move? I can help you get a free estimate, check availability, or answer any questions. When are you looking to move?",
      personality: "Reassuring and organized. Understands that moving is stressful and people need to feel confident in their movers. Asks the right questions to scope the move. Never dismissive about small moves — treats every customer with equal care.",
      faqs: [
        { question: 'How much does a move cost?', answer: "Our rates are {{rate_structure}}. The total depends on the size of your home, distance, and any extras like packing. Want me to set up a free estimate?" },
        { question: 'Are you licensed and insured?', answer: "Absolutely. We are fully licensed and insured. {{license_details}}" },
        { question: 'Do you do long-distance moves?', answer: "{{long_distance}}" },
        { question: 'Do you provide packing services?', answer: "{{packing_services}}" },
        { question: 'What about fragile or valuable items?', answer: "We take extra care with fragile items. {{specialty_items}}. We also offer additional valuation coverage for high-value items." },
        { question: 'How far in advance should I book?', answer: "We recommend booking {{booking_lead_time}} in advance, especially during summer months. But we handle last-minute moves too!" },
      ],
      transferTriggers: [
        'Ready to book or requesting a contract',
        'Long-distance or multi-stop move',
        'Damage claim or complaint',
        'Commercial or office move',
      ],
      escalationRules: {
        urgentKeywords: ['damage', 'broken', 'missing', 'claim', 'late', 'no show', 'emergency'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For a free estimate, leave your name, phone, move date, and current/new addresses. We'll call you back first thing!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Company Info',
          description: "Let's set up your moving company.",
          fields: [
            { id: 'business_name', label: 'Company Name', type: 'text', required: true, placeholder: 'e.g., Two Men & A Truck' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., Greater Denver area + long-distance nationwide' },
            { id: 'license_details', label: 'License Info', type: 'text', required: true, placeholder: 'e.g., USDOT #1234567, fully insured up to $1M' },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What moving services do you offer?',
          fields: [
            { id: 'rate_structure', label: 'Rate Structure', type: 'text', required: true, placeholder: 'e.g., $150/hour for 2 movers + truck, $200/hour for 3 movers + truck' },
            { id: 'long_distance', label: 'Long-Distance Moves', type: 'text', required: false, placeholder: 'e.g., Yes! We handle moves anywhere in the continental US. Long-distance is quoted flat-rate.' },
            { id: 'packing_services', label: 'Packing Services', type: 'text', required: false, placeholder: 'e.g., Full and partial packing available. Packing materials included. Starting at $50/hour.' },
          ],
        },
        {
          id: 'details',
          title: 'Move Details',
          description: 'Help us understand your process.',
          fields: [
            { id: 'specialty_items', label: 'Specialty Items', type: 'text', required: false, placeholder: 'e.g., We handle pianos, pool tables, safes, and artwork with specialized equipment' },
            { id: 'booking_lead_time', label: 'Recommended Booking Lead Time', type: 'text', required: true, placeholder: 'e.g., 2-4 weeks' },
            { id: 'estimate_type', label: 'Estimate Type', type: 'select', required: true, options: ['Free in-home estimates', 'Free virtual/video estimates', 'Phone estimates', 'All of the above'] },
          ],
        },
        {
          id: 'equipment',
          title: 'Your Fleet',
          description: 'Tell us about your trucks.',
          fields: [
            { id: 'truck_count', label: 'Number of Trucks', type: 'number', required: true, placeholder: '4' },
            { id: 'crew_size', label: 'Average Crew Size', type: 'text', required: true, placeholder: 'e.g., 2-4 movers depending on the job' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'todays-moves', type: 'list', title: "Today's Moves", dataSource: 'moves_today', refreshInterval: 300 },
      { id: 'pending-estimates', type: 'list', title: 'Pending Estimates', dataSource: 'estimates_pending', refreshInterval: 600 },
      { id: 'weekly-schedule', type: 'chart', title: 'Weekly Schedule', dataSource: 'schedule_weekly', refreshInterval: 3600 },
      { id: 'monthly-revenue', type: 'metric', title: 'Monthly Revenue', dataSource: 'revenue_monthly', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'estimate-followup', title: 'Follow Up on Estimates', description: 'Send follow-ups to people who requested estimates but haven\'t booked', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'move-confirmation', title: 'Confirm Upcoming Moves', description: 'Send confirmation texts 48 hours before each scheduled move', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'review-request', title: 'Request Reviews', description: 'Send review requests the day after a completed move', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 40000, currentValue: 0 },
      { id: 'moves-month', label: 'Moves/Month', format: 'number', target: 25, currentValue: 0 },
      { id: 'avg-move', label: 'Average Move Value', format: 'currency', target: 1200, currentValue: 0 },
      { id: 'estimate-conversion', label: 'Estimate to Booking', format: 'percentage', target: 45, currentValue: 0 },
    ],
    integrations: [
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'yelp', name: 'Yelp', category: 'listings', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'move-confirm', name: 'Move Confirmation', subject: 'Your move with {{business_name}} is confirmed!', body: "Hi {{customer_name}},\n\nYour move is confirmed! Here are the details:\n\n📅 Date: {{move_date}}\n⏰ Arrival Window: {{arrival_window}}\n📍 From: {{origin_address}}\n📍 To: {{destination_address}}\n👷 Crew: {{crew_size}} movers\n🚛 Truck: {{truck_size}}\n\nPlease have everything packed and ready to go. Our crew will call 30 minutes before arrival.\n\nQuestions? Call {{phone}}.\n\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'move-reminder', name: 'Move Reminder', body: '🚛 Reminder: Your move with {{business_name}} is tomorrow! Arrival window: {{arrival_window}}. We\'ll call 30 min before. Questions? {{phone}}', trigger: 'automated' },
      { id: 'crew-enroute', name: 'Crew En Route', body: 'Your {{business_name}} crew is on the way! Estimated arrival: {{eta}}. See you soon! 🚛', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'moving', 'movers', 'relocation'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'junk-removal',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'junk-removal',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'We haul it all — you don\'t lift a finger',
      description: 'A professional junk removal service that handles everything from single-item pickups to full property cleanouts — fast, affordable, and eco-friendly.',
      primaryColor: '#2E7D32',
      secondaryColor: '#E8F5E9',
      tone: 'can-do, friendly, efficient',
      personality: 'Like the strong friend with a truck who shows up, gets it done, and doesn\'t complain — except this friend also recycles responsibly.',
    },
    demoExperience: {
      headline: 'Your Junk Removal Business, Clean and Profitable',
      subheadline: 'Mouse handles estimates, scheduling, and follow-ups — so your crew can focus on hauling and your phone keeps ringing.',
      heroImage: 'junk-removal-team-loading-truck',
      socialProof: 'Junk removal companies using Mouse book 45% more jobs through instant estimate responses.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your junk removal business advisor',
      greeting: "Hey there! Let's keep your trucks busy and your calendar full. I'll handle the calls and estimates so your crew can keep hauling.",
      sampleAdvice: [
        'You have 5 estimate requests from the last 2 days with no response. Junk removal is impulse — respond within an hour to close 3x more jobs.',
        'Spring cleaning season drives 40% of annual revenue. Start your "Spring Cleanout Special" campaign now.',
        'Your average job is $350 but your competitor charges $450 for the same truck load. You may be undercharging.',
      ],
      knowledgeDomains: ['junk removal operations', 'pricing strategy', 'recycling/donation routing', 'truck logistics', 'estate cleanouts', 'commercial hauling'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. Need junk removed? I can help you get a free estimate or schedule a pickup. What do you need hauled?",
      personality: "Upbeat and no-nonsense. Makes the process feel easy. Asks about the type and amount of junk to give ballpark pricing. Emphasizes eco-friendly disposal. Never judges what people are getting rid of.",
      faqs: [
        { question: 'How much does junk removal cost?', answer: "Our pricing is based on how much space your junk takes in our truck. {{pricing_structure}}. We offer free on-site estimates — no obligation!" },
        { question: 'What items do you take?', answer: "We take almost everything! {{accepted_items}}. We can NOT take {{not_accepted}}." },
        { question: 'Do you recycle?', answer: "{{eco_policy}}" },
        { question: 'How fast can you come?', answer: "In most cases, we can come {{availability}}. For exact scheduling, let me check our calendar — when works best for you?" },
        { question: 'Do I need to be home?', answer: "For most jobs, yes — someone needs to point us to the items. But for outdoor pickups, we can sometimes work without you being there." },
      ],
      transferTriggers: [
        'Estate cleanout or large commercial job',
        'Hazardous material inquiry',
        'Complaint about service or pricing',
        'Contractor or ongoing service setup',
      ],
      escalationRules: {
        urgentKeywords: ['emergency', 'eviction', 'hoarder', 'biohazard', 'hazardous', 'today'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're off the clock but back at {{next_open}}. Text us a photo of what needs to go and we'll have an estimate ready when we open!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your junk removal business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., Gone for Good Junk Removal' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., within 30 miles of downtown' },
          ],
        },
        {
          id: 'pricing',
          title: 'Your Pricing',
          description: 'How do you price jobs?',
          fields: [
            { id: 'pricing_structure', label: 'Pricing Structure', type: 'text', required: true, placeholder: 'e.g., Starting at $99 for a small load. Half truck $250. Full truck $450.' },
            { id: 'accepted_items', label: 'Items You Take', type: 'text', required: true, placeholder: 'e.g., furniture, appliances, yard waste, electronics, construction debris, hot tubs' },
            { id: 'not_accepted', label: 'Items You Don\'t Take', type: 'text', required: true, placeholder: 'e.g., hazardous waste, chemicals, paint, asbestos, tires' },
          ],
        },
        {
          id: 'operations',
          title: 'Operations',
          description: 'How does your service work?',
          fields: [
            { id: 'availability', label: 'Typical Availability', type: 'text', required: true, placeholder: 'e.g., same-day or next-day service' },
            { id: 'eco_policy', label: 'Recycling/Donation Policy', type: 'text', required: true, placeholder: 'e.g., We recycle or donate up to 60% of what we haul. We partner with local charities for usable items.' },
          ],
        },
        {
          id: 'specialties',
          title: 'Specialty Services',
          description: 'Any extra services?',
          fields: [
            { id: 'estate_cleanouts', label: 'Do Estate Cleanouts?', type: 'toggle', required: false, defaultValue: true },
            { id: 'commercial', label: 'Do Commercial Jobs?', type: 'toggle', required: false, defaultValue: true },
            { id: 'demolition', label: 'Light Demo Available?', type: 'toggle', required: false, defaultValue: false },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'todays-jobs', type: 'list', title: "Today's Jobs", dataSource: 'jobs_today', refreshInterval: 300 },
      { id: 'pending-estimates', type: 'list', title: 'Pending Estimates', dataSource: 'estimates_pending', refreshInterval: 600 },
      { id: 'weekly-revenue', type: 'metric', title: 'Weekly Revenue', dataSource: 'revenue_weekly', refreshInterval: 3600 },
      { id: 'jobs-completed', type: 'chart', title: 'Jobs This Month', dataSource: 'jobs_monthly', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'estimate-followup', title: 'Follow Up on Estimates', description: 'Send follow-ups to estimate requests that are 24+ hours old', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'review-request', title: 'Request Reviews', description: 'Send review requests after completed jobs', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'seasonal-promo', title: 'Seasonal Promotion', description: 'Promote spring/fall cleanout specials', difficulty: 'needs-approval', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 20000, currentValue: 0 },
      { id: 'jobs-month', label: 'Jobs/Month', format: 'number', target: 50, currentValue: 0 },
      { id: 'avg-job', label: 'Average Job Value', format: 'currency', target: 325, currentValue: 0 },
      { id: 'recycle-rate', label: 'Recycle/Donate Rate', format: 'percentage', target: 60, currentValue: 0 },
    ],
    integrations: [
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'yelp', name: 'Yelp', category: 'listings', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'estimate-confirm', name: 'Estimate Confirmation', subject: 'Your free junk removal estimate from {{business_name}}', body: "Hi {{customer_name}},\n\nThanks for contacting {{business_name}}! Your free estimate appointment is confirmed:\n\n📅 {{estimate_date}} at {{estimate_time}}\n📍 {{address}}\n\nOur team will look at what needs to go and give you a price on the spot. If you approve, we can usually haul it right then and there!\n\nQuestions? Call {{phone}}.\n\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'on-the-way', name: 'On Our Way', body: '🚛 Hi {{customer_name}}! Your {{business_name}} crew is headed your way. Estimated arrival: {{eta}}. See you soon!', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'junk-removal', 'hauling', 'cleanout'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'appliance-repair',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'appliance-repair',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'We fix what keeps your home running',
      description: 'A professional appliance repair service that gets your washer, dryer, fridge, dishwasher, or oven back in working order — fast and affordably.',
      primaryColor: '#37474F',
      secondaryColor: '#ECEFF1',
      tone: 'knowledgeable, reliable, honest',
      personality: 'Like the handy neighbor who actually knows what they\'re doing — diagnoses the problem fast, gives you an honest assessment, and fixes it right the first time.',
    },
    demoExperience: {
      headline: 'Your Appliance Repair Business, Fixed Up',
      subheadline: 'Mouse handles service calls, scheduling, and follow-ups — so you can focus on diagnosing and fixing.',
      heroImage: 'appliance-technician-repairing-washer',
      socialProof: 'Appliance repair businesses using Mouse fill 35% more service slots through automated booking.',
      ctaText: 'See Your Business on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your appliance repair business advisor',
      greeting: "Hey there, fixer! Let's keep your schedule full and your customers happy. I'll handle the calls and booking so you can focus on repairs.",
      sampleAdvice: [
        'You have 6 missed calls from today. In appliance repair, customers call the next company within 15 minutes. Let me auto-respond with your next available slot.',
        'Your average repair is $185 but you\'re spending 30 minutes on the phone per booking. Automating scheduling would save you 3 hours per day.',
        'Refrigerator repairs are your highest-margin service at 65%. Consider marketing specifically to "fridge not cooling" searches on Google.',
      ],
      knowledgeDomains: ['appliance repair', 'parts sourcing', 'scheduling optimization', 'warranty management', 'customer communication', 'service pricing'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help you schedule a repair, check on an existing appointment, or answer questions about our services. What appliance is giving you trouble?",
      personality: "Empathetic and practical. Understands that a broken appliance is a real disruption to daily life. Asks the right diagnostic questions to prepare the technician. Gives honest expectations about timing and cost.",
      faqs: [
        { question: 'What do you repair?', answer: "We repair {{appliances_serviced}}. If it's a major home appliance, we probably fix it!" },
        { question: 'How much does a repair cost?', answer: "Our service call/diagnostic fee is {{diagnostic_fee}}. That fee is applied toward the repair if you proceed. Most repairs range from {{repair_range}} depending on the issue and parts needed." },
        { question: 'How soon can you come?', answer: "We typically have availability within {{availability}}. Emergencies like a leaking washer or non-working fridge, we try to prioritize. When works for you?" },
        { question: 'What brands do you work on?', answer: "We service {{brands}}. We carry common parts for most major brands." },
        { question: 'Do you guarantee your work?', answer: "{{warranty_policy}}" },
        { question: 'Should I repair or replace?', answer: "That depends on the age and condition of the appliance. Our technician will give you an honest assessment. As a general rule, if the repair costs more than 50% of a new one, replacement may be smarter." },
      ],
      transferTriggers: [
        'Active water leak or gas smell (urgent)',
        'Warranty or insurance claim',
        'Commercial or multi-unit property',
        'Complaint about previous repair',
      ],
      escalationRules: {
        urgentKeywords: ['gas smell', 'leaking', 'flooding', 'sparking', 'smoke', 'fire', 'emergency'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. If you smell gas, leave the house and call your gas company immediately. For non-emergencies, leave a message and we'll call you back first thing.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Business Info',
          description: "Let's set up your appliance repair business.",
          fields: [
            { id: 'business_name', label: 'Business Name', type: 'text', required: true, placeholder: 'e.g., ProFix Appliance Repair' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'service_area', label: 'Service Area', type: 'text', required: true, placeholder: 'e.g., within 25 miles of downtown' },
          ],
        },
        {
          id: 'services',
          title: 'What You Fix',
          description: 'Tell us about your repair services.',
          fields: [
            { id: 'appliances_serviced', label: 'Appliances You Service', type: 'multiselect', required: true, options: ['Refrigerators', 'Washers', 'Dryers', 'Dishwashers', 'Ovens/Ranges', 'Microwaves', 'Garbage Disposals', 'Ice Makers', 'Wine Coolers', 'Freezers'] },
            { id: 'brands', label: 'Brands Serviced', type: 'text', required: true, placeholder: 'e.g., all major brands including Samsung, LG, Whirlpool, GE, Maytag, Frigidaire, Bosch, KitchenAid' },
            { id: 'diagnostic_fee', label: 'Diagnostic/Service Call Fee', type: 'text', required: true, placeholder: 'e.g., $89 diagnostic fee, waived if you proceed with the repair' },
            { id: 'repair_range', label: 'Typical Repair Range', type: 'text', required: true, placeholder: 'e.g., $150-$400' },
          ],
        },
        {
          id: 'operations',
          title: 'Operations',
          description: 'How do you run your service?',
          fields: [
            { id: 'availability', label: 'Typical Availability', type: 'text', required: true, placeholder: 'e.g., same-day or next-day' },
            { id: 'warranty_policy', label: 'Warranty on Repairs', type: 'text', required: true, placeholder: 'e.g., 90-day warranty on all labor and parts' },
            { id: 'hours', label: 'Service Hours', type: 'text', required: true, placeholder: 'Mon-Fri 8am-6pm, Sat 9am-2pm' },
          ],
        },
        {
          id: 'scheduling',
          title: 'Scheduling',
          description: 'How do you handle appointments?',
          fields: [
            { id: 'appointment_windows', label: 'Appointment Windows', type: 'text', required: true, placeholder: 'e.g., 2-hour windows: 8-10am, 10am-12pm, 12-2pm, 2-4pm' },
            { id: 'same_day', label: 'Offer Same-Day Service?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'todays-calls', type: 'list', title: "Today's Service Calls", dataSource: 'appointments_today', refreshInterval: 300 },
      { id: 'pending-bookings', type: 'list', title: 'Pending Booking Requests', dataSource: 'bookings_pending', refreshInterval: 600 },
      { id: 'weekly-revenue', type: 'metric', title: 'Weekly Revenue', dataSource: 'revenue_weekly', refreshInterval: 3600 },
      { id: 'parts-needed', type: 'alert', title: 'Parts on Order', dataSource: 'parts_pending', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'appointment-confirm', title: 'Confirm Appointments', description: 'Send confirmation texts for tomorrow\'s appointments', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'followup-repair', title: 'Follow-Up After Repair', description: 'Check in with customers 3 days after repair to ensure everything is working', difficulty: 'automatic', estimatedMinutes: 2 },
      { id: 'review-request', title: 'Request Reviews', description: 'Send review requests after completed repairs', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 15000, currentValue: 0 },
      { id: 'calls-per-day', label: 'Service Calls/Day', format: 'number', target: 4, currentValue: 0 },
      { id: 'avg-ticket', label: 'Average Ticket', format: 'currency', target: 225, currentValue: 0 },
      { id: 'first-visit-fix', label: 'First-Visit Fix Rate', format: 'percentage', target: 80, currentValue: 0 },
    ],
    integrations: [
      { id: 'google-calendar', name: 'Google Calendar', category: 'calendar', priority: 'essential', setupTime: 5 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'appointment-confirm', name: 'Appointment Confirmation', subject: 'Your appliance repair appointment with {{business_name}}', body: "Hi {{customer_name}},\n\nYour repair appointment is confirmed:\n\n📅 {{appointment_date}}\n⏰ Window: {{appointment_window}}\n🔧 Appliance: {{appliance_type}}\n💰 Diagnostic Fee: {{diagnostic_fee}} (applied to repair if you proceed)\n\nOur technician will call 30 minutes before arrival. Please make sure the appliance is accessible.\n\n{{business_name}}\n{{phone}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'tech-enroute', name: 'Tech En Route', body: 'Hi {{customer_name}}! Your {{business_name}} technician is on the way. ETA: {{eta}}. Please make sure the {{appliance_type}} is accessible. See you soon!', trigger: 'automated' },
      { id: 'followup', name: 'Post-Repair Follow-Up', body: 'Hi {{customer_name}}, this is {{business_name}} checking in. How is your {{appliance_type}} working? If you have any issues, call us — your repair is under warranty. 👍', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'appliance-repair', 'repair', 'home-service'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'phone-repair',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'phone-repair',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Cracked screens and dead phones? We fix them fast.',
      description: 'A phone and device repair shop offering quick, quality repairs for smartphones, tablets, and laptops — often while you wait.',
      primaryColor: '#00ACC1',
      secondaryColor: '#E0F7FA',
      tone: 'tech-savvy, quick, reliable',
      personality: 'Like the tech genius friend who can fix anything and explains what happened in plain English — no geek speak, just results.',
    },
    demoExperience: {
      headline: 'Your Repair Shop, Always Charged Up',
      subheadline: 'Mouse handles repair inquiries, status updates, and walk-in management — so you can focus on fixing devices.',
      heroImage: 'phone-repair-technician-workbench',
      socialProof: 'Phone repair shops using Mouse see 30% more walk-ins through instant text responses.',
      ctaText: 'See Your Shop on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your repair shop business advisor',
      greeting: "Hey, tech boss! Let's keep your repair bench full and your customers happy. I'll handle the calls and status updates so you can focus on the repairs.",
      sampleAdvice: [
        'iPhone screen repairs are 60% of your revenue. Make sure you always have iPhone 13-15 screens in stock — you ran out twice last month.',
        'Your average repair takes 45 minutes but customers wait 90 minutes. Consider a text-when-ready system so they can grab coffee next door.',
        'Back-to-school season drives a 30% spike in repairs. Stock up on popular parts now.',
      ],
      knowledgeDomains: ['device repair', 'parts inventory', 'mobile technology', 'customer flow', 'warranty management', 'data privacy'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. Got a broken phone, tablet, or laptop? I can give you a quick price estimate, check repair status, or answer any questions. What device needs help?",
      personality: "Quick and friendly. Understands that a broken phone feels like an emergency. Gives fast price quotes and turnaround times. Speaks in plain language, not tech jargon.",
      faqs: [
        { question: 'How much does a screen repair cost?', answer: "Screen repair prices depend on your device model. {{screen_pricing}}. Want an exact quote? Tell me your phone model and I'll look it up!" },
        { question: 'How long does a repair take?', answer: "Most repairs take {{typical_turnaround}}. Some complex repairs may take longer — we'll let you know upfront." },
        { question: 'Do you fix [specific device]?', answer: "We repair {{devices_serviced}}. If it has a screen and a battery, we can probably fix it!" },
        { question: 'Will I lose my data?', answer: "For most repairs (screens, batteries, charging ports), your data stays safe. If there's any risk of data loss, we'll tell you before we start and recommend a backup." },
        { question: 'Do you use original parts?', answer: "{{parts_policy}}" },
        { question: 'Do you have a warranty?', answer: "{{warranty_policy}}" },
        { question: 'Is my repair ready?', answer: "Let me check! What's your name or phone number? I'll look up your repair status." },
      ],
      transferTriggers: [
        'Water damage or complex repair',
        'Data recovery request',
        'Complaint about repair quality',
        'Business or bulk device repair',
      ],
      escalationRules: {
        urgentKeywords: ['data recovery', 'water damage', 'lost everything', 'urgent', 'complaint', 'worse'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For repair status, text us your name. Walk-ins welcome during business hours — no appointment needed!",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Shop Info',
          description: "Let's set up your repair shop.",
          fields: [
            { id: 'business_name', label: 'Shop Name', type: 'text', required: true, placeholder: 'e.g., QuickFix Phone Repair' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Business Hours', type: 'text', required: true, placeholder: 'Mon-Sat 10am-7pm, Sun 12pm-5pm' },
            { id: 'address', label: 'Shop Address', type: 'text', required: true },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What do you repair?',
          fields: [
            { id: 'devices_serviced', label: 'Devices You Repair', type: 'multiselect', required: true, options: ['iPhones', 'Samsung Galaxy', 'Google Pixel', 'Other Android', 'iPads', 'Android Tablets', 'MacBooks', 'Windows Laptops', 'Game Consoles'] },
            { id: 'screen_pricing', label: 'Screen Repair Pricing', type: 'text', required: true, placeholder: 'e.g., iPhone screens from $79, Samsung screens from $99, iPad screens from $129' },
            { id: 'typical_turnaround', label: 'Typical Repair Time', type: 'text', required: true, placeholder: 'e.g., 30-60 minutes for most screen and battery repairs' },
          ],
        },
        {
          id: 'quality',
          title: 'Quality & Warranty',
          description: 'Your quality standards.',
          fields: [
            { id: 'parts_policy', label: 'Parts Policy', type: 'text', required: true, placeholder: 'e.g., We offer both OEM and high-quality aftermarket parts. We always discuss options with you before starting.' },
            { id: 'warranty_policy', label: 'Repair Warranty', type: 'text', required: true, placeholder: 'e.g., Lifetime warranty on all screen repairs. 90 days on other repairs.' },
          ],
        },
        {
          id: 'extras',
          title: 'Extras',
          description: 'Any additional services?',
          fields: [
            { id: 'sell_accessories', label: 'Sell Accessories?', type: 'toggle', required: false, defaultValue: true },
            { id: 'buy_devices', label: 'Buy Used Devices?', type: 'toggle', required: false, defaultValue: false },
            { id: 'mail_in', label: 'Accept Mail-In Repairs?', type: 'toggle', required: false, defaultValue: false },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'active-repairs', type: 'list', title: 'Active Repairs', dataSource: 'repairs_active', refreshInterval: 300 },
      { id: 'ready-pickup', type: 'alert', title: 'Ready for Pickup', dataSource: 'repairs_ready', refreshInterval: 600 },
      { id: 'daily-revenue', type: 'metric', title: "Today's Revenue", dataSource: 'revenue_daily', refreshInterval: 300 },
      { id: 'popular-repairs', type: 'chart', title: 'Top Repairs This Week', dataSource: 'repairs_by_type', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'repair-ready', title: 'Notify Repairs Ready', description: 'Text customers when their device is repaired and ready', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'pickup-reminder', title: 'Pickup Reminders', description: 'Remind customers with devices ready for 3+ days', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'review-request', title: 'Request Reviews', description: 'Send review request after device pickup', difficulty: 'automatic', estimatedMinutes: 1 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 12000, currentValue: 0 },
      { id: 'repairs-per-day', label: 'Repairs/Day', format: 'number', target: 8, currentValue: 0 },
      { id: 'avg-repair', label: 'Average Repair Value', format: 'currency', target: 120, currentValue: 0 },
      { id: 'turnaround', label: 'Avg Turnaround (min)', format: 'number', target: 45, currentValue: 0 },
    ],
    integrations: [
      { id: 'repairdesk', name: 'RepairDesk', category: 'pos', priority: 'recommended', setupTime: 20 },
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'yelp', name: 'Yelp', category: 'listings', priority: 'recommended', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'repair-complete', name: 'Repair Complete', subject: 'Your {{device}} is fixed! — {{business_name}}', body: "Hi {{customer_name}},\n\nGood news — your {{device}} repair is complete and ready for pickup!\n\n{{address}}\n{{hours}}\n\nDon't forget — your repair comes with our {{warranty_policy}}.\n\nSee you soon!\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'repair-done', name: 'Repair Done', body: '✅ Hi {{customer_name}}! Your {{device}} at {{business_name}} is fixed and ready for pickup. We\'re open {{hours}}.', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'phone-repair', 'device-repair', 'tech'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'tailor-shop',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'tailor-shop',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'The perfect fit, every time',
      description: 'A professional tailor and alterations shop where skilled hands transform how your clothes look and feel — because the right fit changes everything.',
      primaryColor: '#6D4C41',
      secondaryColor: '#EFEBE9',
      tone: 'skilled, meticulous, personable',
      personality: 'Like a master craftsperson who takes pride in every stitch and makes you feel like a million bucks when your clothes fit perfectly.',
    },
    demoExperience: {
      headline: 'Your Tailor Shop, Perfectly Fitted',
      subheadline: 'Mouse handles order tracking, pickup notifications, and customer communication — so you can focus on your craft.',
      heroImage: 'tailor-measuring-suit-fitting',
      socialProof: 'Tailor shops using Mouse see 30% fewer unclaimed orders through automated pickup reminders.',
      ctaText: 'See Your Shop on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your tailor shop business advisor',
      greeting: "Welcome, master tailor! Let's make sure your skills get the business they deserve. I'll handle the customer communication so you can focus on making people look amazing.",
      sampleAdvice: [
        'Wedding season starts in 8 weeks. Last year you did 40+ bridesmaid dress alterations. Time to promote your bridal alteration services.',
        'You have 18 orders ready for pickup. Unclaimed orders tie up your rack space — let me send reminders.',
        'Your prom season alterations average $65 per garment with 80% margins. Start marketing to local dress shops as an alteration partner.',
      ],
      knowledgeDomains: ['tailoring', 'alterations', 'garment construction', 'fabric knowledge', 'bridal alterations', 'custom clothing'],
    },
    aiReceptionist: {
      greeting: "Hi, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with alteration pricing, turnaround times, order status, or anything else. What do you need fitted?",
      personality: "Warm and knowledgeable. Makes people feel confident that their garment is in expert hands. Explains alterations in simple terms. Understanding that special occasion alterations (wedding, prom) come with extra emotions and deadlines.",
      faqs: [
        { question: 'How much do alterations cost?', answer: "{{pricing_info}}" },
        { question: 'How long do alterations take?', answer: "Standard alterations take {{standard_turnaround}}. Rush service is available for {{rush_policy}}." },
        { question: 'Do I need an appointment?', answer: "{{appointment_policy}}" },
        { question: 'Do you do wedding dress alterations?', answer: "{{bridal_services}}" },
        { question: 'Can you make custom clothing?', answer: "{{custom_clothing}}" },
        { question: 'Is my order ready?', answer: "Let me check! What's the name on the order? I'll look it up for you." },
      ],
      transferTriggers: [
        'Bridal gown consultation',
        'Custom suit or clothing request',
        'Complaint about alteration quality',
        'Complex or unusual garment',
      ],
      escalationRules: {
        urgentKeywords: ['wedding tomorrow', 'prom tonight', 'ruined', 'wrong', 'emergency', 'urgent'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For order status, text us your name. For fitting appointments, leave a message and we'll call you back.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Shop Info',
          description: "Let's set up your tailor shop.",
          fields: [
            { id: 'business_name', label: 'Shop Name', type: 'text', required: true, placeholder: 'e.g., Perfect Stitch Tailoring' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Business Hours', type: 'text', required: true, placeholder: 'Mon-Fri 9am-6pm, Sat 10am-3pm' },
            { id: 'address', label: 'Shop Address', type: 'text', required: true },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What alterations do you offer?',
          fields: [
            { id: 'pricing_info', label: 'Common Alteration Prices', type: 'text', required: true, placeholder: 'e.g., Hems $15-$25, Waist $20-$35, Zippers $15-$25, Suit tailoring from $50' },
            { id: 'standard_turnaround', label: 'Standard Turnaround', type: 'text', required: true, placeholder: 'e.g., 5-7 business days' },
            { id: 'rush_policy', label: 'Rush Service', type: 'text', required: false, placeholder: 'e.g., 24-48 hour rush available for 50% surcharge' },
          ],
        },
        {
          id: 'specialty',
          title: 'Specialty Services',
          description: 'Any special services?',
          fields: [
            { id: 'bridal_services', label: 'Bridal Alterations', type: 'text', required: false, placeholder: 'e.g., Yes! Wedding dress alterations from $150. We recommend booking 8-10 weeks before the wedding.' },
            { id: 'custom_clothing', label: 'Custom Clothing', type: 'text', required: false, placeholder: 'e.g., Yes, custom suits and shirts. Consultation required — starting at $500 for custom suits.' },
            { id: 'appointment_policy', label: 'Appointment Policy', type: 'text', required: true, placeholder: 'e.g., Walk-ins welcome for simple alterations. Appointments recommended for bridal and custom work.' },
          ],
        },
        {
          id: 'notifications',
          title: 'Customer Notifications',
          description: 'How should we notify customers?',
          fields: [
            { id: 'notify_ready', label: 'Text When Order Ready?', type: 'toggle', required: false, defaultValue: true },
            { id: 'remind_unclaimed', label: 'Remind After 7 Days Unclaimed?', type: 'toggle', required: false, defaultValue: true },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'active-orders', type: 'metric', title: 'Active Orders', dataSource: 'orders_active', refreshInterval: 600 },
      { id: 'ready-pickup', type: 'list', title: 'Ready for Pickup', dataSource: 'orders_ready', refreshInterval: 600 },
      { id: 'fittings-today', type: 'list', title: "Today's Fittings", dataSource: 'appointments_today', refreshInterval: 600 },
      { id: 'daily-revenue', type: 'metric', title: "Today's Revenue", dataSource: 'revenue_daily', refreshInterval: 300 },
    ],
    sampleTasks: [
      { id: 'order-ready', title: 'Notify Orders Ready', description: 'Text customers when their alterations are done', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'pickup-reminder', title: 'Pickup Reminders', description: 'Remind customers with orders ready for 7+ days', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'bridal-promo', title: 'Bridal Season Promotion', description: 'Promote bridal alteration services ahead of wedding season', difficulty: 'needs-approval', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 8000, currentValue: 0 },
      { id: 'orders-per-week', label: 'Orders per Week', format: 'number', target: 35, currentValue: 0 },
      { id: 'avg-ticket', label: 'Average Ticket', format: 'currency', target: 40, currentValue: 0 },
      { id: 'pickup-rate', label: 'Same-Week Pickup Rate', format: 'percentage', target: 80, currentValue: 0 },
    ],
    integrations: [
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'order-ready', name: 'Order Ready', subject: 'Your alterations are ready at {{business_name}}!', body: "Hi {{customer_name}},\n\nYour garment is altered and ready for pickup!\n\n{{address}}\n{{hours}}\n\nCan't wait for you to see the perfect fit.\n\n{{business_name}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'order-ready-sms', name: 'Order Ready', body: '✂️ Hi {{customer_name}}! Your alterations at {{business_name}} are done and ready for pickup. We\'re open {{hours}}.', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'tailor', 'alterations', 'sewing'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'print-shop',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'print-shop',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Your ideas, printed perfectly',
      description: 'A full-service print shop offering business cards, banners, signs, custom apparel, promotional products, and more — with personal service and expert guidance.',
      primaryColor: '#C62828',
      secondaryColor: '#FFEBEE',
      tone: 'creative, capable, reliable',
      personality: 'Like a creative partner who turns your ideas into reality — whether it\'s 100 business cards or 10,000 event programs.',
    },
    demoExperience: {
      headline: 'Your Print Shop, Making an Impression',
      subheadline: 'Mouse handles order inquiries, proofing, and pickup notifications — so you can focus on producing great print work.',
      heroImage: 'print-shop-colorful-products-display',
      socialProof: 'Print shops using Mouse complete 25% more orders through streamlined proof approval.',
      ctaText: 'See Your Shop on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your print shop business advisor',
      greeting: "Hey there, print pro! Let's keep your presses running and your customers coming back. I'll handle the communication so you can focus on producing great work.",
      sampleAdvice: [
        'You have 4 jobs waiting on proof approval. Proof delays are the #1 cause of missed deadlines — want me to send approval reminders?',
        'Graduation season starts in 6 weeks. Banners, invitations, and party supplies are big sellers — time to promote.',
        'Your average order is $180 but custom apparel orders average $500. Consider marketing your screen printing and embroidery more.',
      ],
      knowledgeDomains: ['commercial printing', 'graphic design', 'large format printing', 'custom apparel', 'promotional products', 'print technology'],
    },
    aiReceptionist: {
      greeting: "Hey, thanks for calling {{business_name}}! This is Mouse, our virtual assistant. I can help with printing quotes, order status, or questions about our services. What do you need printed?",
      personality: "Helpful and creative. Asks the right questions about projects: quantity, size, paper stock, deadline. Makes printing feel approachable for people who aren't sure what they need. Never condescending about design quality.",
      faqs: [
        { question: 'What do you print?', answer: "We print {{services_offered}}. If you need it printed, we can probably do it!" },
        { question: 'How much does it cost?', answer: "Pricing depends on the product, quantity, and specs. {{pricing_examples}}. For an exact quote, tell me what you need and I'll price it right out." },
        { question: 'How fast can you turn it around?', answer: "Standard turnaround is {{standard_turnaround}}. {{rush_policy}}" },
        { question: 'Can you help with design?', answer: "{{design_services}}" },
        { question: 'Do I need to bring a file?', answer: "{{file_requirements}}" },
        { question: 'Is my order ready?', answer: "Let me check! What's the name on the order?" },
      ],
      transferTriggers: [
        'Large commercial order over $1,000',
        'Custom design consultation',
        'Complaint about print quality',
        'Rush order needing same-day',
      ],
      escalationRules: {
        urgentKeywords: ['rush', 'today', 'tomorrow', 'wrong color', 'misprint', 'deadline', 'emergency'],
        afterHoursMessage: "Thanks for calling {{business_name}}! We're closed now but open at {{next_open}}. For order status, text us your name. For new orders, email {{email}} with your project details and we'll have a quote ready when we open.",
        maxTransferAttempts: 2,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Shop Info',
          description: "Let's set up your print shop.",
          fields: [
            { id: 'business_name', label: 'Shop Name', type: 'text', required: true, placeholder: 'e.g., FastPrint Solutions' },
            { id: 'phone', label: 'Phone Number', type: 'phone', required: true },
            { id: 'hours', label: 'Business Hours', type: 'text', required: true, placeholder: 'Mon-Fri 8am-6pm, Sat 9am-2pm' },
            { id: 'address', label: 'Shop Address', type: 'text', required: true },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What do you print?',
          fields: [
            { id: 'services_offered', label: 'Services', type: 'multiselect', required: true, options: ['Business Cards', 'Flyers/Brochures', 'Banners/Signs', 'Posters', 'Custom T-Shirts', 'Embroidery', 'Stickers/Labels', 'Invitations', 'Envelopes/Letterhead', 'Booklets/Catalogs', 'Vehicle Wraps', 'Window Graphics'] },
            { id: 'pricing_examples', label: 'Pricing Examples', type: 'text', required: true, placeholder: 'e.g., Business cards from $29/500, Banners from $3/sq ft, Custom tees from $12/shirt (min 12)' },
            { id: 'design_services', label: 'Design Services', type: 'text', required: false, placeholder: 'e.g., Yes! In-house design starting at $50/hour. We can design from scratch or clean up your existing files.' },
          ],
        },
        {
          id: 'production',
          title: 'Production Details',
          description: 'Your turnaround and processes.',
          fields: [
            { id: 'standard_turnaround', label: 'Standard Turnaround', type: 'text', required: true, placeholder: 'e.g., 3-5 business days for most orders' },
            { id: 'rush_policy', label: 'Rush Service', type: 'text', required: false, placeholder: 'e.g., Same-day and next-day rush available for most products at 50% surcharge.' },
            { id: 'file_requirements', label: 'File Requirements', type: 'text', required: true, placeholder: 'e.g., We accept PDF, AI, PSD, PNG, and JPG. 300 DPI minimum for best quality. Not sure? Bring what you have and we\'ll help.' },
          ],
        },
        {
          id: 'online',
          title: 'Online Presence',
          description: 'Where can customers find you?',
          fields: [
            { id: 'email', label: 'Business Email', type: 'email', required: true },
            { id: 'website', label: 'Website', type: 'url', required: false },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'active-orders', type: 'list', title: 'Active Orders', dataSource: 'orders_active', refreshInterval: 600 },
      { id: 'awaiting-approval', type: 'alert', title: 'Awaiting Proof Approval', dataSource: 'proofs_pending', refreshInterval: 1800 },
      { id: 'ready-pickup', type: 'list', title: 'Ready for Pickup', dataSource: 'orders_ready', refreshInterval: 600 },
      { id: 'monthly-revenue', type: 'metric', title: 'Monthly Revenue', dataSource: 'revenue_monthly', refreshInterval: 86400 },
    ],
    sampleTasks: [
      { id: 'proof-reminder', title: 'Proof Approval Reminders', description: 'Remind customers to approve their proofs so production can start', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'order-ready', title: 'Order Ready Notification', description: 'Text customers when their print order is ready', difficulty: 'automatic', estimatedMinutes: 1 },
      { id: 'reorder-outreach', title: 'Reorder Outreach', description: 'Reach out to customers who may need to reorder business cards or materials', difficulty: 'needs-approval', estimatedMinutes: 3 },
    ],
    kpis: [
      { id: 'monthly-revenue', label: 'Monthly Revenue', format: 'currency', target: 18000, currentValue: 0 },
      { id: 'orders-per-week', label: 'Orders per Week', format: 'number', target: 25, currentValue: 0 },
      { id: 'avg-order', label: 'Average Order', format: 'currency', target: 180, currentValue: 0 },
      { id: 'on-time-rate', label: 'On-Time Delivery Rate', format: 'percentage', target: 95, currentValue: 0 },
    ],
    integrations: [
      { id: 'square', name: 'Square', category: 'payments', priority: 'essential', setupTime: 10 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
      { id: 'canva', name: 'Canva', category: 'design', priority: 'nice-to-have', setupTime: 5 },
    ],
    emailTemplates: [
      { id: 'proof-ready', name: 'Proof Ready for Approval', subject: 'Your proof is ready — {{business_name}}', body: "Hi {{customer_name}},\n\nYour proof is ready for review! Please take a look and let us know if it's approved or if you'd like changes.\n\nView your proof: {{proof_link}}\n\nOnce approved, we'll start production right away. Estimated completion: {{estimated_date}}.\n\n{{business_name}}\n{{phone}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'order-ready-sms', name: 'Order Ready', body: '🖨️ Hi {{customer_name}}! Your print order at {{business_name}} is done and ready for pickup. We\'re open {{hours}}.', trigger: 'automated' },
      { id: 'proof-reminder', name: 'Proof Reminder', body: 'Hi {{customer_name}}, we\'re waiting on your proof approval for your {{business_name}} order. Please check your email and approve so we can start printing! 📋', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'print-shop', 'printing', 'custom-apparel'],
      requiredPlan: 'pro',
    },
  },

  {
    id: 'funeral-home',
    version: '1.0.0',
    vertical: 'specialty-services',
    subVertical: 'funeral-home',
    identity: {
      businessName: '{{business_name}}',
      tagline: 'Honoring lives with dignity and compassion',
      description: 'A funeral home providing compassionate, dignified end-of-life services — guiding families through one of the most difficult times with care, respect, and unwavering support.',
      primaryColor: '#37474F',
      secondaryColor: '#F5F5F5',
      tone: 'compassionate, dignified, gentle',
      personality: 'Like a caring, steady guide who walks alongside families during their most difficult moments — offering comfort, clarity, and genuine kindness without ever rushing.',
    },
    demoExperience: {
      headline: 'Your Funeral Home, Serving Families with Grace',
      subheadline: 'Mouse handles initial inquiries, pre-planning consultations, and aftercare follow-ups — so you can give every family your full compassionate attention.',
      heroImage: 'funeral-home-chapel-peaceful-flowers',
      socialProof: 'Funeral homes using Mouse ensure no family call goes unanswered — even at 2 AM.',
      ctaText: 'See Your Funeral Home on Mouse',
    },
    kingMousePersonality: {
      name: 'King Mouse',
      role: 'Your funeral home business advisor',
      greeting: "I understand the weight of the work you do, and I'm here to help with the business side so you can focus entirely on the families you serve. Let's make sure no family falls through the cracks.",
      sampleAdvice: [
        'You served the Henderson family 30 days ago. The first month is the hardest — want me to send a gentle check-in with grief support resources?',
        'Pre-need planning inquiries have increased 20% this month. Consider hosting a free community seminar on advance planning.',
        'Your aftercare program reaches families at 1 week and 1 month. Industry best practice adds a 6-month and 1-year touchpoint. Want me to set those up?',
      ],
      knowledgeDomains: ['funeral service', 'pre-need planning', 'grief support', 'FTC funeral rule compliance', 'aftercare programs', 'community outreach'],
    },
    aiReceptionist: {
      greeting: "Thank you for calling {{business_name}}. This is Mouse, our virtual assistant. I'm here to help however I can. Whether you need to make arrangements, have questions about our services, or need to reach someone, I'm here for you.",
      personality: "Deeply compassionate and calm. Speaks gently and never rushes. Understands that callers may be in shock, grief, or distress. Uses soft, respectful language. NEVER uses sales language or upselling. Treats every call as sacred. If someone is calling about an immediate death, connects them to staff immediately.",
      faqs: [
        { question: 'Someone just passed away. What do I do?', answer: "I'm so sorry for your loss. Let me connect you with our funeral director right away. They will guide you through everything, step by step. If you're at a hospital or care facility, they can also help with transportation. Let me get someone on the line for you." },
        { question: 'What are your services?', answer: "We offer {{services_offered}}. Every family is different, and we work with you to create a service that truly honors your loved one." },
        { question: 'How much do funerals cost?', answer: "We understand cost is an important consideration. Our services range from {{price_range}}. We provide a detailed price list as required by law, and we'll work with any budget to create a meaningful service. There's never any pressure." },
        { question: 'Do you offer pre-planning?', answer: "Yes. Pre-planning is one of the most thoughtful gifts you can give your family. It removes the burden of difficult decisions during an emotional time. We offer free, no-obligation pre-planning consultations." },
        { question: 'Do you offer cremation?', answer: "{{cremation_services}}" },
        { question: 'Can you help with veterans\' benefits?', answer: "{{veterans_services}}" },
      ],
      transferTriggers: [
        'Immediate death — ALWAYS transfer immediately',
        'Family ready to make arrangements',
        'Pre-need planning consultation',
        'Grief counseling or aftercare request',
        'Any caller who is distressed',
      ],
      escalationRules: {
        urgentKeywords: ['just died', 'just passed', 'passed away', 'death', 'deceased', 'hospital', 'coroner', 'hospice', 'transport body'],
        afterHoursMessage: "Thank you for calling {{business_name}}. We are available 24 hours a day, 7 days a week. If you need immediate assistance, please stay on the line and your call will be forwarded to our on-call funeral director. We are here for you.",
        maxTransferAttempts: 5,
        fallbackAction: 'voicemail',
      },
    },
    onboardingWizard: {
      steps: [
        {
          id: 'basics',
          title: 'Your Funeral Home Info',
          description: "Let's set up your funeral home profile with care.",
          fields: [
            { id: 'business_name', label: 'Funeral Home Name', type: 'text', required: true, placeholder: 'e.g., Meadowbrook Funeral Home' },
            { id: 'phone', label: 'Main Phone (24/7)', type: 'phone', required: true },
            { id: 'address', label: 'Address', type: 'text', required: true },
            { id: 'after_hours_phone', label: 'After-Hours Direct Line', type: 'phone', required: true },
          ],
        },
        {
          id: 'services',
          title: 'Your Services',
          description: 'What services do you provide?',
          fields: [
            { id: 'services_offered', label: 'Services', type: 'multiselect', required: true, options: ['Traditional Funeral', 'Memorial Service', 'Cremation', 'Direct Burial', 'Direct Cremation', 'Graveside Service', 'Celebration of Life', 'Pre-Planning', 'Grief Support', 'Veterans Services'] },
            { id: 'price_range', label: 'Service Price Range', type: 'text', required: true, placeholder: 'e.g., from $1,500 for direct cremation to $8,000+ for full traditional services' },
            { id: 'cremation_services', label: 'Cremation Details', type: 'text', required: false, placeholder: 'e.g., Yes, we offer direct cremation, cremation with memorial service, and full funeral followed by cremation.' },
          ],
        },
        {
          id: 'community',
          title: 'Community & Aftercare',
          description: 'How do you serve families after the service?',
          fields: [
            { id: 'veterans_services', label: 'Veterans Services', type: 'text', required: false, placeholder: 'e.g., Absolutely. We help families access VA burial benefits, military honors, and flag presentations. We handle all the paperwork.' },
            { id: 'grief_support', label: 'Grief Support Programs', type: 'text', required: false, placeholder: 'e.g., We offer grief support groups, individual counseling referrals, and resource guides for families.' },
            { id: 'aftercare_program', label: 'Aftercare Program', type: 'text', required: false, placeholder: 'e.g., We check in with families at 1 week, 1 month, and around the anniversary with support resources.' },
          ],
        },
        {
          id: 'details',
          title: 'Additional Details',
          description: 'Anything else families should know.',
          fields: [
            { id: 'chapel_capacity', label: 'Chapel Capacity', type: 'number', required: false, placeholder: '200' },
            { id: 'languages', label: 'Languages Spoken', type: 'text', required: false, placeholder: 'e.g., English and Spanish' },
          ],
        },
      ],
    },
    dashboardWidgets: [
      { id: 'active-cases', type: 'list', title: 'Active Cases', dataSource: 'cases_active', refreshInterval: 1800 },
      { id: 'upcoming-services', type: 'list', title: 'Upcoming Services', dataSource: 'services_upcoming', refreshInterval: 3600 },
      { id: 'aftercare-due', type: 'alert', title: 'Aftercare Follow-Ups Due', dataSource: 'aftercare_due', refreshInterval: 86400 },
      { id: 'preneed-inquiries', type: 'list', title: 'Pre-Need Inquiries', dataSource: 'inquiries_preneed', refreshInterval: 3600 },
    ],
    sampleTasks: [
      { id: 'aftercare-checkin', title: 'Aftercare Check-In', description: 'Send gentle check-in messages to families at 1-week, 1-month, and anniversary milestones', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'preneed-followup', title: 'Pre-Need Follow-Up', description: 'Follow up with families who expressed interest in pre-planning', difficulty: 'needs-approval', estimatedMinutes: 5 },
      { id: 'community-outreach', title: 'Community Education', description: 'Promote upcoming community seminars on pre-planning or grief support', difficulty: 'needs-approval', estimatedMinutes: 5 },
    ],
    kpis: [
      { id: 'families-served', label: 'Families Served/Month', format: 'number', target: 15, currentValue: 0 },
      { id: 'preneed-plans', label: 'Pre-Need Plans Sold', format: 'number', target: 5, currentValue: 0 },
      { id: 'aftercare-completion', label: 'Aftercare Completion', format: 'percentage', target: 90, currentValue: 0 },
      { id: 'avg-service-value', label: 'Average Service Value', format: 'currency', target: 5000, currentValue: 0 },
    ],
    integrations: [
      { id: 'frontrunner', name: 'FrontRunner', category: 'website', priority: 'recommended', setupTime: 20 },
      { id: 'passare', name: 'Passare', category: 'case-management', priority: 'recommended', setupTime: 25 },
      { id: 'google-business', name: 'Google Business Profile', category: 'listings', priority: 'essential', setupTime: 10 },
    ],
    emailTemplates: [
      { id: 'aftercare-1month', name: '1-Month Aftercare', subject: 'Thinking of you — {{business_name}}', body: "Dear {{family_name}} Family,\n\nIt has been about a month since {{deceased_name}}'s service, and we wanted you to know we're still thinking of you.\n\nGrief doesn't follow a timeline, and whatever you're feeling right now is completely normal. We've included some resources below that other families have found helpful:\n\n{{grief_resources}}\n\nIf you need anything at all — whether it's a question about the service, help with paperwork, or just someone to talk to — please don't hesitate to reach out.\n\nWith deepest sympathy,\n{{business_name}}\n{{phone}}", trigger: 'automated' },
    ],
    smsTemplates: [
      { id: 'aftercare-sms', name: 'Aftercare Check-In', body: 'Dear {{family_name}} family, we\'re thinking of you. If you need anything at all, {{business_name}} is here. {{phone}} 💙', trigger: 'automated' },
    ],
    metadata: {
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      author: 'Mouse Platform',
      tags: ['specialty', 'funeral-home', 'end-of-life', 'grief-support'],
      requiredPlan: 'pro',
    },
  },
];
